AOMediaCodec/SVT-AV1

- Source/App/EbAppMain.c
This will kick in if the main process receives a second SIGINT.
> main: restore default sigint handler

- Source/App/EbAppConfig.c
- Source/App/EbAppConfig.h
- Source/App/EbAppInputy4m.c
- Source/App/EbAppInputy4m.h
- Source/App/EbAppProcessCmd.c
Support for YUV4MPEG2 (.y4m) input files, all bit depths, standard input mode.
Reads the y4m header and saves the video's parameters (width, height, bitdepth, etc) to the config structure, so there is not need to specify them explicitly. 
In addition, when reading each frame, a delimited "FRAME\n" is removed.
More info about the YUV4MPEG2 format can be found here: https://wiki.multimedia.cx/index.php/YUV4MPEG2
> Initial support for YUV4MPEG2 (.y4m) input files

- .travis.yml
- README.md
Partly resolves #4.
First Travis implementation. It compiles SVT-AV1 on Ubuntu 16.04 and also applies the FFmpeg patch, that currently fails (see #15).
For optimal integration, Travis CI needs to be enabled on the [GitHub Marketplace](https://github.com/marketplace/travis-ci).
> Add basic Travis CI implementation

- README.md
- appveyor.yml
Part of #4.
This PR adds continuous integration & delivery with AppVeyor. SVT-AV1 gets build with Microsoft Visual Studio 2017 and Yasm 1.3.0. AppVeyor publishes `SvtAv1Enc.dll`, `SvtAv1Enc.exp`, `SvtAv1Enc.lib`, `SvtAv1EncApp.exe` and `SvtAv1EncSimpleApp.exe` in the Artifacts tab ([example](https://ci.appveyor.com/project/EwoutH/svt-av1/build/artifacts)).
AppVeyor needs to be enabled on the [GitHub Marketplace](https://github.com/marketplace/appveyor) or on [ci.AppVeyor.com](https://ci.appveyor.com/project/OpenVisualCloud/SVT-AV1).
When enabled, AppVeyor publishes the artifacts with each build. When tagging a new (pre)release, AppVeyor will also upload these files to GitHub, creating a release page [like this](https://github.com/EwoutH/SVT-AV1/releases/tag/0.0.1-test1).
To enable …
> Add AppVeyor CI/CD

- .travis.yml
- CMakeLists.txt
- README.md
I combined the recent Travis proposals in one PR, #22 and #23 where conflicting with each other.
- Adds macOS build (replaces PR #23)
- Adds Coveralls for code coverage (replaces PR #22)
- Allow FFmpeg patch job to fail (see issue #15)
> Add macOS & Coveralls to Travis

- Source/Lib/ASM_AVX2/variance_avx2.c
just noticed it will reading through the code.. Strange bug in MSVC compiler b.t.w...
> fix small typo in comment

- appveyor.yml
Resolves #48 (@kylophone).
AppVeyor had an [image update](https://www.appveyor.com/updates/2019/02/11/) yesterday which updated CMake to 3.13.3. This broke our AppVeyor config, this PR fixes that.
> Fix AppVeyor after image update

- Source/Lib/Codec/EbEncHandle.c
Return EB_ErrorBadParameter if the pointer is NULL
> Handle NULL Pointer in api functions

- .travis.yml
Since issue #15 is fixed with PR #57, the allow_failures for the FFmpeg patch can be removed.
> Require FFmpeg patch to build with Travis

- Source/Lib/Codec/EbIntraPrediction.c
Original implementation is dangerous, may break other parameters within the function stack
> Fix the parameter declare issue

- Source/Lib/Codec/EbFullLoop.c
> Remove unneeded memset() in av1_quantize_inv_quantize().

- Source/API/EbSvtAv1.h
- Source/API/EbSvtAv1Dec.h
- Source/API/EbSvtAv1Enc.h
- Source/API/EbSvtAv1ErrorCodes.h
- Source/API/EbSvtAv1ExtFrameBuf.h
- Source/API/EbSvtAv1Formats.h
- Source/API/EbSvtAv1Time.h
Currently, both SVT-AV1 and SVT-HEVC use the same header guards. Including one skips the other.
Required by #73.
```c
$ cat a.c
#include <EbApi.h>
#include <EbSvtAv1Enc.h>
$ cc -E a.c $(pkg-config SvtAv1Enc SvtHevcEnc --cflags) | fgrep EbSvtAv1EncConfiguration
$ cat b.c
#include <EbSvtAv1Enc.h>
$ cc -E b.c $(pkg-config SvtAv1Enc SvtHevcEnc --cflags) | fgrep EbSvtAv1EncConfiguration
typedef struct EbSvtAv1EncConfiguration
} EbSvtAv1EncConfiguration;
EbSvtAv1EncConfiguration *config_ptr);
EbSvtAv1EncConfiguration *pComponentParameterStructure);
```
> Allow inclusion of both SVT-AV1 and SVT-HEVC headers

- appveyor.yml
Stops AppVeyor from uploading the gtest and .exp artifacts after #181.
> AppVeyor: Don't upload & deploy unnecessary artifacts

- Build/linux/build.sh
- Source/Lib/Encoder/Codec/EbEncHandle.c
It's been slightly confusing when it would show gcc 4.2.1 even though it was clang.
Added a distinguisher between Apple, mingw, msvc, linux, and others.
Idk what the identifiers for other types would be.
> Print out clang version instead of gcc

- Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.h
- Source/Lib/Common/ASM_AVX2/highbd_fwd_txfm_avx2.c
av1_fwd_txfm2d_32x64_avx2()
Implemented load from int16_array_with_stride_to_int32_array_without_stride()
to AVX2, and other optimizations.
The increase in encoding speed was measured by ~ 1.4% in M6
Kernel Av1EstimateTransform take 7.1% insted of 8.5%
> Optimization the transformation in av1_fwd_txfm2d_64x64_avx2(),

- Docs/svt-av1_encoder_user_guide.md
Updates the user guide with the existence of enc-mode 8 after #185
> Update user guide with enc-mode 8

- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppInputy4m.c
- Source/Lib/Common/Codec/EbDefinitions.h
EB_STRNCPY assume the dest is a static array, so it will use sizeof(dst) to get the size
But it's not true in copyUntilCharacterOrNewLine. So the y4m as input is totally breaking.
Since we can't check the type of dst, assume it's static array is harmful.
Better let the user pass the dst size.
> y4m: fix parser error for y4m input

- README.md
- Adds info about the #svt IRC channel
- Uses smaller headings to save space
> Readme: Add IRC channel, use smaller headings

- README.md
- Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.asm
- Source/Lib/Common/ASM_SSE2/x64RegisterUtil.asm
- Source/Lib/Common/ASM_SSE2/x64inc.asm
- Source/Lib/Common/Codec/EbThreads.c
Asm prefix part taken from <https://aomedia.googlesource.com/aom/+/master/aom_ports/x86_abi_support.asm#95>.
Named semaphores must be unlinked else they will be orphaned but still contribute to the global semaphore count. As long as they are unlinked after being opened, they should not be orphaned. 
<https://bugs.chromium.org/p/nativeclient/issues/detail?id=686>
> Use prefix for asm files using AOM's method, add a note about macOS fd limit

- Docs/svt-av1_decoder_user_guide.md
Hi,
There was extra whitespace which made `Known Limitations` not able to redirect properly.
BR,
Vibhoothi
> docs/decoder: Fix the broken link

- STYLE.md
Could I add a note about using sed to remove trailing whitespace after coding? It's been quite annoying when the commits include deletion of whitespace, filling up the commit.
`find . -name <Filename> -type f -exec sed -i 's/[[:space:]]*$//' {} \;`
or
`sed -i 's/[[:space:]]*$//' <Filename>`
for bash
``` Powershell
ls -Recurse -File [-Filter *.c] | ForEach-Object{$(Get-Content $_.FullName | Foreach {Write-Output "$($_.TrimEnd())`n"}) | Set-Content -NoNewline $_.FullName}
```
for powershell
(I don't think it's possible for command prompt)
> Style: add syntax stuff for the code blocks in STYLE.md

- .gitignore
- Build/windows/build.bat
- Build/windows/generate_vs17.bat
- README.md
Renamed generate_vs2017 to generate and added switches for using different cmake generators.
Also only define char_bit if not defined (one of mingw's header already defines it as 8)
> Add switches for batch file for windows. Add VS2019

- Docs/svt-av1_decoder_user_guide.md
- Removed double spaces
- Added code blocks
- Fixed interpunction
- Removed main profile reference (AV1 main profile requires 10-bit and 4:0:0 support)
> Docs: Make the decoder guide readable

- Docs/svt-av1_encoder_user_guide.md
- Remove double spaces
- Use consistent image captions
- Use codeblocks for command lines
- Remove multiple white lines
> Docs: Update encoder guide layout

- test/CMakeLists.txt
Closes #295 
Does not solve
```
../../../test/BitstreamReaderMock.cc: In function ‘void od_ec_dec_refill(od_ec_dec*)’:
../../../test/BitstreamReaderMock.cc:87:9: error: ‘OD_EC_WINDOW_SIZE’ was not declared in this scope
s = OD_EC_WINDOW_SIZE - 9 - (cnt + 15);
^~~~~~~~~~~~~~~~~
../../../test/BitstreamReaderMock.cc: In function ‘void od_ec_dec_init(od_ec_dec*, const unsigned char*, uint32_t)’:
../../../test/BitstreamReaderMock.cc:146:28: error: ‘OD_EC_WINDOW_SIZE’ was not declared in this scope
dec->tell_offs = 10 - (OD_EC_WINDOW_SIZE - 8);
^~~~~~~~~~~~~~~~~
../../../test/BitstreamReaderMock.cc: In function ‘int od_ec_decode_bool_q15(od_ec_dec*, unsigned int)’:
../../../test/BitstreamReaderMock.cc:173:30: error: ‘OD_EC_WINDOW_SIZE’ was not declared in this scope
vw = (od_ec_window)v << …
```
> test CMake: Use TARGET_OBJECTS for link libraries

- Source/App/DecApp/EbDecAppMain.c
Fixes:
```
/SVT-AV1/Source/App/DecApp/EbDecAppMain.c:183:52: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
fprintf(stderr, "Skipping first %llu frames.\n", config_ptr->skip_frames);
~~~^             ~~~~~~~~~~~~~~~~~~~~~~~
%lu
[100%] Linking C executable ../../../../../../Bin/Release/SvtAv1DecApp
```
> DecApp: fix format string warning

- CHANGELOG.md
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbInitialRateControlProcess.c
- Source/Lib/Common/Codec/EbMotionEstimation.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbRateControlProcess.c
Change the QP based on the content. Adaptive QP scaling was previously active in I slices only.
Updated the algorithm to use a new metric for all frames. The metric is defined as normalized ME distortion (16x16 based from list 0) over frames in the look ahead.
If number of frames in the LAD/SW is less than 8, the adaptive QP scaling algorithm is turned off.
Associated with Issue #294
Closes #294
@anaghdin
Feature improvement
Expected Average PSNR-SSIM BD-rate gain in the range of -2.4% on the AOM test set, using 4 QP values: {20, 32, 43 and 55}. Note that the maximum gain is achieved when ALT_REF is enabled
The algorithm can be further improved using other information from LAD or ALR_REF filtering
> Adaptive QP scaling

- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
A bug was found after merging the Alt-ref pictures support and disabling the encoding of the overlay pictures seems to be fixing it. So, this should be disabled by default until the problem is fixed. 
The issue will be debugged and a bug fix PR will be submitted.
> Disable overlay pictures (used by the Alt-refs) by default

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbMotionEstimation.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Improved Non Square Block search for M0 by disabling NSQ reordering table and allowing more candidates to be tested
**Improvements**
Results on 360p clips:
- 0.3%/0.3% PSNR/SSIM bdarate gain.
- 12% speed drop.
- No memory impact.
**Todo**
Optimize to reduce the speed cost
> Improved_NSQ_M0

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Fix a few bugs relate to Chroma search (cost calculation, comparison between independent mode and DC)
Fix a bug where 64x64 are disabled for sub 720P resolution
Enable chroma search for all layers in MR mode
**Authors**
@anaghdin
Feature improvement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.9% on the AOM test set, using 4 QP values: {20, 32, 43 and 55}. 
> Bug fixes related to Chroma and 64x64 block size

- Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h
- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_AVX2/pickrst_avx2.c
- Source/Lib/Common/ASM_AVX2/pickrst_avx2.h
- Source/Lib/Common/ASM_AVX2/transpose_avx2.h
- Source/Lib/Common/Codec/EbRestorationPick.c
- test/CMakeLists.txt
- test/EbUnitTest.h
- test/EbUnitTestUtility.c
- test/EbUnitTestUtility.h
- test/RestorationPickTest.cc
Redo weiner filter avx2 optimizations, and add unit test code.
Speedup against original c and avx2 functions (low bitdepth):
TAP 3:  66x 17x
TAP 5: 125x 21x
TAP 7: 188x 20x
Speedup against original c and avx2 functions (high bitdepth):
8-bit
TAP 3:  57x N/A
TAP 5: 113x 59x
TAP 7: 167x 65x
10-bit or 12-bit
TAP 3:  41x N/A
TAP 5:  80x 42x
TAP 7: 128x 50x
Associated with Issue #262
> [SIMD] Wiener Filter AVX2

- Source/Lib/Decoder/Codec/EbDecParseBlock.c
ENUM argument exceeding the range was causing the problem in Mac/Linux
> Decoder Bug fix in Mac/Linux platform

- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Common/Codec/EbSequenceControlSet.h
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Common/Codec/EbTemporalFiltering.h
- Source/Lib/Encoder/Codec/EbEncHandle.c
Fixes a bug in the adjustment of the temporal filtering strength and introduces a better handling of the corner cases where not enough pictures are available for the temporal filtering. Finally, it also contains some small clean-ups of unused code (lossless) and small fixes. 
Bug fix and clean-up
PSNR-YUV BD-rate gains of approximately **-0.3%** on the AOM test set.
[4 QP values: {20, 32, 43 and 55}]
> [Bug fix] filtering strength adjustment for Alt-ref tool

- CHANGELOG.md
- Config/Sample.cfg
- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1.h
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbPacketizationProcess.c
- Source/Lib/Common/Codec/EbRestProcess.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
* The stat report functionality allows the encoder to output per picture statistics [byte count / PSNR Y U V / QP ] to a file of the user's choosing. if the file is not specified, a summary of the average statistics are shown at the end of the encode. 
* This change added API field in the output structure to send out the sse values.
Closes #97 
New feature / Tool / API change
> Statistics report functionality 

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbMotionEstimation.c
Turn on NSQ_ME_OPT by default: SIMD optimization for ExtSadCalculation
Address bug fix mismatch when NSQ_ME_OPT is off
#262 
Currently measure ~5% speed gain where non square partitions are selected. When a very large motion search is used, these gains could go as high as 3x the  encoder as it smooths the work flow of the multi-threaded motion estimation.
> Turn on NSQ_ME_OPT by default

- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbCabacContextModel.c
- Source/Lib/Common/Codec/EbCabacContextModel.h
- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbCodingUnit.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbEntropyCoding.c
- Source/Lib/Common/Codec/EbEntropyCodingProcess.c
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbPictureControlSet.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbRateControlProcess.c
- Source/Lib/Common/Codec/EbRateControlProcess.h
- Source/Lib/Common/Codec/EbSegmentation.c
- Source/Lib/Common/Codec/EbSegmentation.h
- Source/Lib/Common/Codec/EbSegmentationParams.h
- Source/Lib/Common/Codec/EbTransforms.h
- Source/Lib/Decoder/Codec/EbDecStruct.h
- Source/Lib/Decoder/Codec/EbObuParse.h
- Source/Lib/Encoder/Codec/CMakeLists.txt
- Source/Lib/Encoder/Codec/EbEncHandle.c
Initial set of commits to enable segmentation. Uses a very basic variance-based adaptive quantization to test the path. While not thoroughly tested, the feature is relatively stable. PR created so that future changes can easily be added and we do not keep running into merge conflicts.
Rec-dec match tested for RC off. There may still be errors though, so not expected for wide use yet.
> Adding support for segmentation

- test/api_test/CMakeLists.txt
- test/e2e_test/CMakeLists.txt
- test/intrapred_cfl_test.cc
- test/intrapred_dr_test.cc
- test/intrapred_edge_filter_test.cc
- test/intrapred_test.cc
1. add unit test for all the intra prediction modes except palatte
and intrabc.
2. add unit test for upsampling and edge filter process.
3. cfl_predict_lbd_avx2 and cfl_predict_hbd_avx2 will produce
mismatch result compared with c version.
> Add intra pred unit test

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbMotionEstimation.c
- Source/Lib/Common/Codec/EbMotionEstimation.h
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Common/Codec/EbPictureBufferDesc.h
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbPictureDecisionProcess.h
- Source/Lib/Common/Codec/EbReferenceObject.c
- Source/Lib/Common/Codec/EbReferenceObject.h
- Source/Lib/Common/Codec/EbSequenceControlSet.c
- Source/Lib/Common/Codec/EbSequenceControlSet.h
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
* Added down-sampling filtering support.
* Used the down-sampled filtered 1/16th and 1/4th input/reference frame(s) @ both ME and alt-ref temporal filtering .
* Added a multi-mode signal to control the down-sampling method; use the filtered if M0, and use the decimated if M1 or  higher.
* Removed HME Level 0 check @ 1/16 th decimation to guarantee valid ZZ SAD and SCD data when HME Level 0 is OFF (lossless bug fix).
@ikatsavounidisFB 
@hguermaz 
New feature/tool and bug fix.
* Bd-Rate gain(s):
Full sub-4K aom list: ~0.4% to aom_2pass_cpu0 on the.
Per resolution: ~0.7%, ~0.4% and ~0.2% to aom_2pass_cpu0 on 360p, 720p and 1080p respectively.
* Speed & memory footprint:
~0% speed deviation and ~0.3% memory increase in M0.
No memory or speed overhead in M1 & higher.
> Downsampling filtering

- Source/Lib/Common/Codec/EbDefinitions.h
musl already defines fseeko64 as fseek and ftello64 as ftello
> EbDefinitions: Don't redefine fseeko64 and ftello64

- Source/Lib/Common/Codec/EbDefinitions.h
This PR will remove duplicate code in EB_MALLOC, original code is error-prone and hard to maintain.
The refact also addressed two issues:
1. resource leak when malloc(sizeof(EbMemoryMapEntry)) return NULL
https://github.com/OpenVisualCloud/SVT-AV1/blob/6a27563a29503376fd27e5049dd5460f3c431ff2/Source/Lib/Common/Codec/EbDefinitions.h#L2502-L2509
2. if the caller did not catch error returned by 
https://github.com/OpenVisualCloud/SVT-AV1/blob/6a27563a29503376fd27e5049dd5460f3c431ff2/Source/Lib/Common/Codec/EbDefinitions.h#L2598-L2599
calls EB_MALLOC again. This line
https://github.com/OpenVisualCloud/SVT-AV1/blob/6a27563a29503376fd27e5049dd5460f3c431ff2/Source/Lib/Common/Codec/EbDefinitions.h#L2589
will corrupt the memory
> EB_MALLOC: remove duplicate code and do more check

- Source/Lib/Common/ASM_SSSE3/EbMcp_Intrinsic_SSSE3.c
- Source/Lib/Common/Codec/EbInterPrediction.c
Target specific option mismatch compiler error exposed with gcc 9.1.0.
> Fix gcc compiler errors

- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Common/Codec/EbPictureAnalysisProcess.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbSegmentation.c
Before this pull request, these warnings were present, all of which are fixed now:
```
/Users/me/Downloads/SVT-AV1-master 3/Source/Lib/Common/Codec/EbPictureDecisionProcess.c: In function 'perform_simple_picture_analysis_for_overlay':
/Users/me/Downloads/SVT-AV1-master 3/Source/Lib/Common/Codec/EbPictureDecisionProcess.c:3144:9: warning: implicit declaration of function 'DownsampleFilteringInputPicture'; did you mean 'DownsampleDecimationInputPicture'? [-Wimplicit-function-declaration]
3144 |         DownsampleFilteringInputPicture(
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|         DownsampleDecimationInputPicture
In file included from /Users/me/Downloads/SVT-AV1-master 3/Source/Lib/Common/Codec/EbBitstreamUnit.h:10,
from /Users/me/Downloads/SVT-AV1-master …
```
> Fix implicit declaration, avoid compile-time overflow, use correct time functions

- Source/Lib/Common/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
- Source/Lib/Common/Codec/EbTransforms.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- test/InvTxfm2dAsmTest.cc
- test/TxfmCommon.h
Speed up vs C:
HandleTransform16x64: 2.03x
HandleTransform32x64: 2.16x
HandleTransform64x16: 2.68x
HandleTransform64x32: 2.71x
HandleTransform64x64: 3.03x
Related to issue #262
> [SIMD] Add HandleTransform AVX2

- Source/Lib/Common/ASM_AVX2/pickrst_avx2.c
Fix segfaults in Wiener Filter AVX2
Issue #346 on MAC is caused by large stack usage. Moved the buffer to heap.
Related to PR #333
> Weiner filter avx2 bug fix

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbMotionEstimation.c
Merged as part of commit 30eeb871494fbefa1758a4b2be5955616ce52e9a branched out before making the style check passing mandatory
> Cleanup trailing spaces

- Build/linux/build.sh
- CMakeLists.txt
- Source/App/DecApp/CMakeLists.txt
- Source/App/EncApp/CMakeLists.txt
- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Decoder/Codec/CMakeLists.txt
- Source/Lib/Encoder/Codec/CMakeLists.txt
- appveyor.yml
- test/api_test/CMakeLists.txt
- test/e2e_test/CMakeLists.txt
1. Rename SvtAv1Enc output to "SvtAv1EncShared" to avoid
name conflict with static library build.
2. Fix build break due to missing "EbFinishTime"
and "EbComputeOverallElapsedTime".
3. Add -DBUILD_TESTING=ON in appveyor.yml to build unittest.
> Fix build errors in MSVC (Windows)

- Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbDeblockingFilter.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEntropyCoding.c
- Source/Lib/Common/Codec/EbEntropyCoding.h
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbInterPrediction.c
- Source/Lib/Common/Codec/EbPictureControlSet.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureManagerProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbSequenceControlSet.c
- Source/Lib/Common/Codec/EbSequenceControlSet.h
- Source/Lib/Encoder/Codec/EbEncHandle.c
Description
Handle the incomplete SBs properly based on the standard and consider all allowed blocks
Authors
@anaghdin
Type of change
Feature improvement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.9% on the AOM test set, using 4 QP values: {20, 32, 43 and 55}.
TODOs:
If the cropped width is not 4, 8, 16, 32, 64 and 128, the block is not allowed. To be removed after intrinsic functions for NxM spatial_full_distortion_kernel_func_ptr_array are added
Only active for M0, to be evaluated for other modes
> Incomplete SBs fix (rebased)

- .travis.yml
Adds a binary identicality test to Travis. The test compares two encodes (enc-mode 0 and 8) encoded from the PR to encodes from the master branch to check if they are bit-identical. It can be used as a check for PRs where no change in bitstream is expected.
**Examples:**
- [A run that passed](https://travis-ci.com/EwoutH/SVT-AV1/jobs/207970232)
- [A run that failed](https://travis-ci.com/EwoutH/SVT-AV1/jobs/207970997)
The whole test is allowed to fail, because of course sometimes we actually want to change the bitstream.
> CI: Add binary identicality test to Travis

- .travis.yml
The Binary test weren't actually running because the master branch was not actually being rebuilt
Moved the workspace dir to $HOME so that way, there doesn't have to be a lot of moving around
> travis: Fix Binary Identical test

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbInitialRateControlProcess.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbRateControlProcess.c
- Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Common/Codec/EbTemporalFiltering.c
Description
Tune the QPS algorithm to consider ALR_REF filtering and movement of the pictures.
Update to a more accurate QPS complexity metric.
Authors
@anaghdin
Type of change
Feature improvement
Expected Average PSNR-SSIM BD-rate gain in the range of -1.3% on the AOM test set, using 4 QP values: {20, 32, 43 and 55}.
Closes #294
> QP Scaling Tuning

- Source/Lib/Common/Codec/EbCodingLoop.c
Fix the atb check in the encode pass to separate the 10-bit and 8bit paths rather than atb_mode paths
Closes #400 
Ref #424
> Fix chroma artifacts in high density presets

- Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_SSE2/EbIntraPrediction_AV1_Intrinsic_SSE2.c
- Source/Lib/Common/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c
Use unaligned buffers commands in intra prediction as intra buffers are not guaranteed to be aligned
Addresses crash
Closes #84
> Use unaligned load commands in the intrinsics intra prediction kernels

- test/BitstreamWriterTest.cc
- test/CMakeLists.txt
- test/EbUnitTestUtility.c
- test/FwdTxfm1dTest.cc
- test/FwdTxfm2dAsmTest.cc
- test/FwdTxfm2dTest.cc
- test/InvTxfm1dTest.cc
- test/InvTxfm2dAsmTest.cc
- test/QuantAsmTest.cc
- test/convolve_2d_test.cc
- test/e2e_test/CMakeLists.txt
- test/e2e_test/E2eTestVectors.h
- test/e2e_test/FrameQueue.cc
- test/e2e_test/ParseUtil.cc
- test/e2e_test/RefDecoder.cc
- test/e2e_test/SvtAv1E2EFramework.cc
- test/e2e_test/SvtAv1E2EParamsTest.cc
- test/e2e_test/VideoSource.cc
- test/intrapred_cfl_test.cc
- test/intrapred_dr_test.cc
- test/intrapred_edge_filter_test.cc
- test/intrapred_test.cc
- test/warp_filter_test_util.cc
1. remove all the build warnings in test code on windows, mac and linux.
> Remove build warning in unit test

- .travis.yml
Defaults build_type to release and generator to Unix Makefiles
Sets OS and compiler for BinIden job to always use the same compiler and os
Forgot to export CFLAGS
Original PR was #428, can't push to Werror anymore even when deleting it everywhere
> travis: Fix Werror, set os and compiler for BinIden

- Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.c
- Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c
- Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.h
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Common/Codec/EbTemporalFiltering.h
Improved Temporal Filtering for the BASE AltRef.
* Added 1/8 sub-pel search/compensation.
* Added the ability to use dynamic/asymmetric window, added the ability to derive the activity within past and future frames @ picture decision, and added a logic to derive window size from activity.
Closes #447.
@hguermaz 
New feature/tool.
* BD-Rate to aom cpu0-2pass: ~0.4% gain.
* Speed:  less than 1% speed increase. 
* Memory footprint: negligible deviation.
> Improve Temporal Filtering

- .travis.yml
- CMakeLists.txt
@lzhangnj, not for master branch
installing the clang and llvm from ubuntu's repo messed up with the clang provided with travis' images
Add CMake code to detect if `_mm512_extracti64x4_epi64` is defined in `immintrin.h` and add the define to not do avx512 stuff. There is a different function for checking functions, types, etc in c files.
For #451
> AVX512: Don't use apt clang and only compile avx512 code if function is defined

- Source/Lib/Common/Codec/EbDefinitions.h
Windows: sizeof(InterpFilters) is 4, Linux: sizeof(InterpFilters) is 1
Kernel: av1_make_interp_filters() Output value was be casted on uint8.
> Fix different outputs between Windows and Linux

- Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
1. add c implementation
2. enable sparse loop for all the block size, currently
the sparse loop is enabled only when width is 16 and height
is less than or equal to 16.
> Fix assembly implementation of sad_loop_kernel_sparse

- Source/Lib/Common/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
1. In sad_loop_kernel_sse4_1_hme_l0_intrin, The sum of 32x16 sad may saturate
in 16-bit register, although it has subtracted the minimal sum first.
> Fix saturate issue in hme sad

- Source/Lib/Encoder/Codec/EbEncHandle.c
The enforcement of the -lp option for logical processor count was #ifdef'd to Windows and Linux only, causing the option to be ignored on macOS builds.
Fixes https://github.com/OpenVisualCloud/SVT-AV1/issues/483
> Fix for logical processors being ignored on macOS

- test/intrapred_test.cc
1. Intrapred test crashes in AVX2 asm code since data and
stride are not aligned in 32 bytes, fix it by aligning the data
and stride.
> Bug fixing for intrapred unit test

- Build/linux/build.sh
Removes verbose warning message when -v option is used in the linux/osx build script. 
Example of message:
```
Dependee "SVT-AV1/Build/linux/release/Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/DependInfo.cmake" is newer than depender "SVT-AV1/Build/linux/release/Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/depend.internal".
```
> Remove verbose warning message during build

- Source/Lib/Common/ASM_AVX2/EbModeDecision_AVX2.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
get_gradient_hist 4x4     faster:  2.08
get_gradient_hist 4x8     faster:  2.56
get_gradient_hist 4x16    faster:  2.88
get_gradient_hist 8x4     faster:  2.25
get_gradient_hist 8x8     faster:  2.84
get_gradient_hist 8x16    faster:  2.97
get_gradient_hist 8x32    faster:  3.19
get_gradient_hist 16x4    faster:  2.26
get_gradient_hist 16x8    faster:  3.01
get_gradient_hist 16x16   faster:  2.93
get_gradient_hist 16x32   faster:  3.14
get_gradient_hist 16x64   faster:  3.06
get_gradient_hist 32x8    faster:  2.96
get_gradient_hist 32x16   faster:  3.04
get_gradient_hist 32x32   faster:  3.13
get_gradient_hist 32x64   faster:  3.15
get_gradient_hist 64x16   faster:  3.07
get_gradient_hist 64x32   faster:  3.12
get_gradient_hist 64x64   faster:  2.91
get_gradient_hist 64x128  faster:  3.01 …
> Optimization kernel get_gradient_hist() to AVX2

- Source/Lib/Common/Codec/EbTemporalFiltering.c
Should fix one of the sources of the run-to-run bitstream mismatch found in master. 
However, there is still another small mismatch that happens when -enable-altrefs 0 that requires further debugging. 
Tested on macOS and Linux using 500+ frames from 3 sequences.
> Fix run-to-run related to the temporal filtering - chroma padding

- appveyor.yml
www.tortall.net is down.We'd better use github to download the yasm file.
I updloaded the yasm 1.3 file here:
https://github.com/OpenVisualCloud/SVT-AV1/pull/463#issuecomment-514077315
Closes #490
> appveyor: download yasm.exe from github instead of tortall.net

- test/SelfGuidedUtilTest.cc
1. The compiling error happened since the function declaration were
changed, and fix it by using updated function.
> Fix compiling error in Unittests

- test/SadTest.cc
1. Change best_sad to 0x7FFFFFFF from UINT_MAX because signed comparison is
used in test function to compare unsigned int.
> Fix test failure in GetEightSadTest

- Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
- Source/Lib/Common/ASM_AVX512/EbHighbdIntraPrediction_AVX512.c
- Source/Lib/Common/ASM_SSE2/EbHighbdIntraPrediction_SSE2.h
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- test/EbHighbdIntraPredictionTests.cc
- test/EbHighbdIntraPredictionTests.h
- test/EbUnitTest.h
This PR has the AVX512 high_bd_dc_predictor,high_bd_dc_top_predictor and high_bd_dc_left_predictor kernels and their unit tests.The performance numbers are given with commit messages.
> Add AVX512 code for high_bd_dc predictor

- test/FwdTxfm2dTest.cc
- test/SelfGuidedUtilTest.cc
- test/random.h
- test/util.h
1. remove redundant min and max definition in util.h
2. fixed wrong assertion in random number generator.
> Minor cleanup in unit test

- Source/Lib/Common/ASM_AVX512/highbd_fwd_txfm_AVX512.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- test/EbUnitTest.h
- test/ForwardtransformTests.cc
This PR has AVX512 high bd forward transform kernels for sizes 16x16,32x32,64x64,64x32,32x64,64x16,16x64,32x16,16x32 and their unit tests.The performance numbers are given in the commit messages,
> Add AVX512 code for high bd forward transform

- Source/Lib/Common/Codec/EbFullLoop.c
Temporal fix until 10-bit implementation for RDOQ is addressed.
> Disable RDOQ for 10-bit

- Source/Lib/Common/Codec/EbInitialRateControlProcess.c
- Source/Lib/Common/Codec/EbRateControlProcess.c
Closes #481 by preventing attempted access to negative queue indices. By adding, HIGH_LEVEL_RATE_CONTROL_HISTOGRAM_QUEUE_MAX_DEPTH to all negative index values, the queue indices are circularly represented as originally intended.
> Protect rate control queues from negative array indexing

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Perform an ME search around the best MVP for each reference frame @ MD: predictive_me_search(), then build fast loop candidates using the refined MVs: inject_predictive_me_candidates(). 
predictive_me_search() performs the following steps:
- check the distortion of each MVP (1 nearest and up to 3 near).
- perform full-pel search around the best MVP.
- perform half-pel search around the best full-pel position.
- perform quarter-pel search around the best half-pel position.
predictive_me_level signal is used to specify the accuracy of the search:
- Level 0: OFF.
- Level 1: 7x5 full-pel search + sub-pel refinement off.
- Level 2: 7x5 full-pel search +  (H + V) sub-pel refinement only = 4 half-pel + 4 quarter-pel = 8 positions + pred_me_distortion to pa_me_distortion deviation on.
- Level 3: …
> Added the ability to perform ME search around MVP

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbMotionEstimation.c
- Source/Lib/Common/Codec/EbMotionEstimation.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Restructure the Sub_pel refinement to be done in an NxM window around the best integer-pel and where NxM is set to 3x3 by default.
The recorded data on the 360p clips is 11% speedup in encoding time for 0.1% bdrate gain and no impact on the memory.
Please note that this PR replaces the #464 one.
> Me sub_pel refinement optimization

- Source/Lib/Common/Codec/EbPictureControlSet.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
1. update the cdf mode in signal_derivation_pre_analysis_oq;
2. always allocate ec_ctx_array and rate_est_array since cdf_mode might change.
3. initial the avail_blk_flag in init_sq_non4_block.
> Fix crash issue when speed control flag is enabled

- .travis.yml
- test/CMakeLists.txt
- test/TransposeTest.cc
1. change build type to release from debug in unittest, as
there is "unrecognizable insn" error when EbHighbdIntraPrediction_AVX512.c
is compiled in debug mode on linux platform.
2. add avx2 flags in test building as TransposeTest.cc includes avx2
functions, also remove the build warning in this file.
> Fix build issues in unittest

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbMalloc.h
- Source/Lib/Common/Codec/EbThreads.h
else it will crash ffmpeg when we create resource failed
this patch also do null check for EB_DESTORY_xxxx
This need to work with  https://github.com/OpenVisualCloud/SVT-AV1/pull/504
> EbMalloc: return EB_ErrorInsufficientResources for thread/semaphore/mutex create fail

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
This PR is to fix and improve FFmpeg plugin.
face854 is the top priority patch in the PR: we are setting a wrong value of vbr thus means vbr mode is totally broken now and we can only work on cqp mode, setting any bitrate is meaningless right now. 
31cdd39 is an small but important fix,  look like current look_ahead_depth is copied from ffmpeg svt-hevc plugin
df9574e can help user to know encoding quality  immediately with little calculation (since just expose qp, not PSNR), and also help developer to know some encoding parameters working correctly or not (such as max/min qp). 
85ef5a7 can provide more detail error message to know what happening in svt library. 
84bbb8c  is to follow an common way in FFmpeg project to support different pixel format, thus should be benefit to make this …
> Ffmpeg plugin fixes and improvements

- Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecision.h
- Source/Lib/Common/Codec/EbModeDecisionProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbMotionEstimation.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- Source/Lib/Decoder/Codec/EbDecParseBlock.c
Added the following lossy speed optimizations:
- Opt 0: Use the top 4 ME candidates only @ 3x3 Unipred and 3x3 Bipred.
- Opt 1: Skip ATB if parent block does not have coeff.
- Opt 2: Use edge detection to bypass some angular modes.
- Opt 3: Bipred candidates reduction @ ME.
- Opt 4: MD candidates reduction @ MD.
Closes #593  
@NaderMahdi 
@chkngit  
@hguermaz 
* BD-Rate to aom cpu0-2pass on the full list: Opt 0: 0.020% loss, Opt 1: 0.023%, Opt 2: 0.029%, Opt 3: M1 & higher tool , Opt 4: M1 & higher too.l 
* Speed on a 4-core machine:  Opt 0: 30% faster, Opt 1: 0.9% faster, Opt 2: 1.5% faster, Opt 3: M1 & higher tool , Opt 4: M1 & higher too.l 
* Memory footprint on a 4-core machine: negligible
> Speed optimization

- test/SpatialFullDistortionTest.cc
1. add unit tests for spatial_full_distortion_kernel{4, 8, 16, 32, 64,
128}x_n_{sse2,avx2}_intrin
2. add unit tests for spatial_full_distortion_kernel_{avx2,avx512}
> Add unit tests for spatial full distortion functions

- Source/Lib/Common/ASM_AVX2/EbPackUnPack_AVX2.h
- test/PackUnPackTest.cc
1. add tests for functions including:
a. c_pack_avx2_intrin
b. compressed_packmsb_avx2_intrin
c. eb_enc_msb_pack2d_avx2_intrin_al
d. eb_enc_msb_pack2d_sse2_intrin
e. eb_enc_un_pack8_bit_data_avx2_intrin
f. eb_enc_msb_un_pack2d_sse2_intrin
g. unpack_avg_avx2/sse2_intrin.
h. unpack_avg_safe_sub_avx2_intrin
2. modify EbPackUnPack_AVX2.h for extern C
> Add unit tests for pack/unpack functions

- Source/App/DecApp/EbDecParamParser.h
- Source/App/DecApp/EbFileUtils.h
- Source/App/DecApp/EbMD5Utility.h
- Source/App/EncApp/EbAppMain.c
- Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Common/Codec/EbComputeSAD.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbInterPrediction.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPredictionStructure.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbSegmentation.c
- Source/Lib/Common/Codec/EbThreads.h
- Source/Lib/Decoder/Codec/EbDecIntraPrediction.h
- Source/Lib/Decoder/Codec/EbDecParseBlock.c
- Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
- Source/Lib/Decoder/Codec/EbDecParseObu.c
- Source/Lib/Decoder/Codec/EbDecPicMgr.c
- test/BitstreamWriterTest.cc
- test/SadTest.cc
- test/e2e_test/RefDecoder.cc
- test/e2e_test/SvtAv1E2EParamsTest.cc
- test/e2e_test/VideoFrame.h
This pull requests resolves **all** warnings issued during compilation by -Wall/-Wextra of the source code and the tests.
---
#497 is needed to enable unittests, as GCC 5.5 poorly supports AVX512. That pull request shows build failure, because there are too many warnings that made into the source code silently, which is the reason new warnings come regularly. Therefore first merging *this* then #497 would prevent new warnings from coming silently. (Though I'll rebase #497 after this one is merged, so please only merge this for now.)
**TL;DR** without this pull request, unit tests won't run properly on Travis!
---
I believe it'd be easier to review it [commit-by-commit](https://github.com/OpenVisualCloud/SVT-AV1/pull/511/commits). I've documented all changes. Forgive me for the mess below, …
> Refactor & Fix all warnings

- Source/Lib/Encoder/Codec/EbEncHandle.c
closes #517 
There was a socket_id > 15 clause that would cause it to throw an error on any machine with 16 or more sockets as soon as it was about to start the encoding process. While this would never occur with physical hardware it is possible to occur with virtual machines. Virtual machines can configure their systems to do 1 socket per core or really anything.  Here is the output of my validation. 
```
luis@clearlinux~/Desktop/SVT-AV1/Bin/Release $ sudo ./SvtAv1EncApp -i ../../output.y4m -enc-mode 8 -b ../../multisocket.mkv
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:	SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :	GCC 9.2.1 20190821 gcc-9-branch@274807	 64 bit
LIB Build date: Aug 22 2019 19:21:54
-------------------------------------------
Number of logical …
```
> Remove limitation of less than 16 Sockets

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbPredictionStructure.c
Change the MRP prediction references:
In 4 Layer prediction structure: Pictures 3, 5 , 7 and 9 use 1 as the reference
In 5 Layer prediction structure: Pictures 3, 5 , 7 and 9 use 1 as the reference, 11, 13, 15 and 17 use 9 as the reference
@anaghdin
Feature enhancement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.3% on the AOM test set, using 4 QP values: {20, 32, 43 and 55}.
Speed drop of ~5% for M0
> Change the MRP prediction references for non-reference frames

- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
- test/PackUnPackTest.cc
1. load two line data with repect of in_stride
2. reduce the stride depend on the implementation of
compressed_packmsb_avx2_intrin
> Fix mismatch issue in packmsb test

- test/PackUnPackTest.cc
1. limit the data range in avg and sub_avg test, only 10-bit are
populated in a short.
2. do not test area_width of 4 since 4 is not supported in
unpack_avg_safe_sub_avx2_intrin
> Fix mismatch issue in PackUnpack unit test

- test/PictureAdditionTest.cc
1. Limit the data range to maximum of signed 13 bits;
> Fix mismatch issue in picture addition test

- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.c
- Source/Lib/Common/Codec/EbPictureManagerProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
This PR addresses build warnings type C4244 seen when building SVT-AV1 on MSVC Visual Studio 2017
fixes #636
Code Cleanup
- Lossless; no impact on BD-Rate
- negligible speed impact
- no deviation in memory footprint
> Remove some MSVC build warnings

- Source/Lib/Common/ASM_AVX2/transpose_avx2.c
- Source/Lib/Common/ASM_AVX2/transpose_avx2.h
- Source/Lib/Common/ASM_SSE2/transpose_sse2.c
- Source/Lib/Common/ASM_SSE2/transpose_sse2.h
- test/CMakeLists.txt
- test/TransposeTest.cc
Add new test cases for functions:
- transpose_8bit_4x4_reg128bit_instance_sse2
- transpose_8bit_8x8_reg128bit_instance_sse2
- transpose_8bit_16x8_reg128bit_instance_sse2
- transpose_8bit_16x16_reg128bit_instance_sse2
- transpose_8bit_16x16_reg128bit_instance_avx2
- transpose_16bit_4x4_reg128bit_instance_sse2
- transpose_16bit_4x8_reg128bit_instance_sse2
- transpose_16bit_8x4_reg128bit_instance_sse2
- transpose_16bit_8x8_reg128bit_instance_sse2
- transpose_16bit_16x16_reg128bit_instance_sse2
- transpose_32bit_4x4_reg128bit_instance_sse2
- transpose_32bit_4x4x2_reg128bit_instance_sse2
- transpose_32bit_8x4_reg128bit_instance_sse2
- transpose_32bit_8x8_reg256bit_instance_avx2
- transpose_64bit_4x4_reg256bit_instance_avx2
- transpose_64bit_4x6_reg256bit_instance_avx2
- …
> Refine transpose unit test to cover more functions

- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbEntropyCoding.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
Hi,
The following PR removes the restriction for non multiple of 8 sized pictures. Please feel free to test.
After looking at this section of code, I would say that the current buffer allocation model should be reworked at some point. The onus of allocating, padding, aligning the input buffer happens in the app. Not ideal, this should really be something that is handled by the lib.
Thanks,
Kyle
> Support arbitrary picture size (non multiple of 8)

- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppInputy4m.c
- Source/App/EncApp/EbAppProcessCmd.c
This is a fix for reading from a named pipe. Tested for both yuv and y4m inputs. Should address #523.
> cfg->input_file: fix for reading from named pipe

- Source/Lib/Common/Codec/EbProductCodingLoop.c
Update info from commit message:
Kernels works 2.3 faster, with previous changes all works 4.3 faster
//OLD: Kernels work 2.7 faster on msvc and 4.3 faster on linux
> Optimizing kernels construct_best_sorted_arrays_md_stage_2/3

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Added the following lossy speed optimizations:
- Variance-based compound skip, 
- Distortion based md-stage-1 count pruning.
- Lossy inter depth decision exit.
- ATB=f(layer) and enabled coef-based ATB skip.
Closes #643   
@hguermaz 
* BD-Rate to aom cpu0-2pass on 360p/720p: 0.189%.
* Speed on a 4-core machine for M0 on 360p: ~22% faster.
* Memory footprint on a 4-core machine: negligible.
> Speed Optimization(s)

- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
- test/PackUnPackTest.cc
In c_pack_avx2_intrin, the output stride is not consistent when the output data is stored. When the input width is 32, the output stride is fixed to 8; If the input width is 64, the output stride could be out_stride or 16.
It would be good if we can use the out_stride consistently.
> Fix stride issue in c pack avx2 intrin

- Source/Lib/Common/ASM_SSE4_1/EbTemporalFiltering_highbd_sse4.c
- Source/Lib/Common/ASM_SSE4_1/EbTemporalFiltering_sse4.c
- Source/Lib/Common/C_DEFAULT/EbComputeVariance_C.c
- Source/Lib/Common/C_DEFAULT/EbComputeVariance_C.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Common/Codec/EbTemporalFiltering.h
- Source/Lib/Common/Codec/EbTemporalFiltering_sse4.h
Changes to the temporal filtering module:
* Addition of 10-bit support
* Addition of 422 and 444 chroma subsampling support
* Code clean-ups
Associated to issue #622
Incremental feature/tool
BD-rate gains for 4 10-bit test sequences  shown below (enc-mode 0). No change for 8-bit sequences.
| Sequence name                    | avg. PSNR-Y | avg. PSNR-U | avg. PSNR-V | overall PSNR-Y | overall PSNR-U | overall PSNR-V | VMAF   |
|----------------------------------|-------------|-------------|-------------|----------------|----------------|----------------|--------|
| Cosmos1_1920x856_BT2100_PQ_24fps | -1.23       | -1.34       | -1.18       | -3.03          | -2.28          | -1.62          | -3.77  |
| Market3_1920x1080p_50_10b_pq_709 | -1.95       | -4.74       | -4.77       | -2.64 …
> Temporal filtering - 10bit support

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEntropyCoding.c
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecision.h
- Source/Lib/Common/Codec/EbModeDecisionProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbRateDistortionCost.c
- Source/Lib/Common/Codec/EbRateDistortionCost.h
- Enabled/fixed transform flag rate estimation. 
- Re-factor ATB path.
- Added ATB for INTER (Depth_1 only).
Closes #642 
@hguermaz 
* BD-Rate to aom cpu0-2pass on the full list: ~0.185% gain.
* Speed on a 4-core machine for M0 on 360p: ~8% slower.
* Memory footprint on a 4-core machine: ~1% increase.
> ATB for INTER 

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbModeDecisionProcess.c
Modified when warp is active: 
MR: ON always
M0: ON for the ref frames
M1-M5: ON for the base layer
else: OFF
@anaghdin
Feature enhancement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.2% on the AOM test set, using 4 QP values: {20, 32, 43 and 55}.
Speed drop of ~3% for M0
> Added WARP_UPDATE flag and modified when warping is active

- Source/Lib/Common/Codec/EbInterPrediction.c
- Source/Lib/Common/Codec/EbIntraPrediction.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
* Use 16-bit buffers
* 10-bit support in the inter_pu_prediction path
Associated to issue #622
Incremental feature/tool
BD-rate gains for 4 10-bit test sequences shown below (enc-mode 0). No change for 8-bit sequences. 
Enabled by encoder flag "-hbd-md 1"
| Sequence name                    | avg. PSNR-Y | avg. PSNR-U | avg. PSNR-V | overall PSNR-Y | overall PSNR-U | overall PSNR-V | VMAF   |
|----------------------------------|-------------|-------------|-------------|----------------|----------------|----------------|--------|
| Cosmos1_1920x856_BT2100_PQ_24fps | -2.699 | -4.927 | 3.698 | -2.385 | -5.012 | 3.838 | -2.86 |
| Market3_1920x1080p_50_10b_pq_709 | -4.694 | -3.86 | -3.949 | -4.518 | -3.822 | -3.915 | -1.899|
| ShowGirl2TeaserClip4000_1920x108 | -7.147 | -9.3 | -9.321 | -6.773 | …
> Add 10-bit path to inter Mode Decision

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
RDOQ for CHROMA
Closes #673
@hguermaz 
* BD-Rate to aom cpu0-2pass on the full list: ~0.6% Y gain and ~3.4% UV loss => YUV: ~0.075% loss (better distribution as currently UV to libaom is >> Y to libaom)
* Speed on a 4-core machine for M0 on 360p: ~1% slower
* Memory footprint on a 4-core machine: ~0%
> RDOQ for CHROMA

- test/InversetransformTests.cc
This pull request fixes the outdated code existing in the AVX512 inverse transforms unit test.
> Fix the outdated code in the unit tests of AVX512 inverse transforms

- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
Enabling 10-bit MD by default to get the ~6% BD-rate gains.
> Set hbd-md true by default

- .travis.yml
- Adds dedicated GCC 8 and GCC 9 builds
- Removes redundant environment variables
- Adds some layout improvements and documentation
- Updates macOS build environment to Xcode 11.2
Blocked by #647: Fix GCC 8 compile warning
@1480c1 @kylophone Please review
> Travis: Add GCC 8 and GCC 9 builds, cleanup

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbPredictionStructure.c
Reordered the references for MRP (Multi Reference Picture):
Odd pictures are moved from spots 0 or 1 to spots 2 or 3. No impact for M0. Setting is helpful for faster MRP modes when all the spots are not used
@anaghdin
Feature enhancement
The changes are not 100% lossless. They impact the MRP signalling, however BDRate impact is 0%
No impact
> Reordered References for MRP (Multi Reference Picture)

- test/CompoundUtilTest.cc
- test/WedgeUtilTest.cc
- test/loopfilter_ref.h
1. add unit test for utility functions in wedge prediction, including:
av1_wedge_sign_from_residuals_avx2,
av1_wedge_compute_delta_squares_avx2,
av1_wedge_sse_from_residuals_avx2
2. add unit tests for utility functions:
av1_build_compound_diffwtd_mask_{, d16}avx2,
aom_blend_a64_mask_avx2/aom_lowbd_blend_a64_d16_mask_avx2
> Add unit tests for utility functions in compound prediction

- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbEncodeContext.c
- Source/Lib/Common/Codec/EbEncodeContext.h
- Source/Lib/Common/Codec/EbEntropyCodingProcess.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbRateControlProcess.c
- Source/Lib/Common/Codec/EbRateDistortionCost.c
- Source/Lib/Common/Codec/EbReferenceObject.c
- Source/Lib/Common/Codec/EbReferenceObject.h
- Source/Lib/Common/Codec/EbSequenceControlSet.c
- Source/Lib/Common/Codec/EbSequenceControlSet.h
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Two pass encoding. For now, the encoder is called two times and data transferred using file.
First pass collect the referenced area per SB and the second pass uses it to: 
- Frame QP assignment 
- SB QP assignment 
- Temporal filtering strength adjustment
A config parameter (-enc-mode-2p) is passed to the first pass to use the ME settings of the second pass (to achieve better bdRate)
SvtAv1EncApp.exe -enc-mode 5  -w 1920  -h 1080  -i -q 20  -fps-num 60000 -fps-denom 1001 -b out.bin   -n 60  -intra-period 119  **-output-stat-file out.stat**   -bit-depth 8 
SvtAv1EncApp.exe -enc-mode 0  -w 1920  -h 1080  -i aspen_1080p_60f.yuv  -q 20  -fps-num 60000 -fps-denom 1001 -b out-m0.bin   -n 60  -intra-period 119   **-input-stat-file in.stat**   -bit-depth 8
@anaghdin
New Feature
Expected Average …
> Two Pass Encoding

- Source/Lib/Common/Codec/EbPictureBufferDesc.c
- Source/Lib/Common/Codec/EbPictureBufferDesc.h
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Decoder/Codec/EbDecMemInit.c
Fix #695 
add origin_bot_y in picture buffer descriptor to hold the bottom padding value (different than the top padding when SB size is 128)
> Fix assertion fail 

- Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbFullLoop.h
- Source/Lib/Common/Codec/EbIntraPrediction.c
- Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
- Source/Lib/Common/Codec/EbModeDecisionConfiguration.h
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.h
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbMotionEstimation.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbPictureOperators.c
- Source/Lib/Common/Codec/EbPictureOperators.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbRateDistortionCost.c
- Source/Lib/Common/Codec/EbRateDistortionCost.h
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
This is a first pass of partitioning decision which ranks all possible partitions based on the open loop EME data. A reduced set of partitions is forwarded to the closed loop partitioning decision pass.
Closes #721  
@NaderMahdi 
New feature
- BD rate difference of -0.05% compared to libaom_fd530f8 in M0 with the fullset of clips.
- No BD rate difference for 360p or screen content clips
- A speed gain of 6% was obtained measured over all clips.
- ~1% memory allocation increase
> Add NSQ shape prediction

- Source/Lib/Common/Codec/EbFullLoop.c
do not count nsq merge blocks if nsq is disabled ( No bd-rate impact)
> Fix valgrind error

- Source/Lib/Common/Codec/EbEncDecProcess.c
More aggressive MD Exit TH for M0 non-SC.
@hguermaz 
Tuning
* BD-Rate to aom cpu0-2pass on the full list: ~0.006% BD-Rate loss.
* Speed on AWS on Full-list: ~2.36% faster.
* Memory footprint on a 4-core machine: ~0%.
> More aggressive MD Exit TH for M0 non-SC

- CMakeLists.txt
Closes m-ab-s/media-autobuild_suite#1441
mingw's stack-protector seems to suck
> CMake: Apply fortify source if stack protector is also on

- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbInterPrediction.c
- Source/Lib/Common/Codec/EbInterPrediction.h
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Decoder/Codec/EbDecParseObu.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
1. Fix when hbd-md 1:
- run to run in release
- crash in debug  
2. created a function table :  av1_inter_prediction_function_table for 8 and 10 bit
3. Code clean up 
Fixes #728 
@okhlif 
Bug fix
BDR : ~0.9% gain on 360p objective-fast1 clips ( changed to 10bit)
> Fix run-to-run in hbd-md 1

- Source/Lib/Common/C_DEFAULT/variance.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- test/VarianceTest.cc
Fix MseTest to test eb_aom_mse16x16_avx2 with eb_aom_mse16x16_c instead of local implementation
> Add missing eb_aom_highbd_8_mse16x16 for C version with tests

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Moved from 4 MD-Stages to only 3 MD-Stages.
The 3 MD-Stages work as follows:
CLASS_0 and CLASS_6: Prediction for Luma & Chroma.
CLASS_2 to CLASS_5: Prediction for Luma Only, No Interpolation Search, Bilinear Interpolation.
CLASS_0 and CLASS_6: T, Q, Q-1, T-1 for Luma Only, No RDOQ, No Tx Type Search, No Tx Size Search.
CLASS_2 to CLASS_5: Interpolation Search, T, Q, Q-1, T-1 for Luma Only, No RDOQ, No Tx Type Search, No Tx Size Search, 
CLASS_0 and CLASS_6: T, Q, Q-1, T-1 for Luma and Chroma, RDOQ, Tx Type Search, Tx Size Search.
CLASS_2 to CLASS_5: T, Q, Q-1, T-1 for Luma and Chroma, RDOQ, Tx Type Search, Tx Size Search.
@hguermaz 
Tuning
enc-mode | BD-rate to aom for the full list | Speed deviation on AWS instances 
------------ | --------------------------------- | …
> Simplify MD Staging

- Source/Lib/Common/ASM_AVX2/EbComputeSAD_AVX2.h
- Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Common/Codec/EbComputeSAD.h
- Source/Lib/Common/Codec/aom_dsp_rtcd.c
- test/SadTest.cc
Master code base generates random encoding results run by run. Verified on old master code base and encoding is bit exact.
Make all sub functions inlined in EbComputeSAD_Intrinsic_AVX2.c for Windows.
Update get_eight_horizontal_search_point_results avx2
get_eight_horizontal_search_point_results_8x8_16x16_pu_avx2_intrin() is 5% (sub_sad case) or 10% faster.
get_eight_horizontal_search_point_results_32x32_64x64_pu_avx2_intrin() is 30% to 100% faster.
AVX512 didn't help for these two functions.
Update compute{4, 8, 16, 24, 32, 48, 64}x_m_sad_avx2_intrin().
Already has AVX512 for width 64. AVX512 didn't help for width 16 and 32.
> [SIMD] Update sad and get_eight_horizontal_search_point_results avx2

- Source/API/EbSvtAv1Dec.h
- Source/App/DecApp/EbDecAppMain.c
- Source/App/DecApp/EbDecParamParser.c
- Source/App/DecApp/EbDecParamParser.h
- Source/App/DecApp/EbFileUtils.c
- Source/App/DecApp/EbFileUtils.h
- Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
- Source/Lib/Common/ASM_AVX2/highbd_jnt_convolve_avx2.c
- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Decoder/Codec/EbDecParseObu.c
- Source/Lib/Decoder/Codec/EbObuParse.h
Added support for Annex-B streams in Decoder.
Changed few of the aligned stores to unaligned stores based on the buffer alignment requirement.
> Annex-B support in Decoder and Intrinsic Fixes

- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
Determine if the evaluation of a and b shapes could be skipped based on cost of square, h and v shapes. Namely:
- skip HA and HB if h_cost > (weighted sq_cost)
- skip VA and VB if v_cost > (weighted sq_cost)
Weighting to sq cost can be controlled with the `-sqw` flag, which is expressed as a percentage and set to `100` (neutral) by default.
- To turn off this feature, set `-sqw 0`
- To use *aggressive* weighting, set `-sqw` to a value lesser than 100
- faster but more BD-Rate loss
- To use *conservative* weighting, set `-sqw` to a value greater than 100
- slower but less BD-Rate loss
@hguermaz 
@JackZhouVCD 
Enhancement
All data generated from full-list objective-1-fast dataset in the context of enc-mode 0. Speed data is generated using AWS ec2 48 vCPU instances
| | Deviation|
|-|-|
| …
> A/B shape skip based on SQ/H/V shape costs

- Source/Lib/Common/ASM_AVX2/EbCombinedAveragingSAD_Inline_AVX2.h
- Source/Lib/Common/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.h
- Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h
- Source/Lib/Common/ASM_AVX2/encodetxb_avx2.c
- Source/Lib/Common/ASM_AVX512/EbCombinedAveragingSAD_AVX512.c
- Source/Lib/Common/ASM_AVX512/encodetxb_avx512.c
- Source/Lib/Common/ASM_SSE2/synonyms.h
- Source/Lib/Common/ASM_SSE4_1/EbMemory_SSE4_1.h
- Source/Lib/Common/Codec/EbComputeSAD.h
- Source/Lib/Common/Codec/aom_dsp_rtcd.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- test/EncodeTxbAsmTest.cc
- test/SadTest.cc
Add combined_averaging_ssd_avx512()
Speed comparing with original avx2:
8x8 :  3.61x
16x16:  7.67x
32x32: 14.34x
64x64: 18.31x
Update eb_av1_txb_init_levels_avx2()
Speed comparison:
4x 4: 2.12x
4x 8: 2.01x
4x16: 1.62x
8x 4: 1.82x
8x 8: 1.53x
8x16: 1.47x
8x32: 1.43x
16x 4: 1.38x
16x 8: 1.49x
16x16: 1.47x
16x32: 1.36x
32x 8: 1.52x
32x16: 1.15x
32x32: 1.24x
Add eb_av1_txb_init_levels_avx512()
About 10% to 30% faster for 16x and 32x.
> [SIMD] Add combined_averaging_ssd_avx512() and eb_av1_txb_init_levels_avx512()

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Description:
Fix a bug related to temporal filtering of non-key Intra frames. Temporal Filtering now enable for all Intra frame
Authors
@anaghdin
Type of change
Bug Fix
Expected Average Y-PSNR BD-rate gain in the range of -3% on the jctvc list with Intra refresh enabled, using 4 QP values: {20, 32, 43 and 55}.
> Fix temporal filtering for non-key Intra frames

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbRateControlProcess.c
- Source/Lib/Common/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
Description:
Tune the two pass encoding for better Luma by adjusting the reference area, the maximum values and the actions
Authors
@anaghdin
Type of change
Feature Improvement
Expected Average Y-PSNR BD-rate gain in the range of -0.2% on the objective fast 1 test set, using 5 QP values: {20, 32, 43, 55 and 63}.
> Two pass tuning

- test/OBMCVarianceTest.cc
1. Add unit test for OBMC variance:
- aom_obmc_variance{4-128}x{4-128}_{c, avx2}
- aom_obmc_sub_pixel_variance{4-128}x{4-128}_{c, sse4_1}
> Add OBMC variance unit test

- Source/Lib/Common/Codec/EbInterPrediction.c
Add interpolation filter search for 10-bit
* Clean-up of some of the related function calls
* Consolidate the SSE computation
Associated to issue #622
Added feature
BD-rate gains for 7 360p 10-bit test sequences is -0.6%  (enc-mode 0); BD-VMAF -1.06%.
Tiny change for 8-bit sequences due to the reuse of existing SSE computation (-0.001%). Encoding time slightly reduced -0.3% (enc-mode 0), though not reliable.
> Interpolation filter search for 10-bit (#769)

- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
1. Add copy of missing variables for redundant Block
2. Check if the parent block is available before testing on parent_sq_has_coeff to inject newmv candidate and intra candidate 
3. Initialize last two elements of nsq_table in order_nsq_table
4. Check that there is at least one candidate for CAND_CLASS_O before testing on its fastcost 
5. Check if the parent block is available before testing non coeff_based_skip_atb
> Fix R2R issues

- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbEncDecProcess.h
- Source/Lib/Common/Codec/EbEntropyCoding.c
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbInterPrediction.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbPictureControlSet.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbPictureOperators.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
Hbd clean up to support three mode for 10bit samples
- EB_8_BIT_MD    = 8bit mode decision
- EB_10_BIT_MD   = 10bit mode decision **(default)**
- EB_DUAL_BIT_MD = Auto: 8bit & 10bit mode decision
Add 8bit IFS path in 10bit MD
@okhlif 
Cleanup
Enhancement
EB_10_BIT_MD  & EB_8_BIT_MD unchanged
Add IFS 8 bit under EB_DUAL_BIT_MD
~ 2.8% speed gain for 10bit 360p
~ BDR over 7 clips 360p-10bit -0.11% (PSNR) -0.04% (SSIM)
~ Memory increase ~1%
> hbd clean up

- Source/Lib/Encoder/Codec/EbEncHandle.c
else it will report memory leak
> eb_deinit_handle: free lp_group, before eb_decrease_component_count

- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbPictureDecisionProcess.h
- Source/Lib/Common/Codec/EbTemporalFiltering.h
This change improves bdrate for 240P clips without introducing a negative impact on clips greater than 240P. 
- Adjusted weighing for luma SAD threshold.
- Instead of taking the absolute difference across multiple divided regions, modified algorithm to effectively take the absolute difference across one region. This will affect how many frames are considered for temporal filtering. Summation of 'ahd' will lower overall.
> lower 'ahd' threshold and restrict 'ahd' summing to one region

- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
This PR adds a mechanism before MD Stage 1 and 2 to prune at the candidate level (intra-class) and class level (inter-class) in terms of cost following a heuristic that is as follows:
Intra-class:
- Prune all candidates that are a threshold percentage away from the best candidate
Inter-class:
- Prune all classes that are a threshold percentage away from the best class (in terms of its best candidate)
The default percentages are as seen in the following table:
| |*inter*-class|*intra*-class|
|-|-|-|
| Before MD stage **1** | 100 | 75 |
| Before MD stage **2** | 25 | 15 |
API signals are included in this PR for the ease of tweaking the thresholds:
| |*inter*-class pruning|*intra*-class pruning|
|-|-|-|
| Before MD stage **1** | `-mds1p-class-th` | `-mds1p-cand-th` |
| Before MD stage **2** …
> Inter-Intra class pruning before MD Stage 1 and 2

- Source/App/EncApp/EbAppConfig.c
test comand: valgrind ../Bin/Debug/SvtAv1EncApp
result:
==115716== Memcheck, a memory error detector
==115716== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==115716== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==115716== Command: ../Bin/Debug/SvtAv1EncApp
==115716==
-------------------------------------------
SVT-AV1 Encoder
==115716== Conditional jump or move depends on uninitialised value(s)
==115716==    at 0x10E17B: read_command_line (EbAppConfig.c:1197)
==115716==    by 0x11247E: main (EbAppMain.c:144)
==115716==
Error instance 1: Invalid Input File
Error in configuration, could not begin encoding! ...
Run ../Bin/Debug/SvtAv1EncApp -help for a list of options
Encoder finished
==115716==
==115716== HEAP SUMMARY:
==115716==     in use at …
> EbAppConfig: fix jump depends on uninitialized value

- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbCodingUnit.h
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
- Source/Lib/Common/Codec/EbModeDecisionConfiguration.h
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
Adaptive open loop partitioning consists of assigning a specific refinement mode for each block instead of using the same refinement mode for all the blocks within the picture. The refinement mode is selected based on the cost difference between the predicted block depth and the above and below depths. Assuming a maximum of 3 above refinement depths (Pred-3) and 3 below refinement depths (Pred+3) can be considered to provide the same quality as all depths, the algorithm can select one of the 16 [0..15] refinement combinations illustrated in the following table.
Combination | Start depth (s_depth) | End depth (e_depth) | Refinement mode
-- | -- | -- | --
0 | -3 | 3 | Pred -3/+3
1 | -2 | 3 | Pred -2/+3
2 | -1 | 3 | Pred -1/+3
3 | 0 | 3 | Pred +3
4 | -3 | 2 | Pred -3/+2
5 | -2 | 2 | Pred …
> Adaptive Open Loop Partitioning

- Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
- Source/Lib/Decoder/Codec/EbDecParseObu.c
Fixed decoder mismatch for 12-bit streams.
The buggy intrinsic module is replaced by C variant for 12 bit streams.
> Fix : decoder 12-bit output mismatch

- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
In M3, sb size may be 128x128 for resolution >= 1080i.
while init_sq_non4_block() is only designed for sb size of 64x64
> Fix the corruption in M3(resolution like 1080P)

- Source/Lib/Common/Codec/EbInterPrediction.c
- Source/Lib/Common/Codec/EbWarpedMotion.c
- Source/Lib/Common/Codec/EbWarpedMotion.h
- Source/Lib/Decoder/Codec/EbDecInterPrediction.c
This removes code and should have no impact on the bit stream for low and high bit depth.
> Remove duplicated implementation of warp_plane for high bit depth

- Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
Fix UT Mismatch issue in SAD loop unit test #771
> Fix mismatch between C and SSE4, AVX2 for sad_loop_kernel_sparse

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
avcodec_receive_packet requires encoder ouptut is reference-counted.
It's documented here https://github.com/FFmpeg/FFmpeg/blob/f01f9f179389befe9bce7639088e453146a39915/libavcodec/avcodec.h#L4990
and enforced by https://github.com/FFmpeg/FFmpeg/commit/73ee53f317418a5719f6169e6171b40f90d18321
We use output buffer pool to fulfill this.
> ffmpeg: fix assert in avcodec_receive_packet

- Source/Lib/Common/ASM_SSE2/EbDeblockingFilter_Intrinsic_SSE2.c
Code SSE2 use in different way array *_blimit1 in relation to C, and SSE2 calculated 2 times more elements that they should.
> Fix issue in unit test: DeblockTest

- Source/Lib/Common/Codec/EbDefinitions.h
NON_KF_INTRA_TF_FIX causing a crash when the intra peirod is not aligned due to the non-availability of altref pictures in the picture decision queue.
Turning off the feature until the issue is addressed.
#710
> Turn OFF NON_KF_INTRA_TF_FIX pending fixing issue 710

- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbGlobalMotionEstimation.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
The first commit fixes the global motion estimation for high bit depth frames by removing a wrong 8 bit conversion.
The second commit enables the global motion compensation for high bit depth streams.
> Fix and enable global motion compensation for high bit depth streams

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbMdRateEstimation.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.c
Improves the high precision MV performance by:
- Shutting it based on the qindex
- Rate estimation fixes
- Candidate injection fixes
**Authors**
@anaghdin
Bug Fix, enhancement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.4% (8 bit) and -0.6%(10bit) over 360P clips in aom list, using 5 QP values: {20, 32, 43, 55 and 63}.
> Improve High-Precision MV

- Source/Lib/Common/Codec/EbPictureControlSet.c
steps to reproduce:
run Bin/Debug/SvtAv1EncApp -i test.y4m -enc-mode 7 -b test.ivf
you will see memory leak at EbPictureBufferDesc.c:L354
> EbPictureControlSet: fix rst_frame leak

- README.md
As requested in #811, the `#svt` channel is [now logged](https://freenode.logbot.info/svt/20191127).
> Readme: Add link to #svt IRC log

- Source/Lib/Common/Codec/EbCdef.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbCdefProcess.c
- Update rate estimation, cost calculation equation, and lambda to match lambda from MD
- Optimization / enhancement
Tested on Objective-fast1 test-set in context of M5M2 where there was a gain of 0.1%. Going to re-run a simulation over M0.
@NaderMahdi @anaghdin
> Update cost calculation for cdef filtering

- Source/Lib/Common/Codec/global_motion.h
This PR just decreases the RANSAC_NUM_MOTIONS macro parameter from 100 to 1.
This parameter corresponds to the number of different motions tested by the RANSAC algorithm that estimates the global motion parameters.
Setting it to 1 leads to a decrease of the compression time while slightly increasing the BD-RATE.
Here are the performance results with the full objective-1-fast dataset:
Metric | deviation
-- | --
Average BD-PSNR | -1.01157208449589E-05
Average BD-RATE | 0.002265293304234
Compression time | -2.13%
> Set RANSAC_NUM_MOTIONS to 1 to speedup global motion estimation

- Source/Lib/Common/Codec/EbCdef.c
- Source/Lib/Encoder/Codec/EbCdefProcess.c
In a previous commit, Travis CI reports that `SequenceControlSet *sequence_control_set_ptr` was an unused variable during the build stage. Warnings were treated as errors and I had it removed. 
In the current master, if we set the flag UPDATE_CDEF to 0, `SequenceControlSet *sequence_control_set_ptr` is referenced again and will result in a build error. Added pre-processor statements to restore the missing parameter.
> Fix build error when UPDATE_CDEF is 0

- Source/Lib/Common/Codec/EbInterPrediction.c
This commit removes build_obmc_inter_pred_above_hbd,
build_obmc_inter_pred_left_hbd and av1_build_obmc_inter_prediction_hbd and
replace them by generic implementations.
This should have no impact on the bit stream.
> Single av1_build_obmc_inter_prediction function for 8 and 10 bit frames

- Source/Lib/Common/ASM_AVX2/corner_match_avx2.c
- Source/Lib/Common/ASM_SSE4_1/highbd_warp_plane_sse4.c
- Source/Lib/Common/Codec/EbWarpedMotion.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- Source/Lib/Common/Codec/corner_match.c
- test/corner_match_test.cc
- test/warp_filter_test.cc
- test/warp_filter_test_util.cc
Imported from AOM
eb_av1_highbd_warp_affine_sse4_1 is ~5.0x faster compared to C implementation
av1_compute_cross_correlation_avx2 is ~3.5x faster compared to C implementation
>  Add intrinsic kernels eb_av1_highbd_warp_affine and av1_compute_cross_correlation

- Config/Sample.cfg
- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
This PR changes the API switch for target bitrate `-tbr` to take in kilobits per second instead of bits per second.
The change is only applied at the api level. The internal library still uses bps.
closes #754
> Change -tbr input values from bps to kbps

- Source/Lib/Common/ASM_SSE2/highbd_variance_impl_sse2.asm
- Source/Lib/Common/ASM_SSE2/highbd_variance_sse2.c
The issue is caused by missing sse variance function for 4x4 block size, so when the block size in test is 16x4, it used 16x16 sse function to compute variance mistakenly.
> Fix issues in HbdVariance unittest

- Source/App/EncApp/EbAppProcessCmd.c
Simple fix to correct log file typo. Frame sizes are in bytes, not bits.
> fixed typo in log file (bits->bytes)

- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Inline_AVX2.h
- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
- test/SpatialFullDistortionTest.cc
Based on PR #830,  I modified function with assumption that  *input and *recon cannot exceed 15bit. 
The speed up is ~6.5x compared to C implementation (instead of current 3.5x )
> Speed up of full_distortion_kernel16_bits_avx2 

- test/EbHighbdIntraPredictionTests.cc
- test/InversetransformTests.cc
- test/MotionEstimationTest.cc
This PR fixes UT for avx512 : 
[  FAILED  ] InverseTransformTest.av1_inv_txfm_2d_square_kernels
[  FAILED  ] InverseTransformTest.av1_inv_txfm_2d_rect_kernels
[  FAILED  ] MotionEstimation_avx512.sadMxN_match
[  FAILED  ] MotionEstimation_avx512.sadMxNx4d_match
HighbdIntraPredictionTest.aom_h_predictor_kernels (which failed only on linux due to unaligned memory)
Combined with: #786, #793, #801 allow to pass all tests from SvtAv1UnitTests
> Fixes for avx512 UT

- Source/Lib/Common/Codec/EbCdef.c
- Source/Lib/Common/Codec/EbCdef.h
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Decoder/Codec/EbDecInverseQuantize.h
This pull request aims to improve code quality related to cdef filtering and to refactor code so it adheres to STYLE.md. Feedback or suggestions are appreciated! 
- remove unused functions `void eb_av1_cdef_search()` and `void av1_cdef_search16bit()`
- remove unused macro _CDEF_BLOCK_H (1)
- remove commented out code
closes #833
> Code cleanup for cdef filtering

- Source/Lib/Common/ASM_AVX512/encodetxb_avx512.c
Protect the AVX512 code in encodetxb_avx512.c by NON_AVX512_SUPPORT to avoid compiling it when AVX512 is disabled
> Protect the AVX512 code in encodetxb_avx512.c

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbGlobalMotionEstimation.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
Perform the global motion estimation on a down-sampled version of the input picture.
Closes #835 
New feature
@NaderMahdi 
- 0.04% BD rate difference to AOM averaged over 360p, 720p, and 1080p clips in M0
- 3.1% speed gain averaged over 360p, 720p, and 1080p clips in M0
> Global Motion Estimation Opt

- Source/Lib/Common/Codec/EbCdef.c
- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbCodingLoop.h
- Source/Lib/Common/Codec/EbCodingUnit.c
- Source/Lib/Common/Codec/EbCodingUnit.h
- Source/Lib/Common/Codec/EbDeblockingFilter.c
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbEntropyCoding.c
- Source/Lib/Common/Codec/EbEntropyCoding.h
- Source/Lib/Common/Codec/EbEntropyCodingProcess.c
- Source/Lib/Common/Codec/EbFullLoop.c
- Source/Lib/Common/Codec/EbFullLoop.h
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecision.h
- Source/Lib/Common/Codec/EbModeDecisionConfiguration.c
- Source/Lib/Common/Codec/EbModeDecisionConfiguration.h
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.h
- Source/Lib/Common/Codec/EbPacketizationProcess.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Common/Codec/EbRateControlProcess.c
- Source/Lib/Common/Codec/EbRateDistortionCost.h
- Source/Lib/Common/Codec/EbSegmentation.c
- Source/Lib/Common/Codec/EbSegmentation.h
remove decoupled_fast_loop_search_method and decouple_intra_inter_fast_loop
remove fast_candidate_intra_count
replace LargestCodingUnit by SuperBlock
remove unused functions void eb_av1_cdef_search() and void av1_cdef_search16bit()
#668
No Impact
> Cleanup Phase I 

- Config/Sample.cfg
- Source/API/EbSvtAv1.h
- Source/API/EbSvtAv1Dec.h
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncodeContext.h
- Source/Lib/Common/Codec/aom_dsp_rtcd.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
- gstreamer-plugin/gstsvtav1enc.c
- test/InvTxfm2dAsmTest.cc
- test/PsnrTest.cc
- test/RestorationPickTest.cc
- test/TestEnv.c
- test/api_test/SvtAv1EncParamsTest.cc
- test/api_test/params.h
Final remove asm_type.
CPU optimization levels divided into flags (type CPU_FLAGS) , for example AVX512 extensions (AVX512F, AVX512CD, AVX512ER) can exists independently.
To enable optimization limit level use param: -asm [0 - 11, c, mmx, sse, sse2, sse3, ssse3, sse4_1, sse4_2, avx, avx2, avx512, max]
Added print CPU Flags list in Encoder, with information about limitations.
Sample param '-asm ssse3' on CPU with AVX2:
"CPU Flags[ignored]: mmx sse sse2 sss3 ssse3 [sse4_1] [sse4_2] [avx] [avx2]"
Closes #165
> Add optimization level "-asm" to limit cpu features at runtime

- Source/Lib/Common/Codec/EbProductCodingLoop.c
This fixes the following error reported by LLVM memory sanitizer:
```          ==15704==WARNING: MemorySanitizer: use-of-uninitialized-value
#0 0x7f8fea199f72 in av1_filter_intra_allowed /home/magsoft/trunks/SVT-AV1/Source/Lib/Common/Codec/EbEntropyCoding.c:1338:25
#1 0x7f8fea8e6c66 in av1_intra_fast_cost /home/magsoft/trunks/SVT-AV1/Source/Lib/Common/Codec/EbRateDistortionCost.c:757:9
#2 0x7f8fea7dea42 in search_best_independent_uv_mode /home/magsoft/trunks/SVT-AV1/Source/Lib/Common/Codec/EbProductCodingLoop.c:7644:58
#3 0x7f8fea7e418a in md_encode_block /home/magsoft/trunks/SVT-AV1/Source/Lib/Common/Codec/EbProductCodingLoop.c:7884:21
#4 0x7f8fea7f6fdf in mode_decision_sb /home/magsoft/trunks/SVT-AV1/Source/Lib/Common/Codec/EbProductCodingLoop.c:8769:17
#5 0x7f8fea174ba6 in …
```
> Add missing palette size initialization in search_best_independent_uv_mode

- Source/Lib/Common/Codec/EbPictureOperators.c
- Source/Lib/Common/Codec/EbPictureOperators.h
- Source/Lib/Common/Codec/aom_dsp_rtcd.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- test/ResidualTest.cc
Added  assign kernel pointers residual_kernel16bit for SSE2 versions. 
Fix correctly assign kernel pointers on AVX2 versions when remove definition NON_AVX512_SUPPORT
> Added residual_kernel16bit for SSE2, fix assigne pointers kernels

- Source/Lib/Common/Codec/EbPacketizationProcess.c
- Source/Lib/Common/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
1、setting feedback_arrived flag should not be in RateControl process，but in PictureManager process before using it.
2、modifying the look_ahead_period, when both intra_period and look_ahead_period are equal to -1.
> fix deadlock in vbr mode:

- Source/Lib/Common/Codec/EbTransforms.c
- test/TxfmCommon.h
Extend UT to cover kernel eb_av1_fwd_txfm2d_32x16 for DCT_DCT calculation.
I see increase performance of encoder  1280x720 10bits in mode 0 around 1.2%
> Enable AVX2 kernel eb_av1_fwd_txfm2d_32x16() to calculate DCT_DCT

- test/quantize_func_test.cc
this commit is based on the existing LBD quantize unit test framework,
expands to support for HBD
1. Add HBD quantize unit tests:
- eb_av1_highbd_quantize_fp_c
- eb_av1_highbd_quantize_fp_avx2
> Add high bit-depth quantize function unit tests

- Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
the code was modified to use unaligned instructions instead of aligned ones in higbd intra prediction AVX2 kernels based on memory alignment. However the asserts were not removed.
> remove assert for highbd intra prediction AVX2

- .github/workflows/svt-av1.yml
GitHub Actions is weird. But it looks quite powerful, so here's an initial setup for a GitHub Actions Workflow.
This Action (I don't even know what it's called anymore) does nothing more than build SVT-AV1 on Ubuntu 18.04 LTS with GCC 9. This is an initial setup, the fact that this passes or not means nothing for now.
@kylophone @1480c1 Feel free to build out from here! I will probably try to port a lot of stuff over from Travis around Christmas.
Part of #4.
> CI: Create initial GitHub Actions workflow

- Source/Lib/Common/ASM_AVX2/palette_avx2.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.c
- Source/Lib/Common/Codec/aom_dsp_rtcd.h
- Source/Lib/Common/Codec/k_means_template.h
- Source/Lib/Common/Codec/palette.c
- test/PaletteModeUtilTest.cc
Add AVX2 implementation for kernels av1_k_means_dim1(), av1_k_means_dim2() and similar kernels 
av1_calc_indices_dim1() av1_calc_indices_dim2().
Based on command line below, we have 23% performance improvement.
```-enable-altrefs 0 -pred-struct 0 -bit-depth 8 -b out.ivf  -enc-mode 8 -w 1920 -h 1080 -i 1080p.yuv -palette 1 -scm 1 ```
> Implementation of function av1_k_means_dim1, av1_k_means_dim2 for AVX2

- Source/Lib/Common/Codec/EbEncDecProcess.c
As auto max partitioning is a inference based feature using a neural network, it may not provide ideal predictions all the time and thus might impact quality. We are going to move this feature away from M0 to preserve stream quality and have this feature's shortcuts benefit higher enc-modes
> Update auto max partitioning to be performed only for M1 and higher

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbModeDecisionProcess.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Updated M0 settings:
- Optimized independent chroma search for all layers.
- Conservative coeff-based NSQ cands reduction.
- Shut coeff-based skip tx size search, 
- Warped for all layers.
- SUB-SAD as ME search method for non-SC only.
solves #884
@hguermaz 
Enhancement
8BIT data generated for full-list objective-1-fast dataset in context of enc-mode 0. Speed data is generated on the full-list objective-1-fast dataset in context of enc-mode 0 for 5QP in term of cycles on AWS ec2 48 vCPU instances.
| Cycle Increase | BD-Rate Gain|
| -- | --
| 5.5% | 0.20%|
10BIT and jctvc 240p, 480p and 720p clips in context of enc-mode 0. Speed data is generated on the same list for 5QP in term of cycles on AWS ec2 48 vCPU instances.
| Cycle Increase | BD-Rate Gain|
| -- | --
| 8.5% | …
> Enhanced M0 Settings

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
Early exit from tx_size search based on the data of already processed tx_size. This provided 0.044% BDrate gain for about 2% speed up on the full AOM clip set.
> Tx_size search_early_exit

- .travis.yml
- A 10-bit sequence, Chimera-Aerial 480x270, is now available in video.tar.gz. Thanks @1480c1 for copying it to the mirror
- Add 10-bit sequence to the Travis build tests (enc-mode 0, 3 frames, and enc-mode 8, 120 frames)
- Add 8-bit to Travis build tests (enc-mode 0, 3 frames)
- Add 10-bit sequence to binary identical tests (enc-mode 0 and 8)
Closes #850
> Add 10bit test to Travis

- Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Common/Codec/EbCodingLoop.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbEntropyCoding.c
- Source/Lib/Common/Codec/EbMdRateEstimation.c
- Source/Lib/Common/Codec/EbMdRateEstimation.h
- Source/Lib/Common/Codec/EbModeDecision.c
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbMotionEstimation.c
- Source/Lib/Common/Codec/EbPictureControlSet.c
- Source/Lib/Common/Codec/EbPictureControlSet.h
- Source/Lib/Common/Codec/EbUtility.c
Adding the modes and MVs CDF updates. The CDFs are used to generate the rate/cost tables, which are used in mode decision. Initially for each SB, the CDF is equal to the weighted average of left CDF (3x) and top CDF (1x).
**Authors**
@anaghdin
Enhancement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.7% (8 bit and 10 bit) over the fast objective list, using 5 QP values: {20, 32, 43, 55 and 63}.
Speed impact is negligible (<1%)
> Rate est update

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbEncDecProcess.c
- Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Common/Codec/EbMotionEstimationProcess.c
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbPredictionStructure.c
- Source/Lib/Common/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
This PR ports the signal presets from the ms-dec1 branch, which are tuned for better M1 to M8 performance.  These changes (under the PRESETS_TUNE macro) will give the same bitstreams as the ms-dec1 branch under the following conditions:
- RATE_ESTIMATION_UPDATE off
- TX_SIZE_EARLY_EXIT off
- HBD2_COMP off
- HBD2_PME off
- HBD2_OBMC off
- AUTO_MAX_PARTITION off
- config_ptr->enable_hbd_mode_decision = 1
- PRESETS_OPT off
Additionally, the signal presets are further updated (under the PRESETS_OPT macro), based on recent testing data, for better M1-M3 performance.
Closes #902 
Enhancement
The data was generated using the optimizations on top of the ms-dec1 branch settings (listed above), and compared to the ms-dec1 branch (difference to AOM).  NB: a negative speed indicates …
> Update the signal presets

- Source/Lib/Decoder/Codec/EbDecParseObu.c
we will have following error on gcc 7.4
../../../../Bin/Debug/libSvtAv1Dec.so.0.7.5: undefined reference to `reallocate_parse_tile_data'
> compile: fix build for gcc 7.4

- Source/Lib/Common/ASM_AVX2/selfguided_avx2.c
Fix one of valgrind errors from #733
Kernel eb_av1_selfguided_restoration_avx2() read neighboring pixels from right side.
Initialize memory before use.
> Fix valgrind issue in eb_av1_selfguided_restoration_avx2()

- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPacketizationProcess.c
- Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Common/Codec/EbPictureDecisionProcess.c
- Source/Lib/Common/Codec/EbSequenceControlSet.c
- Source/Lib/Common/Codec/EbSequenceControlSet.h
- Source/Lib/Common/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Codec/EbEncHandle.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Use the least possible resource allocation  to have an efficient single core operating mode.
- Fix deadlock with -lad 0
- Latency(controlled by number of parent pcs = number of input) went down from 72 frames to 24 frames:
24 = 17(GOP) + 6(SCD/ALTREF) +1(EOS) + 0 (Needed Pictures for Look-Ahead)
Ref = 17 assuming a 5L GOP.  
Pa-Ref = 25  + 6(SCD/ALTREF) +1(EOS) ,  assuming a 5L GOP. 
- Change output bistream allocation to be done at run time to serve a single threaded app.
- Changes have been made to picture decision to remove the 6-frames delay in case  Scene-Change and ALTREF are OFF.
- Added the ability to unpin the single core execution to allow multiple single core encodes on the same machine without them being pinned to all core 0 [execution is unpinned by default]
- For a 5L GOP, …
> Memory efficient single core mode

- .travis.yml
- Source/Lib/Common/ASM_AVX2/highbd_quantize_intrin_avx2.c
- As in #910, fix stack overwrite eb_av1_highbd_quantize_fp_avx2
- Disallow macOS 10-b test to fail
- Needed to set 'lp' to 1 for it to NOT fail (to be changed when that is fixed)
> Fix quant_hbd and macos 10b crash

- Source/Lib/Common/Codec/EbModeDecision.c
Github Issue: #733
at 0x4F2AE52: update_av1_mi_map (EbAdaptiveMotionVectorPrediction.c:1504)
by 0x4F4AEFE: av1_encode_pass (EbCodingLoop.c:3805)
by 0x4F5F324: enc_dec_kernel (EbEncDecProcess.c:3189)
by 0x1012DDD4: start_thread (in /usr/lib64/libpthread-2.17.so)
by 0x10741EAC: clone (in /usr/lib64/libc-2.17.so)
at 0x4F2B61F: update_mi_map (EbAdaptiveMotionVectorPrediction.c:1596)
by 0x5051495: md_update_all_neighbour_arrays (EbProductCodingLoop.c:673)
by 0x50514FD: md_update_all_neighbour_arrays_multiple (EbProductCodingLoop.c:694)
by 0x5066DE1: mode_decision_sb (EbProductCodingLoop.c:9779)
by 0x4F5F2D2: enc_dec_kernel (EbEncDecProcess.c:3160)
by 0x1012DDD4: start_thread …
> Fixes for update_av1_mi_map() and update_mi_map() valgrind errors

- Source/Lib/Common/ASM_SSE2/CMakeLists.txt
- Source/Lib/Common/ASM_SSSE3/CMakeLists.txt
if you only install nasm on your system, build will fail and report following error:
`C:\Program Files\CMake\share\cmake-3.16\Templates\MSBuild\nasm.targets(33,5): error MSB3721: The command ""C:/Program Files/NASM/nasm.exe" -o "COMMON_ASM_SSE2.dir\Debug\x64Macro.obj" -fwin64 -I"C:\projects\SVT-AV1\mybuild\Source\Lib\Common\ASM_SSE2\\" -I"C:\projects\SVT-AV1\Source\Lib\Common\ASM_SSE2\\" -I"C:\projects\SVT-AV1\Source\API\\" -I"C:\projects\SVT-AV1\Source\Lib\Common\Codec\\" -I"C:\projects\SVT-AV1\Source\Lib\Common\C_DEFAULT\\" -D"WIN32" -D"_WINDOWS" -D"NON_AVX512_SUPPORT" -D"CMAKE_INTDIR="Debug"" -D"WIN64" -gcv8 "C:\projects\SVT-AV1\Source\Lib\Common\ASM_SSE2\x64Macro.asm"" exited with code 3.`
This is because we set some asm includes as compile files. Exclude them will fix the issue.
This …
> asm: fix build for nasm

- test/ref/TxfmRef.cc
1. Txfm unit test triggers assertion failed after 64x64 TxSize added into tests:
~~~
18:03:40 SvtAv1UnitTests: /home/av1-slave1/workspace/SVTAV1-Coverage/test/ref/TxfmRef.cc:149: void svt_av1_test_reference::reference_idtx_1d(const double*, double*, int): Assertion `0' failed.
18:03:40 xargs: env: terminated by signal 6
~~~
this commit fixes it in TxfmRef.cc
> Fix assertion failed in transform unit tests

- Source/App/EncApp/EbAppConfig.c
Calling `fprintf` on `stderr` after we close it is causing MSVC to raise an assert failure, fixes the issue in https://github.com/OpenVisualCloud/SVT-AV1/pull/919#issuecomment-568906796
> EbAppConfig: Don't call fclose on error_log_file if it's equal to stderr

- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
```none
LD	ffprobe_g.exe
D:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbFullLoop.c.obj): warning: definition of `allowed_tx_set_a' overriding common from D:/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbProductCodingLoop.c.obj)
D:/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/media-autobuild_suite/local64/lib/libxvidcore.a(mbcoding.obj):mbcoding.c:(.text+0x4110): multiple definition of `get_mv'; D:/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbInitialRateControlProcess.c.obj):EbInitialRateControlProcess.c:(.text+0x790): first defined here
collect2.exe: error: ld returned 1 …
```
> Rename get_mv to eb_get_mv to fix conflicts between libxvidcore

- Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
Signed-off-by: Luis Garcia <luigi311.lg@gmail.com>
Building debug and running it causes a memory leak as reported by SvtMalloc.
Command used:
sudo ./SvtAv1EncApp -i ../../../Chim*.y4m -enc-mode 8 -b test.mkv
Message:
SvtMalloc[error]: malloced memory leaked at /home/luis/Desktop/SVT-AV1/Source/Lib/Encoder/Codec/EbModeDecisionProcess.c:L115
This will add a EB_FREE_ARRAY for the palette_info in the fast_candidate_ptr_array pointer due to just doing the EB_FREE_ARRAY on the entire pointer still leaves the memory leak
> Fix memory leak on EbModeDecisionProcess.c:L115

- Docs/svt-av1_encoder_user_guide.md
This should have been included with the vbv-bufsize code. 
Also corrected minor issue with TargetBitRate not having been updated to new RateControl modes.
> Added -vbv-bufsize to encoder doc. 

- Source/App/EncApp/EbAppConfig.c
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfiletype
GetFileType needs a HANDLE not a FILE*.
> windows: fix assert in GetFileType

- appveyor.yml
Used to using `-ne` to test if a variable present, not backwards.
> Appveyor: Fix logic error in pushing an artifact

- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
==21579== Conditional jump or move depends on uninitialised value(s)
==21579==    at 0x4A4BFEC: av1_split_flag_rate (Source/Lib/Encoder/Codec/EbRateDistortionCost.c:2554)
==21579==    by 0x4947D02: d1_non_square_block_decision (Source/Lib/Encoder/Codec/EbFullLoop.c:3284)
==21579==    by 0x4A2D9AB: mode_decision_sb (Source/Lib/Encoder/Codec/EbProductCodingLoop.c:6787)
==21579==    by 0x4916459: enc_dec_kernel (Source/Lib/Encoder/Codec/EbEncDecProcess.c:2766)
==21579==    by 0xF3AC668: start_thread (pthread_create.c:479)
==21579==    by 0xF637322: clone (clone.S:95)
==21579== Conditional jump or move depends on uninitialised value(s)
==21579==    at 0x4A4C057: av1_split_flag_rate (Source/Lib/Encoder/Codec/EbRateDistortionCost.c:2559)
==21579==    by 0x4947D02: d1_non_square_block_decision …
> EbProductCodingLoop: fix valgrind errors

- Source/Lib/Common/ASM_AVX512/highbd_inv_txfm_avx512.c
- test/InvTxfm2dAsmTest.cc
- test/TxfmCommon.h
Modify UT to cover mismatch
Fix for linux Release UT that cause: segmentation fault
I do not see any performance change, compared to previous implementation
> Fix mismatch between AVX512 and AVX2/C eb_av1_inv_txfm2d_add_64x16() kernel

- Source/Lib/Encoder/Codec/EbCodingLoop.c
this function is meant to save the current mv set and will be used as tmvp for following frames.
However, it overwritten the data, and it will cause some mistakes in some rare cases.
For example, if sb size is 64x64. if we process (0,256) first, and (576, 0) later. the mv of block starting at (0,256) may be overwritten by the mv from (576, 0).
It will affect the mode decision a bit.
For multi-tile case, it is more easy to trigger, and may also affect the entropy part(when building the tmvp stack), and cause corrupt bitstreams
> Fix the tmvp issue

- Source/Lib/Common/Codec/EbBlockStructures.h
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbPictureBufferDesc.c
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbDlfProcess.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.h
- Source/Lib/Encoder/Codec/EbEncDecResults.h
- Source/Lib/Encoder/Codec/EbEncDecSegments.c
- Source/Lib/Encoder/Codec/EbEncDecTasks.h
- Source/Lib/Encoder/Codec/EbEntropyCoding.c
- Source/Lib/Encoder/Codec/EbEntropyCoding.h
- Source/Lib/Encoder/Codec/EbEntropyCodingObject.h
- Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
- Source/Lib/Encoder/Codec/EbMdRateEstimation.c
- Source/Lib/Encoder/Codec/EbMdRateEstimation.h
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/EbRestProcess.c
- Source/Lib/Encoder/Codec/EbSequenceControlSet.c
- Source/Lib/Encoder/Codec/EbSequenceControlSet.h
- Source/Lib/Encoder/Globals/EbEncHandle.c
-Enabled tile group parallelism at encDec kernel, now set tile group the same as tile row
-Enabled tile parallelism at enctropy kernel
-Fixed a bug during saving the mvs
-Enabled palette for tile parallelism at entropy kernel
-Improved the tile_size_bytes_minus_1 field
> Enable tile parallelism

- Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
This reverts commit aa05a85ea1d5c27240993c936300000f48cc1ffd.
It inserted a wrong logic that decreases the BD-RATE performance of some
samples.
> Revert "EbproductCodingLoop: fix valgrind errors (#966)"

- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
A bitstream corruption occured in M3 triggered when over_boundary_block_mode is disabled.
Block partition is not initialized properly.
using init_sq_nsq_block instead of init_sq_non4_block guarantees initialization of partition for all blocks.
Partition is used in encode_pass (if (part != PARTITION_SPLIT && scs_ptr->sb_geom[sb_addr].block_is_allowed[blk_it]) {) .
> Fix bitstream corruption: use init_sq_nsq_block instead of init_sq_non4_block 

- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
Since it is an I_SLICE, no global motion has been computed. We must
fallback to default_warp_params for entropy coding.
This should fix #986.
> EbPictureManagerProcess: do not take an I_SLICE as global motion reference

- .github/workflows/svt-av1.yml
There was an issue reported by @mafonsoN and @luigi311 where the the libraries were not being correctly linked when running the branch and master executables in the binary identical test.
See:
- https://github.com/OpenVisualCloud/SVT-AV1/pull/963/checks?check_run_id=413615745
- https://github.com/OpenVisualCloud/SVT-AV1/runs/414096956
I reordered the steps, changed the build from dynamically linked to statically linked, and changed where executables are called for clarity. 
Additionally, if the binary identical test fails on mismatch, we upload both files as artifacts so that they can be inspected for debugging.
Problem discussed in #873
> Resolve library errors for binary identical test in Github Actions

- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
fixes #738
For intra peroid 50, the frame with decoder order 50's mini_gop_hierarchical_levels is 3
frame 51's mini_gop_hierarchical_levels 4.
so the frame 50's dts will be 50 - (1<<3) + 1 = 43
frame 51's dts will be 51 - (1<<4) + 1 = 36
ffmpeg will complain about:
" Non-monotonous DTS in output stream 0:0; previous: 43, current: 36; changing to 44. This may result in incorrect timestamps in the output file"
uses a constant hierarchical_level will fix it.
The patch tested by following command line:
"ffmpeg -i test.mp4  -c:v libsvt_av1  -g 1 out.mp4 -y"
"ffmpeg -i test.mp4  -c:v libsvt_av1 -g 50 out.ivf -y"
> Packetization: fix Non-monotonous DTS

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Globals/EbEncHandle.c
make OIS: open Loop intra search results allocation in parent pcs structure based on config demand.
Memory Footprint Reduction
@chkngit 
Memory footprint reduction of an M0 1080 p encode (-lad 0, -lp 1) from ~2GB to ~1.5GB
> Ois memory reduction

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
MD rate estimation enhancement (MD_RATE_EST_ENH). Use the CDFs from the previous SB. Active for LP =1 for now
**Authors**
@anaghdin
Enhancement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.4% (8 bit and 10 bit) over the fast objective list, using 5 QP values: {20, 32, 43, 55 and 63}.
Speed impact is negligible (<1%)
**To Do**
To make it work with multi-segments
> MD rate estimation enhancement

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
ALT REF filtering improvement:
- Enable TF for layer 1 in 1 pass encoding (already active in 2 pass) 
- Adjust the filter strength
**Authors**
@anaghdin
Enhancement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.5% (~-0.2% for TF in layer 1 and -0.3% for strength update) for 1 pass encoding over the fast objective list, using 5 QP values: {20, 32, 43, 55 and 63}.
Speed impact in context of M0 ~1%
> ALT REF Filtering Improvement

- Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.h
- Source/Lib/Encoder/Codec/EbEntropyCoding.c
- Source/Lib/Encoder/Codec/EbFullLoop.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
This PR should fix the following valgrind issues and should not modify the bitstream:
```
at 0x4AA1DBA: merge_1d_inter_block (Source/Lib/Encoder/Codec/EbFullLoop.c:3247)
by 0x4AA1F5E: d1_non_square_block_decision (Source/Lib/Encoder/Codec/EbFullLoop.c:3278)
by 0x4B89D60: mode_decision_sb (Source/Lib/Encoder/Codec/EbProductCodingLoop.c:7032)
by 0x4A6FC57: enc_dec_kernel (Source/Lib/Encoder/Codec/EbEncDecProcess.c:2800)
by 0xF3BD668: start_thread (pthread_create.c:479)
by 0xF648322: clone (clone.S:95)
at 0x4AA1DFB: merge_1d_inter_block (Source/Lib/Encoder/Codec/EbFullLoop.c:3250)
by 0x4AA1F5E: d1_non_square_block_decision (Source/Lib/Encoder/Codec/EbFullLoop.c:3278)
by …
```
> Fix valgrind issues

- Config/PredStruct_level0.cfg
- Config/PredStruct_level1.cfg
- Config/PredStruct_level2.cfg
- Config/PredStruct_level3.cfg
- Config/PredStruct_level4.cfg
- Config/PredStruct_level5.cfg
- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/API/EbSvtAv1ErrorCodes.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncodeContext.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPredictionStructure.c
- Source/Lib/Encoder/Codec/EbPredictionStructure.h
- Source/Lib/Encoder/Globals/EbEncHandle.c
This PR implements manual prediction structure, user can specify the prediction structure via the configuration file with command line "-pred-struct-file xx/PredStruct_level0.cfg".
Some example prediction structure configuration files are placed at SVT-AV1\Config\PredStruct_level0.cfg~PredStruct_level5.cfg, which match the fixed prediction structure in current code. 
When prediction structure configration file is used, hierarchical_levels value in command line is ignored, and will be set the actual size automatically accoring to the prediction structure configuration file.
There are still some restrictions on this manual prediction structure due to the current SVT_AV1 framework:
1. Only hierarchical prediction structure is supported
2. The maximum levels supported is 5 (minigop 32)
3. …
> Support manual prediction structure

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbFullLoop.c
quantize_fp is now added for INTER blocks @ RDOQ (previously added for INTRA blocks only). quantize_b is still called when RDOQ is not used (quantize_b and quantize_fp are both libaom kernels).
Also added the support for Fast_RDOQ (libaom technique). The idea consists of reducing the number of non-zero quantized coefficients before getting to the main/complex RDOQ stage (it performs an early check whether to zero out or not each of the non-zero quantized coefficients, and early exit if all are zeroed-out).
closes #1001 
Enhancement
@hguermaz 
Testing was performed on the objective-1-fast dataset (8 bit) in context of CORE.  A BD-rate gain of -0.27% was found for M0, with no speed deviation.
For 10 bit testing, fourteen 720p true 10bit clips were used.  In context of …
> Enhanced RDOQ

- Source/Lib/Encoder/Codec/EbSequenceControlSet.c
- Source/Lib/Encoder/Codec/EbSequenceControlSet.h
Simplified the logic in the copy sequence control set
Removed individual member copy and unused write_count
variable.
Bulk of the copying is now done by a simple EB_MEMCPY
sb_geom and sb_params_array structures are handled with
special logic.
> SequenceControlSet Copy

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbUtility.c
- Source/Lib/Common/Codec/EbUtility.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbEntropyCoding.c
- Source/Lib/Encoder/Codec/EbFullLoop.c
- Source/Lib/Encoder/Codec/EbFullLoop.h
- Source/Lib/Encoder/Codec/EbIntraPrediction.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Unified the tx partitioning path (txs/txt search) and the default path (txt search only) @ full_loop_core() into 1 unique path (i.e. product_full_loop_tx_search() is removed, and only tx_type_search() is now called). This will make future development(s) easier (1 spot to modify instead of 2).
- Added txs early exit (if cost of performed child tx(s) is higher than the cost of the Parent tx then exit current Tx depth) .
- Bypassed txt search for Tx(s) where only DCT is allowed (if tx width > 32 or tx high > 32).
- Bypassed INTRA compensation for Tx depth 0 as previous stage predicted samples could be re-used.
- Added the ability to specify whether frequency or spatial domain @ distortion calculation per PD/MD stage.
- Removed useless tx signal(s).  
- Updated tx block geometry. …
> Tx Path Unification and Enhancements

- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_AVX2.h
- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
nxm_sad_kernel_sub_sampled_helper_avx2 modification to call avx2 code for block width: 128, 48, 24
(WxH) different block sizes
128x128 45.43x
128x64 81.64x
24x32 43.57x
24x24 42.09x
24x16 38.75x
48x48 53.03x
48x32 51.83x
48x16 42.86x
> nxm_sad_kernel_sub_sampled_helper_avx2 modification to call avx2 code for block width: 128, 48, 24

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbInterPrediction.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
Improve warp motion by enabling warp motion for all references in list 0 and list 1
**Authors**
@anaghdin
Enhancement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.2% for 1 pass encoding over the fast objective list, using 5 QP values: {20, 32, 43, 55 and 63}.
Speed impact in context of M0 ~1%
> Improve Warp motion

- .github/workflows/ci.yml
1. discributes unit tests in shards based on PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/958
2. disabled some failure unit test cases:
a) Convolve/HBDVariace fixed in PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/954
b) sad_Calculation fixed in PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/969
3. fixed transform crash in PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/944, to avoid being interrupted during testing.
> distribute unit tests in GitHub CI

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
Change the QP assignment for CQP
Support QP assignment for different prediction structures
**Authors**
@anaghdin
Enhancement
Average PSNR-SSIM BD-rate gain in the range of -0.8% for 1 pass encoding and -1% for two pass encoding over the fast objective list, using 5 QP values: {20, 32, 43, 55 and 63}
Speed impact in context of M0 ~0%
> Change the QP assignment

- Config/PredStruct_level5.cfg
- Source/Lib/Encoder/Codec/EbEncodeContext.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPredictionStructure.c
This PR fixes issues in manual prediction structure scheme:
1. Move updating dependent lists for I slice from I slice to the start of the next minigop, because DPB management in manual prediction structure scheme needs processing frames in encoding order in a minigop, and I slice is always the first frame in encoding order but the last frame in display order in a minigop.
2. Fix merge issue for level5, YUV decoded from the streams made by the same manual and fixed prediction structures respectively can be bit identical.
> Fix issues in manual prediction structure scheme

- Source/Lib/Encoder/Globals/EbEncHandle.c
- test/api_test/SvtAv1EncParamsTest.cc
- test/e2e_test/SvtAv1E2EFramework.cc
- test/e2e_test/SvtAv1E2EParamsTest.cc
- test/e2e_test/SvtAv1E2ETest.cc
Fix for unsupported RateControlMode format in tests
Fix for tile rows/cols tests
Added additional validiation for encode_color_format, only 420 is supported
> Fix all tests from SvtAv1E2ETests

- .travis.yml
Add builds jobs for 64-bit ARMv8, PowerPC (64-bit, little-endian) and IBM Z. All on Linux with GCC 9. Are allowed to fail (for now).
For general distribution SVT-AV1 has to be able to be compiled on different CPU architectures then x86. It doesn't need to be fast or optimized, it just needs to compile and run.
> Travis CI: Add build jobs on other CPU architectures

- .github/workflows/ci.yml
1. add e2e tests with GTest sharded mode to accelerate: parallel running e2e tests in multiple tasks.
> add e2e tests in GitHub CI

- Source/Lib/Encoder/Codec/EbPictureControlSet.c
Minor extra line of code introduced during the enc/common/dec separation was causing a leak, visible in debug mode.
> Fix mutex leak in debug mode and extra commented code

- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
The Visual Studio version wasn't reported correctly in many instances, this PR fixes that.
Based on https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros
> Enc/dec handle: Fix reported Visual Studio version

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
General Idea:
Restructure the motion estimation to perform the following steps:
1- HME search for all available N reference pictures
2 - Select a subset M <= Nof reference pictures to be used for the next steps
3- Integer-pel search on the N reference pictures
4- Select a subset H <= M of reference pictures to be used for the next steps
5- Subpel search on the H reference pictures
Algorithm details:
If HME SAD deviation to Best SAD is > TH%=80% (default) -> Prune reference MV ELSE IF
If Fullpel ME SAD deviation to Best SAD is > TH%=30% (default) -> Prune reference MV  
#1047 
* Bdrate 0.04% loss
* Speed 3% of speed up
* Memory 0%
> Multi stages me

- Config/Sample.cfg
- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
The screen content detector is having a lot of misdetections e.g. niklas clip. Also the detection takes place at the picture decision process and some features would need to be turned on / off (such as MRP, the max block size) at init time and switching them would cause major stability issues if done at run-time
This PR sets the detection to be off by default until further work is done there to solve all of these problems.
Screen content clips would have to be encoded using -scm 1
> Default -scm to 0

- Source/Lib/Common/ASM_AVX512/CMakeLists.txt
- Source/Lib/Common/ASM_AVX512/convolve_avx512.h
- Source/Lib/Common/ASM_AVX512/synonyms_avx512.h
- Source/Lib/Common/Codec/EbBlend_a64_mask.c
- Source/Lib/Encoder/ASM_AVX2/EbNoiseExtractAVX2.h
This PR fixes the compilation issue when using old version of gcc, e.g. 4.8.5.
Unnecessary intrinsic data type usage in header files are removed.
> Fix compilation error for old gcc

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Used Spatial Domain Distortion @ only the last stage (PD2/MD_STAGE_3).
- Removed layer check(s) from PD1 settings derivation.
@hguermaz 
Tuning/Clean-up.
| -- | --
| 3.67% | -0.023%|
> Updated Multi-Pass-PD and MD-Staging Settings

- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbRestoration.c
- Source/Lib/Encoder/Codec/EbCdefProcess.c
- Source/Lib/Encoder/Codec/EbDeblockingFilter.c
- Source/Lib/Encoder/Codec/EbDlfProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
- Source/Lib/Encoder/Codec/EbReferenceObject.c
- Source/Lib/Encoder/Codec/EbRestProcess.c
This PR introduces the changes for 16bit pipeline, which controls whether to use 16bit pipeline for filter (dlf, cdef, rest) according to a new cfg parameter `-16bit-pipeline`.
Currently, recon is copied to recon16 before filter, while recon16 is copied back to recon after filter. The code for copy can be removed once the 16bit pipeline is ready the entire encoding process.
> 16bit pipeline for filter

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_AVX2.h
- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Encoder/C_DEFAULT/EbComputeSAD_C.c
- Source/Lib/Encoder/C_DEFAULT/EbComputeSAD_C.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- test/SadTest.cc
Rebase PME_SAD_OPT branch to make it applicable for master
ENABLE_PME_SAD : used SAD instead of SSD for FUll_Pel
SWITCH_XY_LOOPS_PME_SAD: loop over search region width first
RESTRUCTURE_SAD: Restructure SAD calculation for PME full pel to make it simd friendly
Implementation of pme_sad_loop_kernel_avx2 with coressponding UT
Added support for maximum block size from 64x64 to 128x128
Loop unrolling for blocks 4x4, 4x8,4x16,8x4,8x8 pme_sad_loop_kernel_avx2
Speedup compared to previous implementation:
4x4  2.1x
4x8  1.9x
4x16 1.8x
8x4  1.8x
8x8  1.5x
None
> Rebase PME_SAD_OPT branch to make it applicable for master

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Use  valid previously encoded similar  blocks (block having the same location and shape , but different neighbours  as the current block). to prune the compounds/inter modes to search at MD
1- If previous similar block is not compound, do not inject compound for current block
2- If previous similar block is not compound, do not inject compound for current block
else consider the compound modes up the similar’s one
3- If previous similar block is intra, do not inject inter current block
in context of enc-mode 0 using mixed mpeg/aom set (T00)
| -- | --
| 2.52% | 0.00%|
> Prune Compound/Inter From Similar Blocks

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Parent ME MV (instead of 64x64 ME MV) as Nx4 & 4xN INTER candidates.
- 1/8 Pel ME MVs  refinement
@hguermaz 
Enhancement.
| -- | --
| 0.12% | -0.041%|
> Enhanced Nx4 & 4xN INTER candidates and 1/8 Pel ME MVs refinement

- .travis.yml
An error in Homebrew caused yasm to fail to install on macOS. This PR migrates that by updating Homebrew before install.
See https://github.com/Homebrew/homebrew-bundle/issues/646 and https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/7
> Travis CI: Fix dependencies not installing on macOS

- appveyor.yml
As of this moment, AppVeyor is now 40 jobs behind, with an average of 25 minutes per job that's over 16 hours. We should speed it up significantly, this PR starts that by dropping the Visual Studio debug job.
@1480c1 What do you think about further options to speedup AppVeyor?
> CI: Speed up AppVeyor by dropping VS debug job

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Perform the Chroma search algorithm just before the last md stage and only when at least one intra mode make it to this stage.
This is a replacement of PR#1039
#1047 
* Bdrate 0.02% Bdrate loss
* Speed 3.5% speed up
* Memory 1% increase
> Chroma search optimization 2

- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Encoder/Codec/EbEncodeContext.h
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.c
- Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.h
- test/e2e_test/SvtAv1E2EFramework.cc
Currently, we output one frame per get ouptut, and the "show existing frame" shares the same pts with the previous frame.
This will introduce jitter to "show existing frame" and the previous frame.
We should output a temporal unit a time.
A temporal unit includes one TD + zero or more undisplay frame + one display frame.
And we need to stamp a different pts for show existing frame since it is a displayable frame.
after apply this patch, ffmpeg will not report error for following test command:
ffmpeg -i 320x240.y4m -c:v libsvt_av1 -vframes 100 test.mkv  -y &&  ffmpeg -c:v libdav1d -i test.mkv -f null /dev/null
and ffmpeg will not insert td for every frame if we use following command:
ffmpeg -i 320x240.y4m -c:v libsvt_av1 -vframes 100 test.ivf  -y
fixes …
> packetization_kernel: pack entire temproal unit for a output buffer

- Source/Lib/Encoder/ASM_AVX2/EbNoiseExtractAVX2.c
debug build will show following errors:
../../../../Bin/Debug/libSvtAv1Enc.so.0.8.1: undefined reference to `luma_weak_filter_128_avx2_intrin'
../../../../Bin/Debug/libSvtAv1Enc.so.0.8.1: undefined reference to `luma_weak_filter_avx2_intrin'
../../../../Bin/Debug/libSvtAv1Enc.so.0.8.1: undefined reference to `chroma_strong_avx2_intrin'
../../../../Bin/Debug/libSvtAv1Enc.so.0.8.1: undefined reference to `chroma_strong_128_avx2_intrin'
../../../../Bin/Debug/libSvtAv1Enc.so.0.8.1: undefined reference to `chroma_weak_luma_strong_filter_128_avx2_intrin'
../../../../Bin/Debug/libSvtAv1Enc.so.0.8.1: undefined reference to `chroma_weak_luma_strong_filter_avx2_intrin'
collect2: error: ld returned 1 exit status
make the inline function in .c as static will fix the problem.
> build: fix debug build for gcc

- Source/Lib/Encoder/Codec/EbEncDecSegments.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
Bin/Debug/SvtAv1EncApp -i in.yuv -w 176 -h 144 -b out.ivf -tile-rows 1 -tile-columns 1
you will get the leak print out
> fix memory leaks for tile encoder

- Source/Lib/Common/ASM_AVX2/EbHighbdIntraPrediction_AVX2.c
- Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_AVX2/aom_subpixel_8t_intrin_avx2.c
- Source/Lib/Common/ASM_AVX2/convolve_2d_avx2.c
- Source/Lib/Common/ASM_AVX2/convolve_avx2.c
- Source/Lib/Common/ASM_AVX2/convolve_avx2.h
- Source/Lib/Common/ASM_AVX2/highbd_convolve_2d_avx2.c
- Source/Lib/Common/ASM_AVX2/highbd_jnt_convolve_avx2.c
- Source/Lib/Common/ASM_AVX2/jnt_convolve_2d_avx2.c
- Source/Lib/Common/ASM_AVX2/jnt_convolve_avx2.c
- Source/Lib/Common/ASM_AVX2/selfguided_avx2.c
- Source/Lib/Common/ASM_AVX2/synonyms_avx2.h
- Source/Lib/Common/ASM_AVX2/txfm_common_avx2.h
- Source/Lib/Common/ASM_AVX2/warp_plane_avx2.c
- Source/Lib/Common/ASM_AVX512/convolve_2d_avx512.c
- Source/Lib/Common/ASM_AVX512/convolve_avx512.c
- Source/Lib/Common/ASM_AVX512/jnt_convolve_2d_avx512.c
- Source/Lib/Common/ASM_AVX512/jnt_convolve_avx512.c
- Source/Lib/Encoder/ASM_AVX2/EbTransforms_Intrinsic_AVX2.c
- Source/Lib/Encoder/ASM_AVX2/fft_avx2.c
- Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
- Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
- Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
- Source/Lib/Encoder/ASM_AVX512/highbd_fwd_txfm_AVX512.c
- Source/Lib/Encoder/ASM_AVX512/pickrst_avx512.c
- Source/Lib/Encoder/ASM_SSE2/fft_sse2.c
this is a follow up for https://github.com/OpenVisualCloud/SVT-AV1/pull/853
following assembly code changed:
_mm_load_ps,
_mm_store_ps,
_mm256_load_si256,
_mm256_store_si256,
_mm256_load_ps,
_mm256_store_ps,
enc-mode 8 and 4 are tested, no obvious fps drop.
> asm: change aligned read/store to unaligned read/store

- .travis.yml
- README.md
Since our coveralls is not reporting an accurate coverage number, we will disable the CI hook for now. When this is fixed, this commit can be reverted.
> Travis: disable coveralls for the moment

- Source/App/DecApp/EbDecAppMain.c
- Source/Lib/Common/Codec/Av1Common.h
- Source/Lib/Common/Codec/EbAv1Structs.h
- Source/Lib/Common/Codec/grainSynthesis.c
- Source/Lib/Decoder/Codec/EbDecBitstream.c
- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Decoder/Codec/EbDecHandle.h
- Source/Lib/Decoder/Codec/EbDecLF.c
- Source/Lib/Decoder/Codec/EbDecMemInit.c
- Source/Lib/Decoder/Codec/EbDecParseBlock.c
- Source/Lib/Decoder/Codec/EbDecParseInterBlock.c
- Source/Lib/Decoder/Codec/EbDecParseObu.c
- Source/Lib/Decoder/Codec/EbDecPicMgr.c
- Source/Lib/Decoder/Codec/EbDecPicMgr.h
- Source/Lib/Decoder/Codec/EbDecProcess.c
- Source/Lib/Decoder/Codec/EbDecRestoration.c
Following are the changes:
1. Bug Fixes related to film_grain: chroma_scaling_from_luma, odd resolution supprt
2. Fixes related to Storing of qindex for each segment id & segment_id from prev frame
3. Bug Fixes related to parsing of DeltaFrameIdLength & delta_lf
4. LF bug_fixes related to odd resolution & lossless mode
5. MT bug fix related to a hang at the end
6. Bug fix related to early exit in Motion field projection 
7. Super_res bug fixes related to smaller frame dim.( less than 16)
> Bug fixes in decoder related to segment id, delta lf, film grain, etc

- .github/workflows/ci.yml
1. change check flow from actions/checkout@v1 to actions/checkout@v2
- to resolve issue of GitHub CI action can not checkout source code sometimes, 
2. disabled DummySrcTest to avoid out of memory in GitHub CI test machine
- to resolve the out-of-memory issue (signal 9) happened in PRs:
[1063](https://github.com/OpenVisualCloud/SVT-AV1/runs/459759523) [1066](https://github.com/OpenVisualCloud/SVT-AV1/runs/461281875) [1071](https://github.com/OpenVisualCloud/SVT-AV1/runs/463515577)
> refine unit test in github ci to cs2 branch

- .github/workflows/ci.yml
1. change check flow from actions/checkout@v1 to actions/checkout@v2
- to resolve issue of GitHub CI action can not checkout source code sometimes, 
2. disabled DummySrcTest to avoid out of memory in GitHub CI test machine
- to resolve the out-of-memory issue (signal 9) happened in PRs:
[1063](https://github.com/OpenVisualCloud/SVT-AV1/runs/459759523) [1066](https://github.com/OpenVisualCloud/SVT-AV1/runs/461281875) [1071](https://github.com/OpenVisualCloud/SVT-AV1/runs/463515577)
> refine unit test in github ci

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncCdef.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.h
- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbFullLoop.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/EbTransforms.h
_________________________________________________________________________________
- Fix lambda for HBD (hbd mode 0, 1 and 2)
- Fix the mismatch of using 10bit vs 8bit lambda depending on the hbd-mode and/or the kernel.
_________________________________________________________________________________
@okhlif 
_________________________________________________________________________________
Enhancement.
_________________________________________________________________________________
Data generated on the 14 720p true 10bit in context in enc-mode 0.
Speed Deviation | BD-Rate Deviation
-- | --
no speed diff | -0.45%
> Fix lambda for HBD

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Moved IFS from MD_STAGE_1 to MD_STAGE_3.
| -- | --
| 4.45% | 0.02%|
> Moved IFS from MD_STAGE_1 to MD_STAGE_3

- Source/Lib/Common/Codec/common_dsp_rtcd.c
- Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
- Source/Lib/Encoder/ASM_SSE2/variance_sse2.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- test/CompoundUtilTest.cc
- test/EbHighbdIntraPredictionTests.cc
- test/SadTest.cc
- test/WedgeUtilTest.cc
- test/intrapred_cfl_test.cc
1. Remove unused function declaration
2. UT and fix for get_eight_horizontal_search_point_results_8x8_16x16_pu_avx512_intrin
3. UT for eb_aom_highbd_blend_a64_vmask_sse4_1
4. UT for eb_aom_highbd_blend_a64_hmask_sse4_1
5. UT for av1_build_compound_diffwtd_mask_highbd_ssse3
6. UT for av1_build_compound_diffwtd_mask_highbd_avx2
7. UT for aom_sse_avx2
8. UT for aom_highbd_sse_avx2
9. UT for eb_aom_subtract_block_sse2
10. UT for aom_subtract_block_avx2
11. UT for aom_highbd_subtract_block_sse2
12. UT for aom_sum_squares_i16_sse
13. UT for av1_get_gradient_hist_avx2
14. UT and fix for aom_upsampled_pred_sse2
> Implementation of missing UT with bugfixes (import from cs2 branch)

- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.h
- Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
Reduce the complexity of the motion estimation by avoiding the full_pel and sub_pel searches for NSQ blocks and inherit their motion vectors from SQ blocks. This feature is enabled only for screen content.
* BDrate 0.17% loss
* Speed 24.5% gain
* Memory 0%
InputSequence | Resolution | Bdrate PSNR-YUV | Bdrate SSIM-YUV | Encoding time   deviation
MINECRAFT_60f_420 | 1920x1080 | 0.09% | 0.10% | 22.02%
SlideEditing_1280x720_30_60f | 1280x720 | 0.08% | 0.13% | 18.59%
SlideShow_1280x720_20_60f | 1280x720 | 0.05% | 0.04% | 22.60%
wikipedia_420 | 1920x1080 | 0.45% | 0.42% | 34.66%
  | Average | 0.17% | 0.17% | 24.47%
> Me nsq opt

- Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h
- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_AVX512/EbPictureOperators_AVX512.h
- Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
- Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c
- Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.h
- Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
- Source/Lib/Common/Codec/EbPictureOperators.c
- Source/Lib/Common/Codec/EbPictureOperators.h
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbFullLoop.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- test/SpatialFullDistortionTest.cc
The MV offset recon_offset is taken as unsigned value in function spatial_full_distortion_kernel_avx2(), then minus value MV like (-36, -10) generate very big recon_offset for forcing to be unsigned int type, it causes the recon buffer points to far away invalid memory, it should change to  signed value int32_t type.
Quality and speed are impacted only when functions spatial_full_distortion_kernel and full_distortion_kernel16bit are called, very slight impact.
Speed Deviation | BD-Rate Deviation
-- | --
-- | 0.00%
> fixed run2run issue caused by uint32_t recon_offset

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
Enhanced I_SICE QP assignment.
full AOM 8 bit and 10 bits list
AOM list | Speed Deviation | BD-Rate Deviation
-- | -- | --
8bit |1.41% | -0.21%
10bit |1.31% | -0.28%
Signed-off-by: anaghdin <amir.naghdinezhad@intel.com>
> Enhanced I_SICE QP assignment

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
nsq_hv_level :
0:  OFF
1: ON  if H>V + TH1% then  skip HA/HB/H4  
if V>H+ TH1% then   skip VA/VB/V4  
in context of cs2 branch / enc-mode 0. 
| -- | --
| ~+1.95% | -0.02%|
> nsq_weight : skip NSQ partitions based on H vs V costs

- Source/API/EbSvtAv1.h
- Source/Lib/Common/Codec/EbSystemResourceManager.c
- Source/Lib/Common/Codec/EbSystemResourceManager.h
- Source/Lib/Common/Codec/EbThreads.c
- Source/Lib/Encoder/Codec/EbCdefProcess.c
- Source/Lib/Encoder/Codec/EbDlfProcess.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/EbRestProcess.c
- Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Avoid using TerminateThread/pthread_cancel which causes issue with multiple continues init/deinit of encoder lib. A customer reported this issue before to SVT-HEVC. This is the fix of it by sending quit signal from main thread to all the kernels. Kernel will break out from the loop once quit signal is set.
Ported from SVT-HEVC. Author: jing.b.li@intel.com
* BDrate: same
* Speed: same
* Memory: Around 1200(number of fifo object) * EbBool(uint8_t) = ~1200 byte mem increase
> Shutdown threads in a graceful way

- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
This PR can fix some of the R2R issue that were caused by using uninitialized array in av1_make_masked_inter_predictor() function for chroma compound with COMPOUND_DIFFWTD flag
Github Issue: #733
> Address valgrind errors that could cause R2R issue and fix print message

- .github/workflows/ci.yml
Extended binary identical test behavior to checkout the target branch upon pull request. Previously, CI compares against the official repository's master independent of the target branch. The change will behave as follows now:
- On pull request event, checkout the target branch
- On push event, checkout master. I removed the option that checks out the official repository's master. For forked projects, users may not want to compare against the official repo's master. It would be better to keep the behavior this way. Open for discussion if there are disagreements on this.
Sanity checks:
Push: https://github.com/ultrawide/SVT-AV1/pull/4/checks?check_run_id=496160708 
Pull Request: https://github.com/ultrawide/SVT-AV1/pull/4/checks?check_run_id=496172549 
Closes #1098
> CI: Extend binary identical test to checkout target branch for pull request

- Source/Lib/Common/Codec/EbObject.h
- Source/Lib/Common/Codec/EbSystemResourceManager.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
In eb_object_wrapper_ctor, if object_creator failed, object_destroyer assignment is lost.
when eb_object_wrapper_dctor is called, object_destroyer is not being called, instead EB_DELETE
which crashes.
> Fix crash during res release if res failed to allocate

- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
global motion gm_down case gets bitstream corruption for global motion MV may be out of range after upscale by 2 in mode decision part, adding global motion MV range clamping change to fix this issue.
> fixed gm_down bitstream corruption issue

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
- Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.h
- Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Codec/EbTemporalFiltering.h
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- Added plane wise tf.
- Added the ability to use 32x32 MVs, and the ability to switch between using 16x16 MVs or 32x32 MVs.
- Tuned tf settings.
- Optimized  10BIT packing @ tf.
| -- | --
| ~0% | -0.8%|
> Enhanced tf

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- clean up the  inter intra compound control signals. turning on/off  could be done via 2 ways: at the seq level(in ressource coordination), or at the picture level (in picture decision)
- add control to search smaller number of references i both ME and MD.
> mrp and inter-intra clean ups

- appveyor.yml
Fixes appveyor failing due to pacman not installing gcc
> appveyor: run pacman update along with installing packages

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Contains 2 cases
- When skiping stage1/2, the full cost is used directly without been
initialized
- At the boundary when it's not a complete super block. We may only
use part of the blocks in MD and didn't set its parent blocks
properly. it will generate the wrong CDF context for the next SB
> Fix the r2r

- Source/Lib/Encoder/Codec/EbCodingUnit.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
This feature consists of skipping depth +1 when the cost of the square partition is better than the cost of the non-square partitions in the current depth. This feature is enabled only for screen content.
* BDrate: 0.55%
* Speed: 19%
* Memory: 0%
InputSequence | Resolution | Bdrate PSNR-YUV | Bdrate SSIM-YUV | Encoding time   deviation
MINECRAFT_60f_420 | 1920x1080 | 0.37% | 0.35% | 3.85%
SlideEditing_1280x720_30_60f | 1280x720 | 0.45% | 0.54% | 27.45%
SlideShow_1280x720_20_60f | 1280x720 | 0.45% | 0.70% | 32.75%
wikipedia_420 | 1920x1080 | 0.67% | 0.86% | 12.55%
  | Average | 0.49% | 0.61% | 19.15%
> Skip depth optimisation

- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
In includes 4 part changes below:
1, to set int32_t recon_offset in half pixel spatial_full_distortion_kernel()
Found it gets crash in a special case  for invalid memory access in function spatial_full_distortion_kernel() function, and root cause the input big recon_offset value does not reasonable, actually it’s a minus value and converted to be unsigned int, which makes it taken as very big value, this error is not fatal for it does not always access invalid memory;
2, to initialized context_ptr->p_sb_best_mv[] in beginning of function motion_estimate_sb()
Found the ME output MVs always get r2r and something the MV value could be very big, then checked the ME module and found this overlay test is very special, it generates search_window size 0x0 of one block in full pixels searching …
> Fix r2r for -enable-overlays cases

- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
Test command:
SvtAv1EncApp -i test.y4m -intra-period 31  -b test.ivf  -n 200
It will print out:
"Bug, too many frames in undisplayed queue"
Root cause:
The overlay frame is not a show_existing frame, it will carry a pts.
So we do not need to push it's counterpart(alt ref frame) to undisplayed queue.
> EbPacketizationProcess: do not push alt ref frame to undisplayed queue

- Source/App/DecApp/EbFileUtils.c
When reading Annex-B OBUs in obudec_read_temporal_unit, when reading
a frame unit size of 0, it would call realloc with 0, which has not
well defined behavior.
> EbFileUtils: fix handling of a 0 frame unit size

- Source/Lib/Encoder/Codec/EbMotionEstimation.c
This case should never happen, add an assert to ensure it would be
easier detected if it happens in debug builds.
Additionally this might help the static analyzer to figure out that
this does not normally happen.
> EbMotionEstimation: add assert in default case

- Source/Lib/Encoder/Codec/EbEntropyCoding.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Issue #733 
This PR fixes:
```
at 0x504AE27: mode_decision_update_neighbor_arrays (EbProductCodingLoop.c:107)
by 0x504BD5F: md_update_all_neighbour_arrays (EbProductCodingLoop.c:743)
by 0x504BDEF: md_update_all_neighbour_arrays_multiple (EbProductCodingLoop.c:762)
by 0x50590B2: mode_decision_sb (EbProductCodingLoop.c:8433)
by 0x4FD3D3F: enc_dec_kernel (EbEncDecProcess.c:3104)
by 0x5EA5DD4: start_thread (in /usr/lib64/libpthread-2.17.so)
by 0x64B9EAC: clone (in /usr/lib64/libc-2.17.so)
Use of uninitialised value of size 8
at 0x504AFA5: mode_decision_update_neighbor_arrays (EbProductCodingLoop.c:164)
by 0x504BD5F: md_update_all_neighbour_arrays (EbProductCodingLoop.c:743)
by 0x504BDEF: md_update_all_neighbour_arrays_multiple …
```
> valigrnd fix for mode_decision_update_neighbor_arrays

- Source/Lib/Encoder/Codec/noise_model.c
These commits fix a warning by the clang static analyzer about a possible double-free in noise_model.c
> Correctly use NULL for pointers in AomEquationSystem

- Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
Helps to catch bugs in debug builds, as those would cause div by
0 further in the code.
Additionally helps guide the static analyzer to know those are not
supposed to be 0 and silences the div by 0 warnings.
> EbPictureAnalysisProcess: assert sizes larger than 0

- Source/App/EncApp/EbAppConfig.c
Even on Windows in the terminal a binary can be run without
the .exe suffix
> SvtAv1EncApp: Remove .exe suffix from usage

- test/PackUnPackTest.cc
UT is failing for example here: https://github.com/OpenVisualCloud/SVT-AV1/pull/1154/checks?check_run_id=566794496
I can reproduce it on windows, visual studio 2019 Debug build with error:
```
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
```
Root cause is that test allocate too small input buffer
> Fix UT, read outside of allocated memory

- test/e2e_test/ConfigEncoder.cc
- test/e2e_test/ConfigEncoder.h
- test/e2e_test/E2eTestVectors.h
- test/e2e_test/SvtAv1E2EFramework.cc
1. add print cli string when e2e test case failure, to help re-produce issue in SvtAv1EncApp
e.g. RcTest6 failed! to print:
cli command: SvtAv1EncApp -i kirland_640_480_30.yuv -w 640 -h 480 -bit-depth 8 -colour-space 420 -rc 1 -tbr 500000 -b output.ivf -o recon.yuv
> Add print CLI of SvtAv1EncApp when E2E test case failure

- Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
Fix issue #733
_mm256_loadu_si256 (avxintrin.h:921)
load_buffer_32x32_new (highbd_inv_txfm_avx2.c:1760)
highbd_inv_txfm2d_add_h_identity_avx2 (highbd_inv_txfm_avx2.c:6194)
highbd_inv_txfm_add_8x16 (EbInvTransforms.c:3193)
highbd_inv_txfm_add (EbInvTransforms.c:3423)
av1_inv_transform_recon (EbInvTransforms.c:3495)
av1_encode_generate_recon_16bit (EbCodingLoop.c:1332)
perform_intra_coding_loop (EbCodingLoop.c:1726)
av1_encode_pass (EbCodingLoop.c:2580)
> Fix valgrind error for highbd_inv_txfm2d_add_h_identity_avx2

- Source/Lib/Common/ASM_AVX2/cfl_avx2.c
- Source/Lib/Common/Codec/EbCabacContextModel.c
- Source/Lib/Common/Codec/EbCabacContextModel.h
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/common_dsp_rtcd.c
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Decoder/Codec/EbDecIntraPrediction.c
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/palette.c
- test/intrapred_cfl_test.cc
1. kernel implementation with UT for:
- cfl_luma_subsampling_420_hbd_avx2 speedup ~3.4x comapred to C
- cfl_luma_subsampling_420_lbd_avx2 speedup ~3.1x comapred to C
2. Modification of:
- av1_get_palette_color_index_context (speedup ~10% compared to previous implementation)
> AVX2 kernel implementation

- .github/workflows/cppcheck.yml
This adds static analysis using [cppcheck](http://cppcheck.sourceforge.net) and creates annotations that show up in the job information. Additionally if a PR introduces new errors, those should show up inline in the diff.
Fix #1161
> CI: Add simple cppcheck job

- CMakeLists.txt
`project_name` is usually set by the project command
`CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR` are defined
by `GNUInstallDirs`
setting `CAN_USE_ASSEMBLER` doesn't do anything
`CMAKE_INCLUDE_CURRENT_DIR` isn't necessary atm.
> CMakeList: Remove unnecessary code

- Source/API/EbSvtAv1Dec.h
- Source/API/EbSvtAv1Enc.h
- Source/App/DecApp/EbDecAppMain.c
- Source/App/EncApp/EbAppContext.c
- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
- gstreamer-plugin/gstsvtav1enc.c
- test/api_test/SvtAv1EncApiTest.cc
- test/api_test/SvtAv1EncParamsTest.cc
- test/e2e_test/ConfigEncoder.cc
- test/e2e_test/SvtAv1E2EFramework.cc
sending this PR primarily for gathering feedback on API namespacing, I do not
actually expect it to be merged in its current form.
SVT-AV1 currently uses `eb_` as the prefix for public functions, but I see
multiple problems with it:
-    it is used across several separate projects, causing symbol conflicts
-    it is used for both public and private functions, making it harder to
distinguish between them
-    as far as I can tell, it's used mainly for historical reasons and it does
not carry much meaning for the API users
Since the library API is not stable yet, these problems can still be addressed
without breaking compatibility. It thus seems reasonable to pick a prefix that
would be
-    meaningful for the end-users
-    unique for SVT-AV1
-    used for public functions only (it would …
> [RFC] consistent namespacing for public API functions

- test/PackUnPackTest.cc
1. fix the allocate size of inn_bit_buffer_, issue of reading out of the bound:
~~~
[----------] 1 test from PACKMSB/PackMsbTest
[ RUN      ] PACKMSB/PackMsbTest.PackMsbTest/5
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[  FAILED  ] PACKMSB/PackMsbTest.PackMsbTest/5, where GetParam() = (64, 32) (1 ms)
[----------] 1 test from PACKMSB/PackMsbTest (1 ms total)
~~~
2. clean-up code to make easier to read
link to failed tests:
https://github.com/OpenVisualCloud/SVT-AV1/runs/574829610
https://github.com/OpenVisualCloud/SVT-AV1/runs/572231314
https://github.com/OpenVisualCloud/SVT-AV1/runs/572210176
> Fix bug in PackMsbTest

- README.md
- Source/Lib/Common/Codec/EbThreads.c
Instead of using named semaphores, use dispatch semaphores. Those are not based on files so this solves the issue of needing a huge number of file descriptors on macOS.
> Use dispatch semaphores on Darwin

- Source/App/EncApp/EbAppContext.c
- Source/App/EncApp/EbAppContext.h
Since nothing was using the `stream_buffer_pool`, it would be better to remove it for now, plus anyone needing it can grep it from the git log.
There seem to be a lot of variables that are generally unused it seems.
> EncApp/EbAppContext.c: Remove call for allocate_output_buffers

- CMakeLists.txt
Instead of special-casing some generators here, instead check the
CMAKE_CONFIGURATION_TYPES variable, if that is set it means the
generator has its own choices for build types and does not need the
CMAKE_BUILD_TYPE. Else default the build type to release, like before.
See https://blog.kitware.com/cmake-and-the-default-build-type/
> CMake: Default build type to Release if needed

- Source/Lib/Common/Codec/EbRestoration.h
- Source/Lib/Decoder/Codec/EbDecInterPrediction.c
- Source/Lib/Decoder/Codec/EbDecRestoration.c
Bug fix related to Dec LR temp buffer
Bug fix related to 16bit_pipeline in Dec InterPrediction
This fixes Issue https://github.com/OpenVisualCloud/SVT-AV1/issues/1215
> Decoder bug fix related to LR temp buffer and 16bit_pipeline

- Source/Lib/Encoder/Codec/EbPredictionStructure.c
The eb_memcpy is a function pointer to NULL which is only initialized
after a call to setup_common_rtcd_internal, which is not done yet
when this is called.
Fix #1216
This issues might be present in other cases, this code is a bit messy and the way those pointer are initialized being done in `setup_common_rtcd_internal` is really weird…
Even more confusing that there is `EB_MEMCPY` which does not do the same as `eb_memcpy` with regard to which implementation is called…
(It was introduced in #1155 where some `EB_MEMCPY` were replaced with `eb_memcpy`)
> Fix calling NULL pointer

- snap/snapcraft.yaml
The magic version 'git' will be replaced with the git describe string
as per the snapcraft.yaml documentation:
https://snapcraft.io/docs/snapcraft-yaml-reference
> Snap: Use 'git' as version

- Source/App/EncApp/EbAppConfig.c
Fixes a small command line documentation forgotten when scm was defaulted to 0 in #1005.
> Docs: Tell correct SCM default mode in EbAppConfig.C

- Build/linux/build.sh
Arguments weren't shifted properly for single dash options that used an argument
> build.sh: fix an issue in arg splitting

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
previous code assumes raw frame size > tu size, it's not true.
A tu may include multiple undisplayable frames + one displayable frame.
So for some complex video pattern, a tu size may > multiple raw frame size.
Instead of using raw frame size as ffmpeg buffer size, This commit will
automatically adjust ffmpeg buffer size based on libsvtav1's output
test:
dd if=/dev/urandom bs=115200 count=30 of=test.yuv
ffmpeg -f rawvideo -vcodec rawvideo -s 320x240 -r 30 -pix_fmt yuv420p -i test.yuv -c:v libsvt_av1 -f ivf -y test.ivf
expected result:
no crash.
> ffmpeg: fix memory overwrite for complex video content

- Source/Lib/Common/ASM_AVX2/wiener_convolve_avx2.c
- Source/Lib/Common/ASM_AVX512/wiener_convolve_avx512.c
- Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
- Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.h
- Source/Lib/Encoder/ASM_AVX512/pickrst_avx512.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- Source/Lib/Encoder/Globals/EbEncHandle.c
- test/RestorationPickTest.cc
- test/wiener_convolve_test.cc
Fixed kernels:
-eb_av1_compute_stats_avx2
-eb_av1_compute_stats_highbd_avx2
-eb_av1_compute_stats_avx512
-eb_av1_compute_stats_highbd_avx512
-eb_av1_wiener_convolve_add_src_avx2
-eb_av1_wiener_convolve_add_src_avx512
> Fix for AVX2/AVX512 kernels when non-multiple of 8 resolution is used

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbMcp.c
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbReferenceObject.c
- Source/Lib/Encoder/Codec/EbReferenceObject.h
- Source/Lib/Encoder/Codec/EbResize.c
- Source/Lib/Encoder/Codec/EbResize.h
- Source/Lib/Encoder/Codec/EbRestProcess.c
- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Implementation of the following features at the encoder side:
- Scaling and super-resolution of inter pictures (intra was already supported)
- Reference scaling
- Clean-up of av1_inter_prediction() to align scaled and unscaled reference path
If -superres-mode 0 (default), bitstreams should match the master branch.
> Super-resolution support for inter pictures

- Source/Lib/Common/ASM_SSE2/EbPictureOperators_SSE2.asm
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Common/Codec/EbUtility.c
- Source/Lib/Common/Codec/EbUtility.h
- Source/Lib/Common/Codec/common_dsp_rtcd.c
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbDeblockingFilter.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbNeighborArrays.c
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbRestProcess.c
- Source/Lib/Encoder/Codec/EbSegmentation.c
in M1 kirkland (#1257)"
uint Log2 should return 0 for arg 0.
Fixes #1261 
Protecting kernel Log2f_ASM() will return 0 when argument is 0.
In argument always sets first bit, to not get undefined behavior from asm bsr.
Results not changes for values different that 0.
> Fix log2f, and revert "Revert log2f changes due to rate loss

- .travis.yml
It seems that it was disabled in https://github.com/OpenVisualCloud/SVT-AV1/commit/6bc9f229d21e4803961a63ce469ffb80c29add0a
> Travis: Re-enable travis-ci for pull requests

- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
update_mi_map (EbAdaptiveMotionVectorPrediction.c:1517)
md_update_all_neighbour_arrays (EbProductCodingLoop.c:748)
md_update_all_neighbour_arrays_multiple (EbProductCodingLoop.c:764)
mode_decision_sb (EbProductCodingLoop.c:8726)
enc_dec_kernel (EbEncDecProcess.c:3436)
inject_new_candidates (EbModeDecision.c:3855)
inject_inter_candidates (EbModeDecision.c:4429)
generate_md_stage_0_cand (EbModeDecision.c:5998)
md_encode_block (EbProductCodingLoop.c:7470)
mode_decision_sb (EbProductCodingLoop.c:8584)
enc_dec_kernel (EbEncDecProcess.c:3436)
> Fix valgrind issue for: -w 640 -h 480 -enc-mode 8 -scm 1 -palette 3

- Docs/svt-av1_encoder_user_guide.md
- Source/App/DecApp/EbDecAppMain.c
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Suppresses the backspaces and frame count printing that sucks when trying to parse the output
Currently needs to be enabled by way of `--no-progress <anything>`  due to the limitation of the current arg parsing system
Semi Closes #1237
> App: Add --no-progress option 

- Source/Lib/Encoder/Codec/EbMdRateEstimation.c
For Debug build with command line below assert is called
cmdline: 176x144.yuv -w 176 -h 144 -bit-depth 8 -enc-mode 0 -n 40 -b out.av1
@ePirat could you confirm that this is fixed correctly? (assert is introduced in PR #1260 )
> Fix wrong parameter for assert, 0 is valid

- Source/Lib/Encoder/Codec/EbMotionEstimation.c
NxM SAD is calculated between the current super block buffer and its
corresponding referenced one (in reconstructed picture) for O/A/B/C/D
positions.
Ported from SVT-HEVC PR #530.
Signed-off-by: Austin Hu <austin.hu@intel.com>
> Update the Y sample buffer indexing for position A in Motion Estimation.

- Source/Lib/Encoder/Globals/EbEncHandle.c
The macro "MRP_31B_SUPPORT" is removed in EbDefinition.h (enabled by default), so remove it here.
When I submit the previous PR #1265 (31B hang related) for review, the macro is there.
When merging the PR #1265, the macro is removed by some other PR , so it will still hang for 31B
> Remove the macro for 31B

- Source/App/EncApp/EbAppMain.c
- Source/Lib/Common/Codec/EbThreads.h
On nix systems with mingw-w64, gcc will error out on `Windows.h` since they do not do case insensitive include search
> EbAppMain, Ebthreads: use lowercase windows.h for case sensitive systems

- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Speedup encoder, remove round() on double.
For cmd line below:
```
-i 1920x1080_60fps_420_8bit.yuv -enc-mode [mode] -w 1920 -h 1080 -bit-depth 8 -fps 60 -b out.ivf
```
Encoding speedup:
 Mode | master[fps] | Changes[fps] | speedup[%]
-- | -- | --| --
M8 | 18,953 | 19,659|3.73
M7 | 11,672 | 11,986|2.69
M6 | 10,454 | 10,761|2.94
M5 | 5,615 | 5,669|0.96
M4 | 3,745 | 3,786|1.09
M3 | 2,483 | 2,511|1.13
M2 | 0,32 | 0,321|0.31
M1 | 0,051 | 0,052|1.96
M0 | 0,037 | 0,037|0.00
> Optimize performance reduce round() on double to int

- .github/workflows/ci.yml
- Source/Lib/Common/Codec/EbThreads.h
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Decoder/Codec/EbDecParseObu.c
- Source/Lib/Decoder/Codec/EbDecProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- Source/Lib/Encoder/Globals/EbEncHandle.c
Closes #999
The issue is caused by the fact that `aom_dsp_rtcd.h` includes `common_dsp_rtcd.h`, and use the same define to trigger using `extern`, causing `aom_dsp_rtcd.o` to have the same function pointers as `common_dsp_rtcd.o`
> GCC10: Fix issues related to common symbols

- .travis.yml
Yesterday GCC 10.1 was [migrated](https://tracker.debian.org/news/1143538/gcc-10-1010-1-migrated-to-testing/) to [Debian Testing](https://tracker.debian.org/pkg/gcc-10), which makes updating the CI fairly simple.
Use GCC 10 with the build jobs on Arm64, PowerPC and IBM Z, as well as with the Valgrind job.
The PowerPC jobs produces some new notes (light warnings) with GCC 10, other than that all runs pass.
> Travis CI: Move to GCC 10

- Source/Lib/Common/Codec/ConfigureGitVersion.cmake
git describe only supports `--broken` if git's version is greater than 2.13.7, else it will print out
```none
Failure to get version from Git: error: unknown option `broken'
usage: git describe [<options>] [<commit-ish>...]
or: git describe [<options>] --dirty
...
<rest of git describe -h>
```
> ConfigureGitVersion: Remove --broken

- Source/Lib/Common/Codec/EbMcp.c
- Source/Lib/Common/Codec/EbMcp.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.h
- Source/Lib/Encoder/Codec/EbPsnr.c
This PR fixes three inconsistent implementation.
1. Fix column range in psnr_calculations. It does not make sense to use `input_picture_ptr->width - scs_ptr->max_input_pad_bottom`
2. Fix ptr in highbd_variance64. This function is fed with `CONVERT_TO_BYTEPTR(uint16_t*)` pointers. The highbd_variance64 function uses `(uint16_t*)` cast, while the corresponding avx2 implementation uses`CONVERT_TO_SHORTPTR(uint8_t*)`.
3. Fix rec/dec mismatch when encoding hbd non 8-aligned video, which was caused by the improper padding when hbd
> Fix inconsistent code

- .github/workflows/ci.yml
This adds werror to all builds and wno-error=array-bounds for clang to match up with Travis.
> CI: Error on warnings

- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- test/TemporalFilterTestPlanewise.cc
Speedup compared to C implementation ~3x
For cmd line below:
```
-i 1920x1080_60fps_420_8bit.yuv -enc-mode [mode] -w 1920 -h 1080 -bit-depth 8 -fps 60 -b out.ivf
```
Encoding speedup:
  | Changes[fps] | master[fps]
-- | -- | --
M8 | 18.094 | 16.386
M7 | 11.487 | 11.131
M6 | 10.304 | 10.057
M5 | 5.546 | 5.491
M4 | 3.756 | 3.721
M3 | 2.456 | 2.418
M2 | 0.322 | 0.322
M1 | 0.052 | 0.052
M0 | 0.037 | 0.037
> Enable svt_av1_apply_temporal_filter_planewise_avx2 kernel

- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
altref_strength is defined as unsigned integer, but it can be calculated as negative (-1) if in the case that low QP (<=20) and --altref-strength is set to 1 or 0
> fix a bug of altref_strength calculation

- Source/API/EbSvtAv1.h
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbRestProcess.c
Most other encoders support SSIM along with PSNR as a compression quality metric. For our use of SVT-AV1 we depend on having SSIM readily available, so we have added support for this to SVT-AV1. It supports both 8- and 10-bit bitdepth. However, we do not have any videos in the "compressed 10-bit format" utilized by SVT-AV1, nor any tools to convert to it, and due to SSIM being a little more complex for this format, it has not yet been added. Still, we are submitting this pull request hoping it will generate some interest. 
If someone can share some sample "compressed 10-bit format" test videos, or advice how to convert to this format, we should be able to complete this pull request soon.
We utilize core SSIM calculation functions from 'aom' in this pull request, since other parts of aom …
> Add support for SSIM

- .ci/ci.sh
- .github/workflows/macos.yml
1. add unit test and e2e tests in MacOS CI
2. modified ci.sh to run without root
For self-hosted runner in GitHub CI workflow, please refer to offical guide:
https://help.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
> Add unit tests and e2e tests for MacOS CI

- Config/Sample.cfg
- Docs/svt-av1_encoder_user_guide.md
- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
And fix wrong description of "Asm" parameter.
> Fix parameter name "AsmType" to "Asm" in Encoder User Guide.

- Docs/svt-av1_encoder_user_guide.md
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppMain.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Closes #1271
Closes #441 
Removed `--scd` since it was broken for a long time
Changed printed out help text to double dash
Corrected asm help text in the encoder guide along with replacing single dash long options with their correct ones
> EbAppConfig: Support double dashes for hme 

- .github/pull_request_template.md
- CONTRIBUTING.md
- Update the PR template to standardize the PR description
- Add PR guidelines to the Contributing.md doc
As discussed in #1283 
@hassount 
@1480c1
> Update PR template and the PR contributing guidelines

- Config/Sample.cfg
- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
set unpin to 1 by default to not restrict the execution in 1 core when -lp1 and update documentation accordingly
> Set unpin to 1 by default

- CMakeLists.txt
Add `/W3` to the C and CXX flags for MSVC based builds
Also testing out how #1320 would look like
Fixes #131 
@1480c1
> CMake: Set W3 for MSVC

- Source/App/EncApp/EbAppContext.c
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
`n_alloc_len` is now set dynamically rather than the hardcoded values.
Resolves issues when encoding a high-resolution input with a low QP value by dynamically reallocating the buffer.
@xuguangxin, @EricLamVCD 
Resolves #1136
Resolves #1174
@mazharaIntel 
@1480c1
> size of n_alloc_len changes based on bitstream count

- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Fix a large number of compiler warnings when compiling tests due to non-const compile-time constants.
Marvin Scholz
> Fix compiler warnings

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
fix build for the latest ffmpeg code.
the build is broken by the following commit in ffmpeg
build failed since following commit in ffmpeg
commit 6e1903938befc0bce2f64e01770af2f65d625cfc
Author: James Almer <jamrial@gmail.com>
Date:   Tue Jun 2 18:38:33 2020 -0300
avcodec/internal: move packet related functions to their own header
Signed-off-by: James Almer <jamrial@gmail.com>
commit 6e1903938befc0bce2f64e01770af2f65d625cfc
Author: James Almer <jamrial@gmail.com>
Date:   Tue Jun 2 18:38:33 2020 -0300
avcodec/internal: move packet related functions to their own header
Signed-off-by: James Almer <jamrial@gmail.com>
NO
Xu Guangxin <guangxin.xu@intel.com>
> ffmpeg: fix build for missing packet_internal.h

- .github/workflows/cppcheck.yml
- CMakeLists.txt
Modified to only enable `ASM_NASM` language if x86 since nasm is not needed on non-x86 platforms
Add `ENABLE_NASM` variable to forcefully tell cmake to check nasm instead
Add a version check for nasm and error out if nasm is less than 2.14 and yasm is not found.
current flow:
1. find yasm
2. check if (yasm_found && ! CMAKE_ASM_NASM_COMPILER ~= "yasm" && !`ENABLE_NASM`) and sets yasm as the assembler
3. else it will let cmake detect a default assembler (usually nasm) and check the version and compare to 2.14, if it's less and the assembler is nasm, it will error out
Closes #1248
Closes #1330 
@1480c1
> CMake: Add error checking for nasm version, use ENABLE_NASM, don't check for nasm if non-x86

- Source/Lib/Common/ASM_SSE2/EbAvcStyleMcp_Intrinsic_SSE2.c
- Source/Lib/Common/ASM_SSE2/EbAvcStyleMcp_SSE2.h
- Source/Lib/Common/ASM_SSSE3/EbAvcStyleMcp_Intrinsic_SSSE3.c
- Source/Lib/Common/ASM_SSSE3/EbAvcStyleMcp_SSSE3.h
- Source/Lib/Common/Codec/EbAvcStyleMcp.c
- Source/Lib/Common/Codec/EbAvcStyleMcp.h
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- test/AVCStyleMcpTest.cc
**UPDATE**: This PR was updated to remove the skip parameter, see discussion. This makes the issue detailed below obsolete.
There is a tautology in the `avc_style_luma_interpolation_filter_posj_ssse3` function:
```
if (skip)
avc_style_luma_interpolation_filter_horizontal_ssse3_intrin(ref_pic - src_stride,
src_stride,
temp_buf,
pu_width,
pu_width,
(pu_height + 3),
0,
EB_FALSE,
2);
else
avc_style_luma_interpolation_filter_horizontal_ssse3_intrin(
ref_pic - src_stride,
src_stride,
temp_buf,
pu_width,
pu_width,
skip ? (2 * pu_height + 3) : (pu_height + 3),
0,
EB_FALSE,
2);
```
If `skip` is true, the first branch is taken, calls `avc_style_luma_interpolation_filter_horizontal_ssse3_intrin` with `(pu_height + 3)`.
If `skip` is false, the second branch is taken, calls …
> Cleanup: Remove always false skip arguments

- Source/Lib/Common/Codec/EbDefinitions.h
EbDefinitions has a weird redefinition of asserts that cause asserts
to not work at all when EbDefinitions was included after assert.h
or if only EbDefinitions was included but no assert.h, without
any warning.
This removes the code completely as it is completely unnecessary and
highly misleading to mess with C library provided macros.
Marvin Scholz
> EbDefinitions: Do not disable all assertions

- .github/workflows/mingw-w64.yml
- CONTRIBUTING.md
- README.md
- appveyor.yml
Moves over the appveyor job to github actions
Tests mingw-w64 compilation along building FFmpeg with libdav1d as well
the resulting ffmpeg.exe binary is uploaded too.
@ePirat @luigi311 @EwoutH can you guys help review this?
@1480c1
> Actions: Add a mingw-w64+ffmpeg & Remove appveyor

- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=827d6fe73d2f5472c1c2128eb14fab6a4db29032 changed the internal encode API, as as such the ffmpeg plugin needs to be adapted.
Without this change, the plugin will fail to build starting with lavc version 58.93.100
James Almer
> ffmpeg: Adapt with new libavcodec internal encode api changes

- CMakeLists.txt
- Source/API/EbSvtAv1.h
- Source/Lib/Common/Codec/EbBitstreamUnit.c
- Source/Lib/Decoder/Codec/EbDecHandle.c
- Source/Lib/Decoder/Codec/EbDecParseObu.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
if we enable libaom and libsvtav1 at same time in ffmpeg like this
`./configure --enable-libsvtav1 --enable-libaom`
it will report error:
```
libSvtAv1Enc.so: warning: multiple common of `aom_obmc_variance32x32'
libaom.a(aom_dsp_rtcd.c.o): warning: previous common is here
libSvtAv1Enc.so: warning: multiple common of `av1_build_compound_diffwtd_mask'
libaom.a(av1_rtcd.c.o): warning: previous common is here
```
The root cause is we reuse some functions in libaom. Make it hidden by default will fix the issue
> fixes symbols conflict with libaom. 

- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Common/Codec/EbSystemResourceManager.c
- ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
enable tile in ffmpeg plugin 
fixes https://github.com/OpenVisualCloud/SVT-AV1/issues/482
ffmpeg -i input.264 -c:v libsvt_av1  -tile-columns 2 -tile-rows 2 out.ivf -y
> ffmpeg: add tile support

- .github/workflows/releases.yml
Packs `SvtAv1DecApp.exe`, `SvtAv1EncApp.exe`, and `SvtAv1Enc.lib` into their own zip files, which should be okay to do since windows has some native ways to unzip
Closes #1346
> Releases: pack releases using zip

- Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c
- Source/Lib/Common/ASM_SSE4_1/highbd_inv_txfm_sse4.c
- Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c
- Source/Lib/Encoder/ASM_AVX512/pickrst_avx512.c
Port AOM commits that fix SIMD kernels.
Commit list :
1. 6e61c8e4b " av1/encoder/x86/pickrst_sse4: fix int sanitizer warnings"
2. d2d6931c3 "encoder/x86/pickrst_avx2: fix int sanitizer warnings"
3. 0c1b245c2 "Fix bug in highbd inv txfm modules"
4. 77c7dc997 "Fix bug in highbd_inv_txfm modules"
5. 3563b12b7"avx2 dr prediction valgrind bug fix"
6. 4ee28caaf  "avx2 dr prediction z2 valgrind issue fix"
7. d8ea9e621 "avx2 dr prediction z2 valgrind issue fix"
8. 1b752e73a "Uninitialized memory bug correction"
9. d6ace9219 "Uninitialized memory bug correction"
I checked both 8 and 10 bit video and speed is similar to master
@tszumski
> Task port aom simd commits

- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Encoder/ASM_AVX2/EbRestorationPick_AVX2.c
- Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c
- Source/Lib/Encoder/ASM_SSE4_1/EbTemporalFiltering_highbd_sse4.c
- Source/Lib/Encoder/ASM_SSE4_1/EbTemporalFiltering_sse4.c
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbDeblockingFilter.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbEntropyCoding.c
- Source/Lib/Encoder/Codec/EbFullLoop.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbNeighborArrays.c
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
Fixes some variableScope and unreadVariable issues
once I get confirmation that this pr is lossless, I will squash the commits.
@1480c1
> cppcheck5: variableScope & unreadVariable

- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Add protection when tile is enbaled and enc_dec segment number is reduced
Fixes #1276
@tszumski
> Add protection when tile is enbaled and enc_dec segment number is reduced

- gstreamer-plugin/gstsvtav1enc.c
use GST_ELEMENT_ERROR message macro for GST_FLOW_ERROR
closes #521 
@tianjunwork
> Use GST_ELEMENT_ERROR macro for GST_FLOW_ERROR

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Adoptions of fixes for R2R in 10bit from svt-01 branch
#define FIX_HBD_R2R         1 // Fix 10bit error in over-boundaries CUs (incomplete SB)
After apllying this PR there is no R2R in objective-2-slow
For command line (from issue #1312):
```
SvtAv1EncApp.exe -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv -b out.av1 -bit-depth 10 -n 100 -enc-mode 8 -lp 8
```
R2R still persist
#1312
> Adoptions of fixes for R2R in 10bit from svt-01 branch

- Source/Lib/Encoder/Codec/EbRateControlProcess.c
Fix valgrind error for command line (-enc-mode: 8, 7, 6, 5, 4, 3, 2):
```./SvtAv1EncApp -lp 8 -i /root/mount_nvme/kirland_640_480_30.yuv -w 640 -h 480 -enc-mode 8 -rc 2 -tbr 1000 -fps 60 -n 17 -b tbr-kirland0.ivf 2>vg-tbr-kirland0.log```
Invalid read of size 4
at 0x50193AA: frame_level_rc_input_picture_cvbr (EbRateControlProcess.c:2942)
by 0x501BE86: rate_control_kernel (EbRateControlProcess.c:5493)
by 0x5E57EA4: start_thread (in /usr/lib64/libpthread-2.17.so)
by 0x646C8DC: clone (in /usr/lib64/libc-2.17.so)
Address 0x3bebefb8 is 0 bytes after a block of size 2,456 alloc'd
at 0x4C2B955: calloc (vg_replace_malloc.c:711)
by 0x5014DE2: rate_control_context_ctor (EbRateControlProcess.c:392)
by 0x4F6A626: svt_av1_enc_init (EbEncHandle.c:1562)
by 0x114A24: init_encoder (EbAppContext.c:453)
by …
> Fix valgrind for -tbr param

- .travis.yml
Temporarily allow the IBM Z job to fail on Travis CI. 
Succeeds #1394 and unblocks #1393.
@EwoutH
> Travis CI: Allow failures on IBM Z job

- Source/App/EncApp/EbAppInputy4m.c
- Source/App/EncApp/EbAppInputy4m.h
- Source/App/EncApp/EbAppProcessCmd.c
Fix error when -n > number of frames in y4m
```
Failed to read proper y4m frame delimeter. Read broken.
```
Fixes #1285 
@tszumski
> Fix read when -n > number of frames in y4m

- .travis.yml
Makes valgrind exit with an error code of 1 if it catches an error
@1480c1
> valgrind: Add an exit code if it is failing

- Source/Lib/Encoder/Codec/EbPredictionStructure.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
bug occurrence conditions：
when command line set parameter："-pred-struct-file", or Sample.cfg set parameter "PredStructFile", the crash will coming！
bug fixed：
when code coming to the two crash points，the eb_memcpy has been not setted，so should using  function memcpy to instead of function eb_memcpy.
> fix bug for two crash！

- .github/workflows/macos.yml
Fixes an issue in the CI where the build would fail because bazelisk and the preinstalled bazel conflicted.
@1480c1
> macOS: Remove bazel

- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
This PR addresses issue #1382 where I got a seg fault whenever I set wedge_mode to be 2. This was due to the fact that wedge_index was not picked in this mode. After looking into the implementation in libaom, I noticed that after estimating the wedge_sign, wedge index with fixed sign was picked. It can be found [here](https://aomedia.googlesource.com/aom/+/refs/heads/master/av1/encoder/compound_type.c#321)  
So this fix was just adding this function.
Fixes #1382 
@nasirhemed
> Add pick_wedge_fixed_sign after estimating wedge_sign

- .github/workflows/macos.yml
make sure we are using the correct binaries for the unit tests in the case where we do not have the same environment as the one that built it, use parallel instead of xargs instead to handle multi-process, and don't clean the directory so we can save time recompiling
@1480c1
> macOS: use upload and download artifact to make sure it uses the same binaries

- .github/workflows/mingw-w64.yml
- .github/workflows/patches.yml
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbTransforms.c
- Source/Lib/Encoder/Codec/EbTransforms.h
311be07bbcafc4e46679fb8d1e578cfb4d7e25c9 introduced a function that conflicts with a function in libvpx, this renames it and adds libvpx to the list of libraries compiled with FFmpeg to catch any conflicts.
@1480c1
> Libvpx: Fix conflicts with libvpx and add it to GitHub Actions

- .github/workflows/patches.yml
libvpx seems to be failing because I forgot to add sudo -E before the configure line
@1480c1
> Patches: Add sudo to prevent permission issues

- Source/Lib/Common/Codec/EbThreads.c
sem_wait will interrupted by singals, like Ctrl-C.
In this case, eb_get_full_object/eb_get_empty_object wakeup with zero object in queue.
It will crash the application
Test steps:
1. run ./ffmpeg -i input.264 test.ivf -y
2. wait sometime to make sure encode is started.
3. press Ctrl+C
Expected:
No crash
> fix crash on Ctrl+C [WIP]

- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Codec/corner_match.c
- test/convolve_2d_test.cc
1. Move some calculation before function call
2. Fix calling C kernel while avx2 version is available 
3. Fix unit test for AVX512 code
Speedup:
8bit M8 0,19%
8bit M6 0,09%
8bit M4 -0,29%
8bit M2 0,63%
8bit M0 0,00%
10b M8 2,73%
10b M6 3,41%
10b M4 0,78%
10b M2 0,85%
10b M0 0,64%
@tszumski
> Small speed improvement

- Source/Lib/Common/Codec/EbMalloc.c
- Source/Lib/Common/Codec/EbMalloc.h
fprintf was replaced with SVT_FATAL when memory allocation fails
Addresses #1387 
palexander-14
- [ x] N/A
- [x ] N/A
- [ x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
> fprintf was replaced with SVT_FATAL when memory allocation fails

- Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
- Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
- Source/Lib/Encoder/Codec/EbDeblockingFilter.c
Speedup picture_sse_calculations() kernel by using SIMD implementation
Speedup:
8b	M8 0,55%
8b	M6 2,51%
8b	M4 0,34%
8b	M2 0,31%
8b	M0 0,00%
10b	M8 1,32%
10b	M6 2,03%
10b	M4 0,73%
10b	M2 1,36%
10b	M0 0,65%
@tszumski
> Sppeedup picture_sse_calculations by using SIMD kernels

- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
test steps:
run "SvtAv1EncApp -n 10 -lad 0 -q 20 -intra-period 119 -lp 1 -i test.y4m -b two_passes.ivf --passes 2 --preset 4"
check the frame count print for the second pass, it will start from 1 instead of 11
fixes https://github.com/OpenVisualCloud/SVT-AV1/issues/1369
> SvtEncApp: do not count frame twice in 2 passes mode

- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
- Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- test/SadTest.cc
Generalize sad loop kernels to support width=6, 12
Previously some c code was being used when sb_width is non-multiple of 8 and not equals 4 for sad calculation.
Speed results(from unit tests):
-	sad_loop_kernel_sse4_1_intrin (for w=6 speedup is ~2.5x comapred to C, for w=12 speedup is  ~54x compared to C)
-	sad_loop_kernel_avx2_intrin (for w=6 speedup is ~2.5x comapred to C, for w=12 speedup is  ~81x compared to C)
-	sad_loop_kernel_avx512_intrin (for w=6 speedup is ~2.5x comapred to C, for w=12 speedup is  ~100x compared to C)
Speed results for command line: ```-enc-mode 7 -q 63 -intra-period  119 -lad 0 -lp 8  -n 2000 -i snow_mnt_480p_65f.y4m  -b out.bin```
Master: 26.825 fps
Changes: 27.768 fps
@tszumski
> Generalize sad loop kernels

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbCodingLoop.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.h
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
- Use the variance of the current block, and the tx_depth=1 vs. tx_depth=0 decision to skip tx_depth=2.
- Also renamed enc_dec_kernel() to mode_decision_kernel(), and renamed av1_encode_pass() to av1_encode_decode().
Related to #1405
Fixes #1415
@hguermaz 
| Preset(s)| Speed Deviation| BD-Rate  Deviation|
| -- | -- | --
|M0 | 1.0% | 0.02%|
|M4 | 0.5% | 0.00%|
> Early tx_depth=2 exit

- .github/workflows/macos.yml
Should fix issues such as where a PR introduces a new file, but due to using glob, cmake doesn't detect if it's been added or deleted in the unit test job
@1480c1
> macOS: Delete build folder before reconfiguring cmake

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Increase the number of WM candidates prepared during candidate generation by expanding the number of neighbour positions  searched and adding WM candidates for PME MVs.
Increase the number of reference frames used for certain reference pruning categories, and change used levels to always prepare candidates for at least the closest reference frames.
Fixes #1405 
Fixes #1411 
| Mode | BDR | Speed |
|-|-|-
|M1|-0.33%|No change|
|M3|-0.33%|No change|
|M5|-0.34% | No change |
Expected gain: -0.3% BD-rate, no speed cost in M1-M5; -0.15% BD-rate, no speed cost in M0
> Increase references and WM candidates at MD stage 0 candidate generation

- Source/Lib/Common/Codec/EbUtility.h
- Source/Lib/Decoder/Codec/EbDecObmc.c
- Source/Lib/Decoder/Codec/EbDecParseBlock.c
- Source/Lib/Decoder/Codec/EbDecPicMgr.c
Fixes some issues that were introduced by the cppcheck commits
Fixes #1423
@1480c1
> DecApp: Fix decoder segfault issues

- Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
- test/SadTest.cc
Incorrect calculate SAD for size (16,5) when search area width is 8 or 16. Fixed UT to cover this issue.
> Fix AVX512, SAD_LOOP fix calculation 16,5 for search area 8,x or 16,x

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Encoder/Codec/EbCodingUnit.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEntropyCoding.c
- Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbMdRateEstimation.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbMotionEstimation.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/av1me.c
- Source/Lib/Encoder/Codec/av1me.h
- Source/Lib/Encoder/Codec/mcomp.c
- Source/Lib/Encoder/Codec/mcomp.h
- Source/Lib/Encoder/Codec/mv.h
- Detect and improve the pred of high active block(s) @ MD (i.e. post ME), and fix MV bound: clip inherited ME MVs to stay within pic boundaries
- Make GMV params/candidates derivation multi-ref aware, and set multi-ref to be considered = f(input_complexity), and enable gm_identiy_exit.
- Upgrade subpel of me and of pme to use libaom subpel search.
Fixes #1414 
@hguermaz 
| Preset(s)| BD-Rate  Deviation| Speed Deviation| 
| -- | -- | --
|M0 | -0.25% | 11.23%|
|M1 | -0.30% | 7.10%|
|M2 | -0.41% | 6.93%|
|M3 | -0.56% | 11.17%|
|M4 | -0.57% | 12.44%|
|M5 | -0.51% | 11.09%|
|M6 | -1.04% | 4.93%|
|M7 | -1.19% | 4.22%|
> Improve INTER Pred

- CMakeLists.txt
This should help with situations like @EsmeraldaQuintero where cmake doesn't detect x86, but the compiler does
Should Fix #1343
@1480c1
> CMake: Use the compiler to actually detect if the 'cpu' is x86

- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
fix warning resulting in a conflict between TX_EARLY_EXIT and TWOPASS_RC
> fix warning resulting in a conflict between TX_EARLY_EXIT and TWOPASS_RC

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c
- Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecision.h
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/EbRateDistortionCost.h
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/firstpass.c
- Source/Lib/Encoder/Codec/mcomp.c
M7 Only:
- Cost-based pred refinement.
- Faster txt search level (only DCT tx types).
- Faster adaptive ME level.
- IFS @ MDS3.
- Faster INTRA level.
- ME_MV-based PME optimizations.
M7 & below:
- Improve PD0 rate estimation.
- Add mvcost @ the ME of MD: PME, adaptive ME, NSQ ME search.
- Bypass distortion_based_modulator() if no NSQ.
- No T-1 @ PD0 and no recon samples update if no INTRA canidatess..
- Bypass sse_gradian_band init if no NSQ.
- Bypass variance computation @ PD0; source_variance used only @ PD2.
- Shut useless pred depth refinement operations.
- Use the actual number of fast loop candidates instead of MAX_NFL_BUF @ fast_cost_init.
- Bypass useless neighbor update if no fast rate.
- Bypass  MVP init if no fast rate.
- Bypass ref masking init if only 1 ref per list.
- Bypass …
> Add a faster M7

- Docs/svt-av1_encoder_user_guide.md
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
Changes the output from using `\b` to `\r` since using `\b` can be quite ugly when logging to a file or trying to parse the output.
Perhaps an ideal would be to do something like ?
```none
[85.1%] 9323/10961, 24.96 fps, 993.49 kbps, eta 0:01:08
```
Closes #1348
Related to #1237, #1178, and #945
> App: Add option to print a bit more verbose or none as alternatives

- Source/Lib/Common/ASM_AVX512/EbHighbdIntraPrediction_AVX512.c
- Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c
- Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- test/SadTest.cc
Modification of sad_loop_kernel_{sse4_1/avx2/avx512} to support odd and even block width/height
@tszumski
> Modification of sad_loop_kernel_{sse4_1/avx2/avx512} to support odd and even block width/height

- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbCodingLoop.h
- Source/Lib/Encoder/Codec/EbEncCdef.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncInterPrediction.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecision.h
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
- Source/Lib/Encoder/Codec/EbModeDecisionProcess.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/firstpass.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
- gstreamer-plugin/gstsvtav1enc.c
- Use temporal layer information to improve lambda generation.
- Shift features to optimize preset trade-offs.
-- Cleanup: Remove unused signals
Fixes #1449 
| Preset(s)| BD-Rate  Deviation| Speed Deviation| 
| -- | -- | --
|M0 | -0.33% | No change|
|M1 | -0.17% | 6.5%|
|M2 | -0.45% | No change|
|M3 | -0.41% | No change|
|M4 | -0.73% | No change|
|M5 | -0.81% | -3%|
|M6 | -0.54% |  -3%|
|M7 | -1.01% | -4%|
> Improve Lambda Generation and optimize preset trade-offs

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/pass2_strategy.c
Fix the one pass QP assignment using frames_to_be_encoded. frames_to_be_encoded is not available in one pass encoding
Fix 2pass encoding related to next_key_frame_forced when intra refresh is used
@anaghdin 
- [x ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
1 PASS encoding CRF (older version)
preset | AVG   PSNR/SSIM/3*yPSNR
-- | --
M1 | 0.19%
M2 | 0.06%
M3 | 0.15%
M4 | 0.08%
M5 | 0.11%
M6 | 0.13%
1 PASS encoding CRF
preset | AVG   PSNR/SSIM/3*yPSNR
-- | --
M0 | -0.04%
M1 | -0.04%
M2 | -0.05%
M3* | 0.01%
M4* | 0.08%
M5* | 0.01%
M6* | 0.07%
** are for older version
2 PASS encoding CRF with intra refresh of 64
preset | AVG   PSNR/SSIM/3*yPSNR
-- | --
M4 | -0.88%
M6 | -1.07%
> Bug fixes related to QP assignment in 1 and 2 pass

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/firstpass.c
Speed up 2pass mode by optimizing pass1
Speed up the 2pass by 2X vs 1pass
Lossless for 1pass mode
#1458 
@chkngit 
@anaghdin 
@okhlif 
low res |   |   | PSNR BDR | SPEED
master_2pass_crf_M3 | vs. | master_1pass_crf_M3 | -0.09% | -3.17%
low res |   |   | PSNR BDR | SPEED
pr_2pass_crf_M3 | vs. | master_1pass_crf_M3 | -0.02% | -1.44%
> Pass1 speed up

- Docs/svt-av1_encoder_user_guide.md
Update the twopass documentation as the ones provided do not work due to flags being deprecated and  default flags causing issues such as --irefresh-type being set to 1 while it needs to be set to 2 for 2 pass to even work. This also removes some deprecated flags for the encoder referenced in #1452 
Fixes #1452 
Luis Garcia
> Update documentation, Remove deprecated flags and update two pass information/flags

- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
Completely fix the sanitizer issue caused by TPL non16aligned error, disable old TPL_SANITIZER_FIX change.
#define TPL_SANITIZER_FIX  0
#define TPL_NON16ALIGN_FIX 1
Signed-off-by: Kelvin Hu <kelvin.hu@intel.com>
> Fix TPL non16align error for openloop intra pred and dispenser

- Source/Lib/Encoder/Globals/EbEncHandle.c
fix deadlock when the intra period is not a multiple of the lookaheaddistance.
comes at a memory cost of ~18% to be addressed when restructuring tpl
should Fix #1453
Fixes #1451 
@chkngit
> Deadlock fix when keyint is not a multiple of lad

- Source/Lib/Encoder/ASM_AVX2/dwt_avx2.c
- Source/Lib/Encoder/Codec/EbTransforms.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- Source/Lib/Encoder/Codec/dwt.c
- Source/Lib/Encoder/Codec/dwt.h
- Source/Lib/Encoder/Codec/firstpass.c
- test/dwt_test.cc
1. Speedup kernel  av1_haar_ac_sad_8x8_uint8_input_c by implementation its SIMD version
Estimated speedup ~5.2x faster than C implementation
2. Cleanup  svt_av1_lowbd_fwd_txfm_c in order to avoid confusion
@tszumski
> Implementation of kernel av1_haar_ac_sad_8x8_uint8_input_avx2

- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Common/Codec/EbMalloc.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncodeContext.c
- Source/Lib/Encoder/Codec/EbEncodeContext.h
- Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/EbSequenceControlSet.c
- Source/Lib/Encoder/Codec/EbSequenceControlSet.h
- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Codec/firstpass.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Add memory interface for 2passes stats in and out.
Most of encoders like libaom will use memory as input/output for 2 passes stats.
This patch will make SvtAv1 follow the same tradition. 
guangxin.xu@intel.com
> 2passes memory interface

- Source/Lib/Common/Codec/EbThreads.c
If successful, the pthread_join() function shall return zero.
Signed-off-by: Limin Wang <lance.lmwang@gmail.com>
> Fix for the error condition checking for pthread_join

- Source/Lib/Encoder/Codec/firstpass.c
reproduce:
SvtAv1EncApp -lad 0 -q 20  -n 100 -intra-period 119 -i 172x144.y4m -b two_passes.ivf --passes 2 --preset 3
root cause:
we need use >= instead of > since we want write stats_out->stat[frame_number]
guangxin.xu@intel.com
> 2pass: fix crash for encode 100+ frames

- .github/workflows/macos.yml
Should fix an issue where the downloaded binary doesn't have +x set
@1480c1
> macos: Add execute bit before running unit tests

- Source/Lib/Encoder/Codec/EbModeDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
When FrameHeader::is_motion_mode_switchable is true then
obj->hbd_mode_decision can be changes during encoder work,
and then between alloc and free encoder the decision about alloc and free
was made on the basis of a different value.
Valgrind memleaks
Cmd:  ./SvtAv1EncApp --lp 8 -i LG_Cymatic_Jazz_HDR_003_864x480_10bit_60Hz_P420_300frames.yuv -w 864 -h 480 --preset 0 -n 5 -b jazz0.ivf --input-depth 10 --lp 2
Valgrind output:
==296430== 560 bytes in 1 blocks are possibly lost in loss record 4 of 32
==296430==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
==296430==    by 0x4012774: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==296430==    by 0x5E4487B: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==296430==    by 0x4E85CA0: eb_create_thread (EbThreads.c:93)
==296430== …
> Fix memory leaks from valgrind

- Docs/svt-av1_encoder_user_guide.md
Move the quantization flag to the rate control options above target bitrate since cqp mode is the default mode
Documentation update
Luis Garcia
> Documentation: Move quantization to Rate Control Options

- Docs/svt-av1_encoder_user_guide.md
Fix inaccurate documentation re: default --keyint value. The default value is -2; the docs say it is -1.
To confirm, simply run:
`SvtAv1EncApp.exe -i in.y4m --lp 1 --rc 0 -q 50 --keyint -2 -b keyint-2.ivf`
`SvtAv1EncApp.exe -i in.y4m --lp 1 --rc 0 -q 50 --keyint -1 -b keyint-1.ivf`
`SvtAv1EncApp.exe -i in.y4m --lp 1 --rc 0 -q 50 -b keyint-default.ivf`
and compare results/filesizes. Also, see https://github.com/AOMediaCodec/SVT-AV1/blob/master/Source/App/EncApp/EbAppConfig.c#L1430
motbob
> Documentation: Fix inaccurate default --keyint value

- Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
Calculation double/float in some cases can return different value.
#1428 
Slawomir Pawlowski
> Fix mismatch C/AVX2 kernel svt_av1_apply_temporal_filter_planewise()

- Build/linux/build.sh
a compilation example in `build.sh` didn't work, because it referenced a non-existing flag - `cpp`.
I changed the flag to `cxx` which does work, and is documented in the usage message.
nodeav
> fix typo in build.sh example

- Source/Lib/Encoder/Codec/EbCodingLoop.h
- Source/Lib/Encoder/Codec/EbEncInterPrediction.h
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/firstpass.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
- third_party/fastfeat/fast.c
Fixes warnings such as:
```c
../Source/Lib/Encoder/Codec/EbRateDistortionCost.c:548:17: warning: type of ‘model_rd_from_sse’ does not match original declaration [-Wlto-type-mismatch]
548 | /*static*/ void model_rd_from_sse(BlockSize bsize, int16_t quantizer,
|                 ^
../Source/Lib/Encoder/Codec/EbEncInterPrediction.c:2977:6: note: type mismatch in parameter 3
2977 | void model_rd_from_sse(BlockSize bsize, int16_t quantizer, uint8_t bit_depth, uint64_t sse,
|      ^
../Source/Lib/Encoder/Codec/EbEncInterPrediction.c:2977:6: note: type ‘uint8_t’ should match type ‘uint64_t’
../Source/Lib/Encoder/Codec/EbEncInterPrediction.c:2977:6: note: ‘model_rd_from_sse’ was previously declared here
../Source/Lib/Encoder/Codec/EbEncInterPrediction.c:2977:6: note: code may be misoptimized …
```
> LtoWarnings: Fix some warnings that appear when trying to use lto

- Source/Lib/Encoder/ASM_AVX2/dwt_avx2.c
steps to reproduce:
1. build with debug. "mkdir build && cd build && cmake ..  -DCMAKE_BUILD_TYPE=Debug && make install"
2. run "SvtAv1EncApp -lp 4 -lad 0 -q 20 -n 3 -intra-period 119 -i ~/bits/SVT/vidyo_720p.y4m -b two_passes.ivf --passes 2 --preset 3"
3. you will see a core dump.
details:
We need declare the output as 32 bytes aligned since transpose_32bit_8x8_avx2 will unref it as __m256i*
> avx2: eb_av1_haar_ac_sad_8x8_uint8_input_avx2, fix unaligned mov for transpose_32bit_8x8_avx2

- CMakeLists.txt
- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppInputy4m.c
- Source/App/EncApp/EbAppMain.c
- third_party/safestringlib/CMakeLists.txt
mingw-w64 clang does not have strnlen_s available, but mingw-w64 gcc seems to be fine
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/1815
@1480c1
> safestringlib: Compile strnlen_s based on availability

- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.h
- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
- test/e2e_test/ConfigEncoder.cc
split encode function to smaller functions to more readable samller functions. 
Tested command:
- SvtAv1EncApp -lp 4 -lad 0 -q 20  -n 3 -intra-period 119 -i ~/bits/SVT/172x144.y4m -i ~/bits/SVT/172x144.y4m -b two_passes.ivf --passes 2 --preset 3 -tttt
- SvtAv1EncApp -lp 4 -lad 0 -q 20  -n 3 -intra-period 119 -i ~/bits/SVT/172x144.y4m -i ~/bits/SVT/172x144.y4m -b two_passes.ivf --passes 2 --preset 3
- SvtAv1EncApp -nch 2 -c 1.cfg 2.cfg
> EncApp: Refact, split encode function to smaller functions.

- Source/Lib/Encoder/Globals/EbEncHandle.c
Being under development --rc 1 and 2 should not be used for any official benchmarking until fully implemented.
> Added explicit warning about rate control modes

- Source/App/EncApp/EbAppConfig.c
- Source/App/EncApp/EbAppConfig.h
- Source/App/EncApp/EbAppContext.c
- Source/App/EncApp/EbAppMain.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
At this point 2-pass only works when used with --rc 0 / 1.
- added check to handle the case where 2-pass is used with rc > 1
- removed code that manually overrides what rc was set to on the command line for first pass
Fixes #1483
@paulsgh
@1480c1
> Block 2-pass VBR when used with --rc 2 / 3

- Source/App/EncApp/EbAppMain.c
- Source/App/EncApp/EbAppProcessCmd.c
- Source/App/EncApp/EbTime.c
- Source/App/EncApp/EbTime.h
- Source/Lib/Common/Codec/EbTime.c
- Source/Lib/Common/Codec/EbTime.h
- Source/Lib/Decoder/Codec/EbDecProcess.c
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- test/CdefTest.cc
- test/EbUnitTestUtility.h
- test/EncodeTxbAsmTest.cc
- test/InvTxfm2dAsmTest.cc
- test/MotionEstimationTest.cc
- test/PaletteModeUtilTest.cc
- test/ResidualTest.cc
- test/RestorationPickTest.cc
- test/SadTest.cc
- test/SelfGuidedUtilTest.cc
- test/SpatialFullDistortionTest.cc
- test/TemporalFilterTestPlanewise.cc
- test/convolve_2d_test.cc
- test/corner_match_test.cc
- test/frame_error_test.cc
- test/quantize_func_test.cc
- test/selfguided_filter_test.cc
- test/warp_filter_test_util.cc
- test/wiener_convolve_test.cc
Changes some of the time-related functions so that we are using a more accurate function on Linux and windows.
@1480c1
> Time: Refactor time functions similar to SVT-VP9

- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Aligns the parameter defaults between the encoder app and the library so that things such as the ffmpeg plugin has similar default behaviour compared to the encoder app.
> Align parameter defaults

- Build/linux/build.sh
Fix job handling in cases where cmake is new enough to generate, but old enough to lack `--parallel` (thanks @ccccheung for noticing this)
Add parsing of `--arg=*` arguments, so you can now do `--prefix=$HOME/local` instead of needing `--prefix "$HOME/local"`, the later still works through.
Add support for `-j12` and `-GNinja` arguments to make it feel more natural and match cmake and make's way
@1480c1
> build.sh: Additional improvements

- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.c
- Source/Lib/Encoder/Codec/EbMotionEstimation.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- Source/Lib/Encoder/Codec/firstpass.c
- test/SadTest.cc
Add the ability to do full_sad calculation in ME by updating the ext_all_sad_calculation_8x8_16x16 code. Set me_search_method to sub_sad by default.
@ttrigui
> fix sub_sad/full_sad selection

- Source/Lib/Common/ASM_AVX2/highbd_warp_affine_avx2.c
- Source/Lib/Common/Codec/common_dsp_rtcd.c
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbTemporalFiltering.c
- Source/Lib/Encoder/Codec/EbTemporalFiltering.h
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
- test/TemporalFilterTestPlanewise.cc
- test/warp_filter_test.cc
- Fix integer overflow in 12bit SSIM calculation
- Scale the pixel difference in temporal filtering according to its bit depth. This resolves a compression performance regression in
12 bit setting
- port av1_highbd_warp_affine_avx2 and use it instead of the SSE4.1 version
@ttrigui 
@spawlows
> Port LibAom optimization and bug fixes

- Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
- Source/Lib/Encoder/C_DEFAULT/EbComputeSAD_C.c
- test/SadTest.cc
Added support for width=56/40 in nxm_sad_kernel_helper_avx2() and changed default condition
Fixes #1512 
@tszumski
> Fix nxm_sad_kernel_helper_avx2: Assertion `0' failed

- Source/App/EncApp/EbAppConfig.c
Uses printf instead of fprintf, which should be fine since we only switched to fprintf(stderr to leave stdout available for video output, but since we aren't actually sending out a video stream if get_help is called, we can use printf.
Switched to using spaces only instead of adding tabs along with some other readability improvements (I hope)
previously
```none
Usage: SvtAv1EncApp <options> -b dst_filename -i src_filename
Examples:                
Two passes encode:       
SvtAv1EncApp <--stats svtav1_2pass.log> --pass 1 -b dst_filename -i src_filename
SvtAv1EncApp <--stats svtav1_2pass.log> --pass 2 -b dst_filename -i src_filename
Or a combined cli:
SvtAv1EncApp <--stats svtav1_2pass.log> --passes 2 -b dst_filename -i src_filename
Options:                 
--help                    	Show …
```
> get_help: Send to stdout and improve readability

- Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c
Optimization of:
-svt_av1_apply_temporal_filter_planewise_avx2
-svt_av1_apply_temporal_filter_planewise_hbd_avx2
Speedup is ~2.1x faster than previous implementation
@tszumski
> Optimization of svt_av1_apply_temporal_filter_planewise

- .github/workflows/macos.yml
I am hoping that the first commit will solve the issue whenever cmake updates, however, it is hard to reproduce and test since I have only seen macOS store cmake in variable location
@1480c1
> Actions: Use the same brew commands for ga macOS and always run cmake for macos-vectors

- Source/Lib/Encoder/Codec/EbRateControlProcess.c
Delete the unused function svt_combine_prior_with_tpl_boost().
Originally named combine_prior_with_tpl_boost, it was just renamed in
commit e5d07c3b3cf73c6c9053a7c1ac3356867c732152. I found that it is not
used and can be deleted.
> Delete unused svt_combine_prior_with_tpl_boost()

- Source/Lib/Common/Codec/common_dsp_rtcd.c
Solves a warning when using a mingw-w64 gcc compiler since `__cpuidex` is
```c
void __cpuidex(
int cpuInfo[4],
int function_id,
int subfunction_id
);
```
and takes an array of ints instead of unsigned.
@1480c1
> run_cpuid: Use int instead of uint32_t since that's what it actualy uses

- CMakeLists.txt
- third_party/safestringlib/CMakeLists.txt
- third_party/safestringlib/safe_str_lib.h
didn't realize I was missing some code
The rest is for making sure that the unused functions are not declared at all so they do not conflict with the regular functions that already exist
@1480c1
> safestrlib: only declare the safestrlib functions if needed

- Source/Lib/Encoder/Globals/EbEncHandle.c
Some initial settings are not set, realated to the 2-pass encoding.
Without these settings, the encoder creates a small (low bitrate) bitstream, not the configured one.
Using this command line, the latest git version (after #1524) makes an 1/3 size (bitrate) output file (1657589 vs 504457 bytes)
ffmpeg -i desperado.mp4 -nostdin -f rawvideo -pix_fmt yuv420p - | SvtAv1EncApp.exe -i stdin -n 500 --pass 1 -w 1920 -h 1080 --preset 8 --irefresh-type 2 --rc 1 --tbr 800 -b desp_800k.ivf
ffmpeg -i desperado.mp4 -nostdin -f rawvideo -pix_fmt yuv420p - | SvtAv1EncApp.exe -i stdin -n 500 --pass 2 -w 1920 -h 1080 --preset 8 --irefresh-type 2 --rc 1 --tbr 800 -b desp_800k.ivf
And all (release and git) versions from v0.8.5 makes incorrect (small, low bitrate) bitstream using the library part only, due …
> 2pass: initial data rate control options

- Config/Sample.cfg
- Docs/svt-av1_encoder_user_guide.md
- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
Change --irefresh-type from 1 (open gop) to 2 (closed gop) to improve seekability in all major web browsers and various media players.
The default --irefresh-type of 1 (open gop) results in videos being difficult to seek in all of the major web browsers (Firefox, Google Chrome, Edge Chromium, etc) and various media players (MPV, MPC, VLC, etc)
Until these media players are updated to have better compatibility with --irefresh-type 1 (open gop), I suggest changing the default to --irefresh-type 2 (closed gop) in order to encourage better default settings, and greater chance of videos being encoded without seekability issues.
This new default setting will help increase the likelihood of AV1 being adopted because seekability issues will not be as much of a concern for people getting into AV1 …
> Change --irefresh-type from 1 (open gop) to 2 (closed gop)

- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/firstpass.c
Fix most of the valgrind errors from issue #1543 
After this PR is applied, only 3 errors left:
```
Syscall param write(buf) points to uninitialised byte(s)
at 0xEC4EA1D: ??? (in /usr/lib64/libc-2.17.so)
by 0xEBD9262: _IO_file_write@@GLIBC_2.2.5 (in /usr/lib64/libc-2.17.so)
by 0xEBDAA7D: _IO_do_write@@GLIBC_2.2.5 (in /usr/lib64/libc-2.17.so)
by 0xEBDCB24: _IO_flush_all_lockp (in /usr/lib64/libc-2.17.so)
by 0xEBDCC84: _IO_cleanup (in /usr/lib64/libc-2.17.so)
by 0xEB98C9A: __run_exit_handlers (in /usr/lib64/libc-2.17.so)
by 0xEB98D36: exit (in /usr/lib64/libc-2.17.so)
by 0xEB8155B: (below main) (in /usr/lib64/libc-2.17.so)
Address 0x40241d0 is in a rw- anonymous segment
at 0x535376C: coding_loop_context_generation …
```
> Fix some valgrind issues

- .github/workflows/sanitizers-known-warnings.txt
- .github/workflows/sanitizers.yml
Add task to CI: Sanitizer(thread-skip-known-warnings) with skip known issues.
Task is not allowed to fail, and will detect regression of new potential issues.
Known warnings are keep in file: /.github/workflows/sanitizers-known-warnings.txt"
Task Sanitizer thread (with allow to fail) raport to much issues to eliminate all in one fix.
Known warnings from Issue  #1308 should be removed in small steps.
#1308 - only support to fix
@spawlows
> Add task to CI Sanitizer thread with skip known issues.

- Source/Lib/Encoder/Codec/noise_model.c
Fix wrong size of memory allocation when Film Grain is used
Fixes 2 out of 3 points in issue #1444 
1 - for the film grain unit test : "SvtMalloc[fatal]: allocate memory failed, at D:\a\SVT-AV1\SVT-
AV1\Source\Lib\Encoder\Codec\noise_model.c, L1499"
3- Memory increase : Up to 20% in some cases
#1444
@tszumski
> Fix wrong size of memory allocation when Film Grain is used

- Source/App/EncApp/EbAppConfig.c
adds back the default value for progress output.
There is no quality or speed impact expected.
Tested Objective-1-fast 8 bit
  | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M4 - 8bit - 1 pass | -0.21% | 0.00 | 0.01%
M8 - 8bit - 1pass | -0.36%|  0.00| 0.01%
fixes #1564 
@ccccheung
> set progress to default to 1 in EbConfig constructor

- Source/Lib/Encoder/Codec/firstpass.c
Initialize with 0 variables that are used by "--pass 1"
Fixes valgrind issue:
```
==56469== Syscall param write(buf) points to uninitialised byte(s)
==56469==    at 0x66C7297: write (write.c:27)
==56469==    by 0x664222C: _IO_file_write@@GLIBC_2.2.5 (fileops.c:1203)
==56469==    by 0x6643FC0: new_do_write (fileops.c:457)
==56469==    by 0x6643FC0: _IO_do_write@@GLIBC_2.2.5 (fileops.c:433)
==56469==    by 0x6646271: _IO_flush_all_lockp (genops.c:769)
==56469==    by 0x6646474: _IO_cleanup (genops.c:921)
==56469==    by 0x65FA1B1: __run_exit_handlers (exit.c:130)
==56469==    by 0x65FA1E9: exit (exit.c:139)
==56469==    by 0x65D8B9D: (below main) (libc-start.c:344)
==56469==  Address 0xf7c2640 is 464 bytes inside a block of size 4,096 alloc'd
==56469==    at 0x4C2FB0F: malloc (in …
```
> Fix valgrind v2

- Source/App/EncApp/EbAppConfig.c
based on the conversation https://github.com/AOMediaCodec/SVT-AV1/commit/99c6693dc744732e23ea33a6cdff916e7a7131a3#r43459612
command ran
```bash
./master/SvtAv1EncApp --passes 2 -i /home/ubuntu/akiyo_cif.y4m --preset 3 --keyint -1 -b masterm3.ivf
./pr/SvtAv1EncApp --passes 2 -i /home/ubuntu/akiyo_cif.y4m --preset 3 --keyint -1 -b prm3.ivf
diff masterm3.ivf prm3.ivf
```
The changes are expected to be lossless
/cc @xuguangxin 
@1480c1
> eb_config_ctor: remove reassignment of the pass variable

- Source/Lib/Common/Codec/Av1Common.h
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
replace the ME segments completion mask (64 bit) by a counter to avoid restricting the number of ME segments to 64
@ttrigui
> remove restricting the maximum number of ME segments to 64

- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbDebugMacros.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPredictionStructure.c
- Source/Lib/Encoder/Codec/EbPredictionStructure.h
- Source/Lib/Encoder/Globals/EbEncHandle.c
- To support 0B/1B/3B or -hierarchical-level 0/1/2 and tune low delay
To support -hierarchical-level 0/1/2 and tune low delay
@kelvinhu325 
@lijing0010 
@anaghdin 
- [] quality
>  Tune 0B/1B/3B settings to support minigop 1, 2 and 4

- Docs/svt-av1_encoder_user_guide.md
- Source/API/EbDebugMacros.h
- Source/API/EbSvtAv1Enc.h
- Source/App/EncApp/EbAppConfig.c
- Source/Lib/Common/Codec/EbDefinitions.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbCodingUnit.h
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbEncodeContext.c
- Source/Lib/Encoder/Codec/EbEncodeContext.h
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.h
- Source/Lib/Encoder/Codec/firstpass.c
- Source/Lib/Encoder/Codec/pass2_strategy.c
- Source/Lib/Encoder/Globals/EbEncHandle.c
- Added re-encode support for 2pass VBR
- Fixed 2nd pass last small group too big frame size error
- Set default min_qp_allowed=1 for VBR good quality
- To allow SB128x128 for 2pass VBR
- Add 2pass VBR 4L support
@kelvinhu325 
@lijing0010 
@anaghdin 
@huijuanzh
> add re-encode support for 2PASS and 2PASS VBR improvement

- Source/Lib/Common/Codec/common_dsp_rtcd.c
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
Cleanup set pointers on kernel when initializing codec in files common_dsp_rtcd.c and aom_dsp_rtcd.c
All kernels are set by macros, to be more readable.
@spawlows
> Cleanup macros to set kernel pointers

- test/stylecheck.sh
In interactive use (with a tty) git would use a pager for the grep output, causing the script to not work as expected locally.
Additionally the check for git was done after it was used, making it not very useful. For the EOF check, another test condition is added that will prevent a hard failure of the script when git diff would return a path to a folder or empty string.
Might help with the failure mentioned at https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/1#note_451236568
Marvin Scholz
> Fix a few issues with the stylecheck script

- test/stylecheck.sh
The stylecheck script did some check in the diff against the upstream git master branch.
This would lead to failures when the script actually runs in the CI jobs on git master, as the
diffs would be empty in these cases, which the script was not handling properly.
This should fix the Gitlab CI style check failures.
Marvin Scholz
> Further stylecheck fixes

- Build/linux/build.sh
Fixes the build script always encountering the following error:
`./Build/linux/build.sh: line 269: syntax error near unexpected token `)'`
Marvin Scholz
> build.sh: Fix broken build script

- Source/Lib/Decoder/pkg-config.pc.in
The library name to link with had a typo in the `.pc` file template.
Fix #1525
Marvin Scholz
> pkg-config: Fix SvtAv1Dec library name

- Source/App/EncApp/EbAppMain.c
test comandline:  SvtAv1EncApp -i test.y4m -o out.yuv -b out.ivf
expected: no error.
fixes #1592
> EbConfig: set recon_eanbled to true when the user assigned a recon_file in the command line

- Source/API/EbDebugMacros.h
- Source/Lib/Encoder/Codec/EbCodingLoop.c
- Source/Lib/Encoder/Codec/EbEncDecProcess.c
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbModeDecision.c
- Source/Lib/Encoder/Codec/EbMotionEstimationContext.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
- Source/Lib/Encoder/Codec/EbPacketizationProcess.c
- Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbRateDistortionCost.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/EbSequenceControlSet.c
- Source/Lib/Encoder/Codec/firstpass.c
- Source/Lib/Encoder/Codec/firstpass.h
- Source/Lib/Encoder/Codec/pass2_strategy.c
- Source/Lib/Encoder/Codec/pass2_strategy.h
- Source/Lib/Encoder/Globals/EbEncHandle.c
The first pass encoding is restructured and moved to PictureDecisionProcess. Both ME and Intra are performed on source pixels.
This commit improves the performance of 2 Pass VBR. Also, the support for adding a new 1 Pass VBR is added.
@anaghdin 
- [x ] other google low res
svt-av1 |   | svt-av1 | AVG PSNR/SSIM/3*yPSNR | Speed Dev
2PASS_VBR_NEW_M2 | vs. | 2PASS_VBR_REF_M2 | -0.33% | -1.24%
2PASS_VBR_NEW_M4 | vs. | 2PASS_VBR_REF_M4 | -0.37% | -0.81%
2PASS_VBR_NEW_M6 | vs. | 2PASS_VBR_REF_M6 | -0.18% | 1.04%
2PASS_VBR_NEW_M7 | vs. | 2PASS_VBR_REF_M7 | -0.20% | 3.18%
> Restructured First Pass

- Source/App/EncApp/EbAppConfig.c
The way find_token was written would lead to it unconditionally
using the next argument following the token. In cases where the
token is the last argument, this could lead to it passing NULL
to strcpy_s which is invalid, triggering an assertion on Windows
debug builds.
This was not reproducible on other platforms as the replacement
strcpy_s implementations does not seem to follow the Windows
implementation for that and only returns an error for these
cases, which is ignored here.
Marvin Scholz
> EbAppConfig: Rewrite find_token to fix assertion

- .github/workflows/sanitizers-known-warnings.txt
- Source/App/EncApp/EbAppProcessCmd.c
- Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/EbRestProcess.c
- Source/Lib/Encoder/Codec/EbSequenceControlSet.c
* process_output_stream_buffer and process_output_stream_buffer
* set_picture_parameters_for_statistics_gathering() move to init loop
* resource_coordination_kernel() set scs_ptr->block_mean_calc_prec move to init loop
* resource_coordination_kernel() set scs_ptr->scd_mode move to begin
* rest_kernel() release pcs_ptr after all reference pointers are used
Fix part of Sanitizer issues.
#1308
@spawlows
> Sanitizer: Fix part of data race issues(#1308)

- Source/App/EncApp/EbAppInputy4m.c
- Source/App/EncApp/EbAppInputy4m.h
- Source/App/EncApp/EbAppProcessCmd.c
increases the max length for 4096 since according to the ["spec"](https://linux.die.net/man/5/yuv4mpeg) the header contains an `unlimited number of TAGGED-FIELDs`
Fixes #1580
@1480c1
> y4m: support y4m with header sizes up to 4096

- .gitlab-ci.yml
glibc has some known issues with valgrind when compiled with static glibc
https://stackoverflow.com/questions/7506134/valgrind-errors-when-linked-with-static-why
@1480c1
> gitlab: don't compile valgrind executable with static linking

- CMakeLists.txt
-march=native can activate -mavx on certain archs that can cause segfaults
on random lines of code
@1480c1
> CMake: add -mno-avx if -march=native is present

- Source/Lib/Common/Codec/common_dsp_rtcd.c
- Source/Lib/Encoder/Codec/aom_dsp_rtcd.c
to confirm locally,
```bash
sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
./Build/linux/build.sh -t https://github.com/m-ab-s/aom/raw/master/build/cmake/toolchains/arm64-linux-gcc.cmake
```
```c
../../../Source/Lib/Common/Codec/common_dsp_rtcd.c: In function ‘setup_common_rtcd_internal’:
../../../Source/Lib/Common/Codec/common_dsp_rtcd.c:221:13: error: ‘check_pointer_was_set’ undeclared (first use in this function)
221 |         if (check_pointer_was_set && ptr != 0) {                                                                           \
|             ^~~~~~~~~~~~~~~~~~~~~
```
@1480c1
> fix building on non-x86 platforms

- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
Encoding using user defined custom prediction structure was not working. The small bug fix resolves this issue
The issue seems to have crept in at commit id: a0f233f6ba5d173fc8e258ded045fb0d75074747 
(suggest adding a test for the user defined config to avoid such issues in the future) 
Fixes #1567 
@kedartatwawadi
> Fix issue with encoding using user defined prediction structure config

- Source/Lib/Common/Codec/EbPictureOperators.c
- Source/Lib/Common/Codec/EbPictureOperators.h
- Source/Lib/Encoder/Codec/EbFullLoop.c
- Source/Lib/Encoder/Codec/EbProductCodingLoop.c
conflicts with vmaf 2.0.0
/cc @kylophone potential cause to look into prefixing/namespacing the symbols in both libraries?
also, @kylophone do you happen to use a .clang-format in vmaf?
https://github.com/m-ab-s/media-autobuild_suite/issues/1869#issuecomment-737588744
https://github.com/AOMediaCodec/SVT-AV1/pull/1620
@1480c1
> picture_copy: rename to svt_av1_picture_copy

- Source/Lib/Encoder/Codec/EbRateControlProcess.c
Fix allows VBR RC to pick lower of two qp candidates when lookahead returns the same bits prediction for two adjacent qp values
Fix #1499 
palexander-14
> Fix issue with hang-up on VBR encoding with specific conditions

- CMakeLists.txt
- third_party/cpuinfo/CMakeLists.txt
- third_party/cpuinfo/deps/clog/CMakeLists.txt
silences a dev warning from CMake
@1480c1
> CMake: set CMP0063 to new to silence warning

- CMakeLists.txt
cmake on centos errors out with `-Werror` since their header contains an error if `-O*` is not specified and fortify source is set
@1480c1
> CMake: only apply fortify source if optimization is applied and not 0

- .github/workflows/mingw-w64.yml
- .github/workflows/patches.yml
adds libvmaf to the list of tested libraries
@1480c1
> patches: add libvmaf to ffmpeg builds

- .gitlab-ci.yml
switch to centos to closer match what people who are actually using gcc 4.8.5 might use
@1480c1
> gitlab: use centos 7 for gcc4.8

- .gitlab-ci.yml
adds a valgrind run with pass 1 that's allowed to fail
@1480c1
> gitlab: add valgrind with pass 1 job

- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.h
- Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c
Fix valgrind error for "--pass 1"
Command line example:
```
valgrind  ./SvtAv1EncApp --lp 1 -i BQSquare_176x144_60.yuv -w 176 -h 144 --preset 3  -n 17 --irefresh-type 2 --pass 1 --stats stat_file.stat
at 0x4A5C7CF: derive_picture_activity_statistics (EbSourceBasedOperationsProcess.c:99)
by 0x4A5C932: source_based_operations_kernel (EbSourceBasedOperationsProcess.c:176)
by 0x5A31608: start_thread (pthread_create.c:477)
by 0x5956292: clone (clone.S:95)
```
> Fix valgrind for "--pass 1"

- .github/workflows/sanitizers-known-warnings.txt
- Source/Lib/Encoder/Codec/EbEncodeContext.c
- Source/Lib/Encoder/Codec/EbEncodeContext.h
- Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c
- Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
- Source/Lib/Encoder/Codec/firstpass.c
Fix Sanitizer thread issues
1] signal_derivation_pre_analysis_oq()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Kernel resource_coordination_kernel() …
> Task sanitizer fix

- .gitlab-ci.yml
soft blocked by https://github.com/Netflix/vmaf/pull/768 and https://gitlab.com/AOMediaCodec/aom-testing/-/merge_requests/13
/cc @ePirat 
@1480c1
> gitlab: add FFmpeg linux build

- CMakeLists.txt
- Source/Lib/Common/Codec/common_dsp_rtcd.c
- Source/Lib/Common/Codec/common_dsp_rtcd.h
- Source/Lib/Decoder/CMakeLists.txt
- Source/Lib/Encoder/ASM_AVX512/highbd_fwd_txfm_AVX512.c
- Source/Lib/Encoder/CMakeLists.txt
- Source/Lib/Encoder/Codec/firstpass.c
- test/FwdTxfm2dAsmTest.cc
Fix AVX512 build and add AVX512 implementation for missing kernels svt_av1_fwd_txfm2d* N2,N4
Fix C only build, (Travis CI task should pass)
@spawlows
> Fix avx512 build

- .github/workflows/ci.yml
- .gitlab-ci.yml
adds arm64 and pcc compilation to gitlab while also using CMake's external project module to pull cpuinfo at configure time instead of our local copy and build it
related to #1614 #1613
@1480c1
> Gitlab: add arm64 and ppc arch compilation

- .gitlab-ci.yml
adds gstreamer testing to gitlab
https://gitlab.com/AOMediaCodec/aom-testing/-/merge_requests/14
@1480c1
> gitlab: add gstreamer

- .github/workflows/patches.yml
- .gitlab-ci.yml
> ci: remove merged vmaf patch

- Source/API/EbDebugMacros.h
- Source/Lib/Common/Codec/EbThreads.c
- Source/Lib/Common/Codec/EbThreads.h
- Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c
- Source/Lib/Encoder/Codec/EbPictureControlSet.h
- Source/Lib/Encoder/Codec/EbRateControlProcess.c
- Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
This PR fixes some deadlocks in the encoder.
Tested on obj-1 fast 8-bit on M4 and M8 and saw no bitstream changes
  | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M4 - 8bit| -0.02% | 0.00% | 0.00%
M8 - 8bit| -0.53% | 0.00% | -0.02%
@ccccheung 
@Arhuan
@1480c1
> Fix some deadlock issues

- .github/workflows/cppcheck.yml
- .gitlab-ci.yml
This limits the messages shown on the cppcheck jobs to just errros
@1480c1
> cppcheck: suppress unused functions and extra messages

- Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c
```c
FAILED: Source/Lib/Common/ASM_AVX512/CMakeFiles/COMMON_ASM_AVX512.dir/EbPictureOperators_Intrinsic_AVX512.c.o 
/usr/lib/ccache/gcc-10 -DARCH_X86_64=1 -DEN_AVX512_SUPPORT=1 -DSAFECLIB_STR_NULL_SLACK=1 -I../. -I../Source/API -I../Source/Lib/Common/Codec -I../Source/Lib/Common/C_DEFAULT -I../Source/Lib/Common/ASM_SSE2 -I../Source/Lib/Common/ASM_SSSE3 -I../Source/Lib/Common/ASM_SSE4_1 -I../Source/Lib/Common/ASM_AVX2 -I../Source/Lib/Common/ASM_AVX512 -Wall -Wextra -Wformat -Wformat-security -Werror -Wshadow -fstack-protector-strong -mavx2 -mavx512f -mavx512bw -mavx512dq -mavx512vl -O3 -DNDEBUG -fPIC -fvisibility=hidden -std=gnu99 -MD -MT Source/Lib/Common/ASM_AVX512/CMakeFiles/COMMON_ASM_AVX512.dir/EbPictureOperators_Intrinsic_AVX512.c.o -MF …
```
> svt_spatial_full_distortion_kernel_avx512: fix Wshadow warning

- .gitlab-ci.yml
Add mingw-w64 ffmpeg builds to gitlab, uses the docker containers
example https://gitlab.com/1480c1/SVT-AV1/-/jobs/948378800
https://gitlab.com/AOMediaCodec/aom-testing/-/merge_requests/19
@1480c1
> gitlab: add windows ffmpeg build

- .travis.yml
- Updates the build environment to Ubuntu 20.04 Focal Fossa
- Removes the allow_failure flag for IBM Z, since it was temporary (see #1395)
@EwoutH
> Travis CI: Update to Ubuntu 20.04 and remove IBM Z allow_failure

- CMakeLists.txt
`-mavx` implies `-msse2avx` which converts sse to avx which can cause seg faults
moves `-mno-avx` from being only applied on march to being applied generally
Fixes  https://github.com/AOMediaCodec/SVT-AV1/issues/1668
@1480c1
> CMake: add -mno-avx if supported

- .gitlab-ci.yml
use the individual files for gitlab so we can remove video.tar.zst
@1480c1
> gitlab: use individual video files 

- .gitlab-ci.yml
This should theoretically be the last CI related job that needs to the added before the move
I am working on trying to combine as many of the ffmpeg jobs as we can so we do not have to update duplicate lines anytime we need to fix something.
https://gitlab.com/1480c1/SVT-AV1/-/pipelines/241438154
@ePirat 
@1480c1
> gitlab: add macOS FFmpeg test

- .gitlab-ci.yml
Cleanup .gitlab-ci.yml file to move similar jobs closer together and use yaml anchors more to reduce duplicate lines
Tagged the untagged jobs with `gitlab-org` since those runners have better specs than the untagged runners.
Limits self-hosted jobs to 2 each since unlike the Linux jobs, those are running on the same physical machine/vm so they don't benefit from the autoscaling like the ones running on linux
Adds mismatch test to test the difference between the outputted ivf file, matrixed between Release/Debug, Linux (Default branch)/Linux/macOS/Windows, 8/10 bit
https://github.com/AOMediaCodec/SVT-AV1/issues/1531
@1480c1
> Gitlab: Cleanup and add missmatch test

- CMakeLists.txt
`--coverage` was not being applied because it requires it to be in the linker flags as well
@1480c1
> CMake: fix COVERAGE option
