AOMediaCodec/SVT-AV1

Source/App/EbAppInputy4m.c, Source/App/EbAppInputy4m.h
Replace warnings by error checking via assertions
=> Fix compile warnings in y4m header parsing

Build/linux/build.sh
Should fix https://github.com/OpenVisualCloud/SVT-AV1/pull/8#issuecomment-461713169
=> build.sh: Compat with old Bash versions (macOS)

Source/Lib/Codec/EbCdef.c, Source/Lib/Codec/EbCdef.h, Source/Lib/Codec/EbCdefProcess.c, Source/Lib/Codec/EbCdefProcess.h, Source/Lib/Codec/EbCodingLoop.c, Source/Lib/Codec/EbDeblockingFilter.c, Source/Lib/Codec/EbDeblockingFilter.h, Source/Lib/Codec/EbDefinitions.h, Source/Lib/Codec/EbDlfProcess.c, Source/Lib/Codec/EbDlfProcess.h, Source/Lib/Codec/EbEncDecProcess.c, Source/Lib/Codec/EbEncDecProcess.h, Source/Lib/Codec/EbEncDecResults.h, Source/Lib/Codec/EbEncHandle.c, Source/Lib/Codec/EbEncHandle.h, Source/Lib/Codec/EbPictureControlSet.c, Source/Lib/Codec/EbPictureControlSet.h, Source/Lib/Codec/EbRestProcess.c, Source/Lib/Codec/EbRestProcess.h, Source/Lib/Codec/EbRestoration.c, Source/Lib/Codec/EbRestoration.h, Source/Lib/Codec/EbRestorationPick.c, Source/Lib/Codec/EbSequenceControlSet.c, Source/Lib/Codec/EbSequenceControlSet.h
bit exact changes to change Cdef and Restoration search algorithm from frame based processes to segment based ones.
=> Multi-threading of Cdef/Restoration search

Source/Lib/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c, Source/Lib/ASM_AVX2/jnt_convolve_avx2.c, Source/Lib/ASM_AVX2/wiener_convolve_avx2.c
=> Task aom update

.travis.yml
Added a debug build on Linux to Travis CI.
Seems to build fine, so #74 is probably about something else.
=> Add debug build to Travis

Source/Lib/Codec/EbDefinitions.h, Source/Lib/Codec/EbModeDecision.c, Source/Lib/Codec/EbPictureDecisionProcess.c, Source/Lib/Codec/EbProductCodingLoop.c
Compare to latest M0
4% loss in bdrate score
150% increase in speed
=> M1 settings

Source/Lib/ASM_AVX2/highbd_fwd_txfm_avx2.c
=> Fix crash with nonalignment memory when encode with resolution 864x480

Source/App/EbAppConfig.c, Source/App/EbAppInputy4m.c, Source/App/EbAppProcessCmd.c
=> Small fixes to the YUV4MPEG2 input support

ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch, ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Signed-off-by: Jing SUN <jing.a.sun@intel.com>
=> FFmpeg Plugin: update the plugins

Source/Lib/Codec/EbEntropyCoding.c
=> Avoid off-by-one in update_cdf()

Source/Lib/Common/Codec/EbNeighborArrays.c, Source/Lib/Common/Codec/EbNeighborArrays.h, Source/Lib/Common/Codec/EbPictureOperators.c, Source/Lib/Common/Codec/EbPictureOperators.h, Source/Lib/Common/Codec/EbProductCodingLoop.c
from 1.5% to 1.0% of all encodeing in M6.
=> Optimization md_update_all_neighbour_arrays_multiple() by 30%

ffmpeg_plugin/README.md
"-preset 1" is slow and not recommended, so to be removed.
=> FFmpeg Plugin: Improve sample cmdlines in README

Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c, Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c, Source/Lib/Common/Codec/aom_dsp_rtcd.h
Average speed up of all highbd_paeth_predictor: ~12 times.
=> Add aom_highbd_paeth_predictor kernel in AVX2.

Source/Lib/Common/Codec/EbInitialRateControlProcess.c
=> Replace with the correct mutex

Source/Lib/Encoder/Codec/EbEncHandle.c
=> Fix a regression which increases init time

CHANGELOG.md, Source/API/EbSvtAv1.h
Add CHANGELOG.md, since it's time to start cutting weekly pre-releases.
=> add CHANGELOG.md

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbModeDecision.c, Source/Lib/Common/Codec/EbModeDecisionProcess.c, Source/Lib/Common/Codec/EbModeDecisionProcess.h
=> Eighth pel

.travis.yml
Add a mirror if it fails to get from GitHub, change back to https since it autoredirects to https
Hopefully Closes #270 
I haven't been able to test yet since i can't reproduce the failure on my travis
=> Travis: add mirror and use https

README.md
- Fixes lists, especially in the __Installation__ sections
- Adds codeblocks for command lines
- Some other minor layout fixes
=> Readme: Fix lists, add codeblocks and other minor layout

Source/Lib/Common/Codec/EbDefinitions.h
=> Turn off EIGTH_PEL_MV support until conflict is fixed

.travis.yml
For now the Style check is allowed to fail (waiting on #248), but that should be reversed as soon as possible.
**Todo:**
=> [WIP] CI: Add coding style check to Travis, cleanup

test/AdaptiveScanTest.cc, test/api_test/CMakeLists.txt, test/e2e_test/CMakeLists.txt
1. fix missing SvtAv1Enc library issue on building api test and
e2e test.
2. add scan table test
=> Add adaptive scan test and fix compiling issue

Source/Lib/Common/Codec/EbDefinitions.h
this is rebase version of https://github.com/OpenVisualCloud/SVT-AV1/pull/287#event-2402924277
=> EB_MALLOC: remove duplicate code and do more check

.travis.yml
=> Travis CI: Remove allow_failure from Style job

CHANGELOG.md, CONTRIBUTING.md, Docs/svt-av1_decoder_user_guide.md, Docs/svt-av1_encoder_user_guide.md, LICENSE.md, NOTICES.md, README.md, STYLE.md, ffmpeg_plugin/README.md, gstreamer-plugin/README.md, test/Readme.md
Cosmetic changes for some files and functional for others
Some changes are based off https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md
a lot of the changes don't change how the file is viewed through GitHub, just in the editor.
=> markdown: format markdown files

CMakeLists.txt, Source/Lib/Encoder/Codec/CMakeLists.txt, test/api_test/SvtAv1EncParamsTest.cc, test/api_test/params.h
1. Update some param setting
2. Add parameters (screen_content_mode, enable_altrefs,
altref_strength, altref_nframes and enable_overlays).
=> Add more param test into api_test

Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c
commit 1c3369bd:
Author: cabirdme
SadLoopKernel(AVX2) and SadLoopKernelHme0(AVX2/AVX512)
commit 0e43ee38:
Author: lzhangnj
Fix a bug in SadLoopKernel_AVX2_HmeL0_INTRIN() and SadLoopKernel_AVX512_HmeL0_INTRIN()
=> Cherry pick bug fixes in SVT-HEVC

Source/Lib/Decoder/CMakeLists.txt, Source/Lib/Encoder/CMakeLists.txt
Fixes #363
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
=> Add SOVERSION for Encoder and Decoder shared libraries

.travis.yml
=> Travis: Add Werror CFLAG when building SVT-AV1

Source/Lib/Common/Codec/EbPictureAnalysisProcess.c
Description
Tune the screen content detector to consider block variance
Authors
@okhlif
Type of change
Detector improvement
Expected Average PSNR-SSIM BD-rate gain in the range of -0.2% on the AOM test set
No Speed impact
=> sc detector tuning

Source/Lib/Common/Codec/EbInterPrediction.c, test/convolve_2d_funcs.h, test/convolve_2d_test.cc
1. Test avx2 version of convolve functions by comparing with c
implementation.;
=> Add unit test for interpolation in inter prediction

appveyor.yml
Fixes #425 
Not ideal, should be fixed CMake side, but due to CMake and multi config generators, I'm unable to force it  to be set properly
=> appveyor: Fix artifacts

Source/Lib/Common/Codec/EbDefinitions.h
=> Update MAX_TILE_COLS and MAX_TILE_ROWS to 64 as per the spec

CHANGELOG.md, Docs/svt-av1_decoder_user_guide.md, Source/App/DecApp/EbDecAppMain.c, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbInterPrediction.c, Source/Lib/Common/Codec/EbInterPrediction.h, Source/Lib/Decoder/Codec/EbDecBitstreamUnit.h, Source/Lib/Decoder/Codec/EbDecBlock.h, Source/Lib/Decoder/Codec/EbDecHandle.c, Source/Lib/Decoder/Codec/EbDecHandle.h, Source/Lib/Decoder/Codec/EbDecInterPrediction.c, Source/Lib/Decoder/Codec/EbDecInterPrediction.h, Source/Lib/Decoder/Codec/EbDecMemInit.c, Source/Lib/Decoder/Codec/EbDecMemInit.h, Source/Lib/Decoder/Codec/EbDecNbr.c, Source/Lib/Decoder/Codec/EbDecNbr.h, Source/Lib/Decoder/Codec/EbDecParseBlock.c, Source/Lib/Decoder/Codec/EbDecParseHelper.c, Source/Lib/Decoder/Codec/EbDecParseHelper.h, Source/Lib/Decoder/Codec/EbDecParseInterBlock.c, Source/Lib/Decoder/Codec/EbDecParseInterBlock.h, Source/Lib/Decoder/Codec/EbDecParseObu.c, Source/Lib/Decoder/Codec/EbDecPicMgr.c, Source/Lib/Decoder/Codec/EbDecPicMgr.h, Source/Lib/Decoder/Codec/EbDecProcessBlock.c, Source/Lib/Decoder/Codec/EbDecProcessFrame.h, Source/Lib/Decoder/Codec/EbDecStruct.h, Source/Lib/Decoder/Codec/EbDecUtils.c, Source/Lib/Decoder/Codec/EbDecUtils.h, Source/Lib/Decoder/Codec/EbObuParse.h
This is same as PR #405, but rebased to latest master and fixed few bugs.
=> Initial decoder version with inter tools support

Source/Lib/Common/Codec/EbRateControlProcess.c
=> Fix the stability issue caused by BRC

test/CdefTest.cc, test/SpatialFullDistortionTest.cc
Add test for cdef_find_dir, cdef_filter_block, copy_rect8_8bit_to_16bit,
compute_cdef_dist and search_one_dual functions.
=> Add unit test for cdef

test/random.h, test/weiner_convolve_test.cc
add unit test for wiener convolve
=> wiener convolve test

Source/Lib/Common/ASM_AVX2/EbIntraPrediction_Intrinsic_AVX2.c, Source/Lib/Common/Codec/EbCodingLoop.c, Source/Lib/Common/Codec/EbFullLoop.c, Source/Lib/Common/Codec/EbIntraPrediction.c, Source/Lib/Common/Codec/EbIntraPrediction.h, Source/Lib/Common/Codec/EbModeDecisionProcess.h, Source/Lib/Common/Codec/EbMotionEstimationContext.c, Source/Lib/Common/Codec/EbMotionEstimationContext.h, Source/Lib/Common/Codec/EbRestProcess.c, Source/Lib/Common/Codec/EbRestoration.c, Source/Lib/Common/Codec/EbRestorationPick.c, Source/Lib/Common/Codec/EbWarpedMotion.c, Source/Lib/Common/Codec/EbWarpedMotion.h
Went through all AVX2 code and identified some memories which should be aligned.
=> Improve SIMD alignment

test/e2e_test/SvtAv1E2ETest.cc, test/e2e_test/VideoSource.cc, test/e2e_test/Y4mVideoSource.cc, test/e2e_test/YuvVideoSource.cc, test/vectors/longtime_comformance_test.cfg
1. Modified video source to support loop mode.
2. Add longtime conformance test.
=> Add longtime conformance test

test/SadTest.cc
1.add unit tests for eight_horizontal_32x32_64x64,
ext_all_sad_calculation and  ext_sad_calculation.
=> add more unit tests for sad functions

test/SelfGuidedUtilTest.cc
1. Add test for av1_{lowbd, highbd}_pixel_proj_error_avx2 and
get_proj_subspace_avx2
=> Add unit test for project-related test in selfguided restoration

test/FFTTest.cc, test/random.h
a. Add unit test for FFT and iFFT
=> Add FFT and iFFT unit test

test/e2e_test/E2eTestVectors.h, test/e2e_test/RefDecoder.cc, test/e2e_test/RefDecoder.h, test/e2e_test/SvtAv1E2EFramework.cc, test/e2e_test/SvtAv1E2EFramework.h, test/e2e_test/SvtAv1E2EParamsTest.cc, test/e2e_test/SvtAv1E2ETest.cc
Fix the issue that the encoder parameters does not take effect
in SvtAv1E2ETest.cc
=> Fix encoder parameter setup issue in e2e test

Source/Lib/Common/ASM_AVX2/CMakeLists.txt, Source/Lib/Common/ASM_AVX512/CMakeLists.txt, Source/Lib/Common/ASM_SSE2/CMakeLists.txt, Source/Lib/Common/ASM_SSE4_1/CMakeLists.txt, Source/Lib/Common/ASM_SSSE3/CMakeLists.txt, Source/Lib/Common/CMakeLists.txt
Now, it's obvious which options run on which configurations.
*Ready!*
=> Simplify CMake Flag checkers

ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch, ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
1. Fix the last frame coded data missing issue.
2. Correct the forced idr interface implementation.
3. Correct the level interface defination.
4. Add YUV420 10-bits support.
=> [FFmpeg Plugin] Fix several SVT AV1 plugin issues.

Source/Lib/Encoder/Codec/EbEncHandle.c
There is no main10 profile for AV1
Signed-off-by: Zhong Li <zhong.li@intel.com>
=> Fix the wrong profile message

test/e2e_test/DummyVideoSource.h, test/e2e_test/E2eTestVectors.h, test/e2e_test/SvtAv1E2EFramework.cc, test/e2e_test/SvtAv1E2ETest.cc, test/e2e_test/VideoSource.cc, test/e2e_test/VideoSource.h
1. Add dummy video source (color bar) support in e2e test.
=> dummy video source support in e2e test

test/DeblockTest.cc, test/loopfilter_ref.h
1. Test the sse2 implementation of in-loop filter.
=> Add unit test for in-loop filter

Source/Lib/Common/Codec/EbRateDistortionCost.c
Kernel work ~1.3 times faster, for Debug, and RelWithDebInfo builds.
=> Optimization kernel av1_cost_coeffs_txb()

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbProductCodingLoop.c
Kernels work 2.7 faster on msvc and 4.3 faster on linux
=> Optimizing kernels construct_best_sorted_arrays_md_stage_2/3.

Source/Lib/Common/ASM_AVX2/convolve_avx2.c, Source/Lib/Common/ASM_SSE2/subtract_sse2.asm, Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c, Source/Lib/Common/Codec/EbCodingLoop.c, Source/Lib/Common/Codec/EbCodingUnit.h, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbEntropyCoding.c, Source/Lib/Common/Codec/EbInterPrediction.c, Source/Lib/Common/Codec/EbInterPrediction.h, Source/Lib/Common/Codec/EbMdRateEstimation.h, Source/Lib/Common/Codec/EbModeDecision.c, Source/Lib/Common/Codec/EbModeDecision.h, Source/Lib/Common/Codec/EbModeDecisionProcess.h, Source/Lib/Common/Codec/EbPictureControlSet.h, Source/Lib/Common/Codec/EbPictureDecisionProcess.c, Source/Lib/Common/Codec/EbProductCodingLoop.c, Source/Lib/Common/Codec/EbRateDistortionCost.c, Source/Lib/Common/Codec/EbResourceCoordinationProcess.c, Source/Lib/Common/Codec/EbSequenceControlSet.h, Source/Lib/Common/Codec/EbTemporalFiltering.c, Source/Lib/Common/Codec/aom_dsp_rtcd.h, Source/Lib/Encoder/Codec/EbEncHandle.c
adding inter-inter compound mode: 
on top of Average compound mode, we add Distance based, Difference based, and Wedge compound modes
bd rate gain of ~2.3% with speed loss of ~30% (when MD classes are on)
=> Pr compound

Source/App/EncApp/EbAppConfig.c
- Fix Description for `-num-hme-w` to match pattern
`number_hme_search_region_in_width` => `NumberHmeSearchRegionInWidth`
- Don't pad width of last column with trailing spaces/tab
Taken together, these changes allow the `-help` output to fit in an 80-character-wide terminal without wrapping unnecessarily.
Before:
<details>
<summary><code>SvtAv1EncApp -help</code></summary>
(Note horizontal scrolling of output block.)
```
-------------------------------------------
SVT-AV1 Encoder
TOKEN                    	DESCRIPTION              	INPUT TYPE               	
-nch                     	NumberOfChannels         	Single input             	
-i                       	InputFile                	Single input             	
-b                       	StreamFile               	Single input …
```
=> SvtAv1EncApp: Improve -help formatting

test/PictureAdditionTest.cc
1. add unit tests for picture_addition_kernel{m}x{n}_{sse,sse2}_intrin,
picture_addition_kernel{m}x{n}_av1_sse2_intrin,
picture_addition_kernel16bit_sse2_intrin test
=> Add unit tests for picture addition functions

test/NoiseExtractTest.cc
1. add unit tests for noise_extract_luma_weak, noise_extract_luma_weak_lcu,
noise_extract_luma_strong, noise_extract_chroma_weak and
noise_extract_chroma_strong;
=> Add unit test for NoiseExtract functions

test/IntraBcUtilTest.cc
Add unit test for av1_is_dv_valid
=> Add unit test for intrabc util function

Source/Lib/Common/Codec/EbCodingLoop.c, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbFullLoop.c
Description
Remove the extra QP offset in the 10 bit coding loop
Authors
@anaghdin
Type of change
Bug fix
=> QP fix for 10 bit coding

.travis.yml, ffmpeg_plugin/README.md
- Updates Linux build environment to Ubuntu Bionic 18.04
- Updates macOS build environment to macOS 10.14 with Xcode 11.0
- Update FFmpeg to 4.2 branch
@1480c1 Could you review?
=> Travis maintenance: Update build environments, FFmpeg

Source/Lib/Common/Codec/EbProductCodingLoop.c
Align with the other calls in the mode decision
=> Align remaining 10b distortion function calls in MD

Source/Lib/Common/Codec/EbPictureControlSet.c, Source/Lib/Common/Codec/EbReferenceObject.c
fixes https://github.com/OpenVisualCloud/SVT-AV1/issues/600
=> fix leaks for encmode 0

Build/linux/build.sh
Allows for custom c,cpp, and asm compiler
Allows for custom generator
=> script: redo build.sh

Source/Lib/Common/ASM_SSE2/EbPackUnPack_Intrinsic_SSE2.c
1. shift the data before pack.
=> Fix bug in eb_enc_msb_un_pack2d_sse2_intrin

.travis.yml
About 5 seconds quicker and doesn't immediately stop the job
=> Style check: split git grep for trs, use git ls-tree, sed, don't use travis_terminate

test/e2e_test/SvtAv1E2ETest.cc
1. modify the screen coding config to cover the intrabc mode.
=> Modify e2e test to increase the coverage

test/MotionEstimationTest.cc
1. add aom_sad{4,8,16,32}x{4,8,16,32} func test
2. add aom_sad{4,8,16,32}x{4,8,16,32}x4d func test
=> Add more aom_sad func test

test/e2e_test/DummyVideoSource.h, test/e2e_test/E2eTestVectors.h, test/e2e_test/RefDecoder.cc, test/e2e_test/SvtAv1E2EFramework.cc, test/e2e_test/SvtAv1E2ETest.cc, test/e2e_test/VideoFrame.h, test/e2e_test/VideoSource.cc, test/e2e_test/VideoSource.h, test/e2e_test/Y4mVideoSource.cc, test/e2e_test/YuvVideoSource.cc
1. Add YUV 422 and YUV 444 support in video source
=> Add YUV422 and YUV444 support unit tests in video source

test/HbdVarianceTest.cc
Added unit test and test cases for high bit-depth variance
calculation.
=> Add high bit-depth variance unit test

Source/App/EncApp/EbAppConfig.c
=> Fix issue #664: seg fault when reading input file

Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c, Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h, Source/Lib/Common/Codec/EbAvcStyleMcp.c, Source/Lib/Common/Codec/EbAvcStyleMcp.h, test/AVCStyleMcpTest.cc
1. add unit tests for functions in avc_style_uni_pred_luma_if_function_ptr_array
2. add reference functions
=> Add AVC Mcp test

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbEncDecProcess.c, Source/Lib/Common/Codec/EbModeDecision.c, Source/Lib/Common/Codec/EbModeDecisionProcess.c, Source/Lib/Common/Codec/EbModeDecisionProcess.h, Source/Lib/Common/Codec/EbProductCodingLoop.c
Added eight-pel to the predicted ME 
- YBdrate gain in 360p M0 is ~0.7%
- Speed drop in 360p M0 is ~1.5%.
=> eighth_pel_precision

Source/Lib/Common/ASM_AVX512/pickrst_avx512.c
Fix build error when enabling AVX512
=>  Fix AVX512 build

Source/Lib/Common/ASM_AVX2/wiener_convolve_avx2.c, Source/Lib/Common/Codec/convolve.c
Mismatch issue in wiener convolve unit test
closes #547
=> Fix Issue #547

test/PsnrTest.cc, test/TestEnv.c
Add unit test of PSNR calculation.
=> Add PSNR unit test

test/TemporalFilterTest.cc
1.add unit test for av1_apply_temporal_filter_sse4_1.
=> Add temporal filter test

Source/Lib/Common/Codec/EbAdaptiveMotionVectorPrediction.c
Fix GCC 8 compile warning
Closes #647 
**Author**
@DesWurstes 
@chkngit 
@okhlif
build
=> Fix GCC 8 compile warning

Source/Lib/Common/Codec/EbModeDecisionProcess.c
change the allocation of scratch_candidate_buffer to fix the memory leak
=> Fix memory leak 

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbInterPrediction.c, Source/Lib/Common/Codec/EbModeDecision.c, Source/Lib/Common/Codec/EbModeDecisionProcess.h, Source/Lib/Common/Codec/EbProductCodingLoop.c
NEW_NEAR & NEAR_NEW support
Closes #715 
**Author**
@chkngit
@okhlif
Enhancement
BDR gain is 0.04% [All objective-fast1 clips ]
No memory change
Speed cost is about 3% [4 core machine]
=> NEW_NEAR & NEAR_NEW support

test/TemporalFilterTest.cc
1.add hbd temporal filter func test
- svt_av1_highbd_apply_temporal_filter_sse4_1
- svt_av1_apply_temporal_filter_sse4_1
Closes #718
=> add hbd temporal filter test

Source/API/EbSvtAv1Enc.h, Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppContext.c, Source/Lib/Common/ASM_SSE4_1/filterintra_sse4.c, Source/Lib/Common/Codec/EbCodingLoop.c, Source/Lib/Common/Codec/EbCodingUnit.h, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbEntropyCoding.c, Source/Lib/Common/Codec/EbIntraPrediction.c, Source/Lib/Common/Codec/EbMdRateEstimation.c, Source/Lib/Common/Codec/EbModeDecision.c, Source/Lib/Common/Codec/EbModeDecision.h, Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c, Source/Lib/Common/Codec/EbPictureControlSet.h, Source/Lib/Common/Codec/EbProductCodingLoop.c, Source/Lib/Common/Codec/EbRateDistortionCost.c, Source/Lib/Common/Codec/aom_dsp_rtcd.h, Source/Lib/Encoder/Codec/EbEncHandle.c, Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
filter intra prediction
Closes #713
updates #622 
**Author**
@chkngit 
@okhlif 
BDR gain is 0.18% [All objective-fast1 clips ]
memory increase is about 2%
Speed cost is about 3% [4 core machine]
=> Filter intra prediction

Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c, Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h, test/PictureOperatorTest.cc
1. add picture copy, average func test
- picture_average_kernel_sse2_intrin
- picture_average_kernel1_line_sse2_intrin
- picture_copy_kernel_sse2
=> add picture operator test

Source/Lib/Common/Codec/EbCodingLoop.c, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbInterPrediction.c, Source/Lib/Common/Codec/EbInterPrediction.h, Source/Lib/Common/Codec/EbModeDecision.c, Source/Lib/Common/Codec/EbMotionEstimation.c, Source/Lib/Common/Codec/EbProductCodingLoop.c, Source/Lib/Common/Codec/EbTemporalFiltering.c, Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
10bit upgrade 
Update #622 
**Author**
@okhlif 
New feature
=> 10bit upgrade

test/FilterIntraPredTest.cc
1. Add unit test of filter intra predictor:
- eb_av1_filter_intra_predictor_sse4_1
=> Add filter intra predictor unit test

Source/App/EncApp/EbAppInputy4m.c, Source/App/EncApp/EbAppProcessCmd.c
check on config->input_file instead of  cfg->input_file_is_fifo for reading from unnamed pipe
=> Bug Fix: Reading from unnamed pipe

Docs/svt-av1_encoder_user_guide.md
=> Document TargetBitRate

Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c
Fix memory leak caused by memory not being freed introduced with ADD_MDC_FULL_COST
=> Memory leak fix

Source/Lib/Common/Codec/EbFullLoop.c
=> Fix the r2r which is caused by tx search in encdec

Source/Lib/Common/Codec/EbCodingLoop.c, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbModeDecisionConfiguration.c, Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.c, Source/Lib/Common/Codec/EbPictureDecisionProcess.c, Source/Lib/Common/Codec/EbProductCodingLoop.c
atb 10bit upgrade
Update #622 
@okhlif
New feature
- Speed 3% on 4 core machine (hbd-md 0) 
-  BDR 0.75% gain over 7 360p 10-bit test sequences ( enc-mode 0  hbd-md 0 )
=> Atb 10bit support in encdec

Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h, Source/Lib/Common/ASM_AVX2/EbPictureOperators_AVX2.h, Source/Lib/Common/ASM_AVX2/EbPictureOperators_Inline_AVX2.h, Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c, Source/Lib/Common/ASM_AVX2/pickrst_avx2.c, Source/Lib/Common/ASM_AVX2/pickrst_avx2.h, Source/Lib/Common/ASM_AVX512/EbPictureOperators_Intrinsic_AVX512.c, Source/Lib/Common/ASM_AVX512/pickrst_avx512.c, Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c, Source/Lib/Common/ASM_SSE2/synonyms.h, Source/Lib/Common/Codec/EbCodingLoop.c, Source/Lib/Common/Codec/EbModeDecisionConfiguration.c, Source/Lib/Common/Codec/EbPictureOperators.c, Source/Lib/Common/Codec/EbPictureOperators.h, Source/Lib/Common/Codec/EbProductCodingLoop.c, Source/Lib/Common/Codec/aom_dsp_rtcd.c, Source/Lib/Common/Codec/aom_dsp_rtcd.h, test/ResidualTest.cc
Speed comparing with avx2:
32x  8:   1.16
32x 16:   1.27
32x 32:   1.30
32x 64:   1.30
64x 16:   1.56
64x 32:   1.67
64x 64:   1.69
64x128:   1.33
128x 64:   1.68
128x128:   1.09
=> [SIMD] Add residual_kernel8bit_avx512()

test/OBMCSadTest.cc
add unit tests for OBMC SAD:
- obmc_sad_w4_avx2
- obmc_sad_w8n_avx2
=> Add OBMC SAD unit test

Docs/svt-av1_encoder_user_guide.md
Simple 1 pass and 2 pass encoding examples
=> Sample commands

Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c, Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h, Source/Lib/Common/C_DEFAULT/EncodeTxbRef_C.c, Source/Lib/Common/C_DEFAULT/EncodeTxbRef_C.h, Source/Lib/Common/Codec/EbHmCode.c, Source/Lib/Common/Codec/EbHmCode.h, Source/Lib/Common/Codec/EbMeSadCalculation.c, Source/Lib/Common/Codec/EbMeSadCalculation.h, Source/Lib/Common/Codec/aom_dsp_rtcd.c, Source/Lib/Common/Codec/aom_dsp_rtcd.h, test/EbSatdTest.cc, test/EncodeTxbAsmTest.cc, test/PictureOperatorTest.cc, test/SadTest.cc
Fix for picture_average_kernel1_line
Fix for compute8x8_satd_u8
Fix for eb_av1_get_nz_map_contexts
Fix for initialize_buffer_32bits
=> Implementation missing c fn with UT

Source/Lib/Common/Codec/EbEncodeContext.h, Source/Lib/Common/Codec/EbPictureDecisionProcess.c
=> Fix non-8 aligned gop size

Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c
Fix issues:
1. The data of this ResidualSum avx2 funtion is out of bounds in avx2 register when size = 8 ;
2. The ResidualSum avx2 function has no implementation code when size = 64;
=> Fix issue in unit test: ResidualSumTest.MatchTest/4,13 and 14

Source/Lib/Common/Codec/EbInterPrediction.c
The predictions relate to a list 1 frame.
=> Inter prediction: fix a typo in the comments

Source/Lib/Common/ASM_AVX2/EbComputeSAD_AVX2.h, Source/Lib/Common/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c, Source/Lib/Common/ASM_AVX2/EbPictureOperators_Inline_AVX2.h, Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c, Source/Lib/Common/C_DEFAULT/EbComputeSAD_C.c, Source/Lib/Common/Codec/EbComputeSAD.h, Source/Lib/Common/Codec/EbPictureOperators.c, Source/Lib/Common/Codec/EbPictureOperators.h, Source/Lib/Common/Codec/aom_dsp_rtcd.c, Source/Lib/Common/Codec/aom_dsp_rtcd.h, test/SadTest.cc, test/SpatialFullDistortionTest.cc
AVX2 kernel sad_16bit_kernel() work faster ~14 times.
AVX2 kernel  full_distortion_kernel16_bits() work faster ~3.5 times.
=> Implement AVX2 kernels: full_distortion_kernel16_bits, sad_16bit_kernel

Source/Lib/Common/Codec/EbInterPrediction.c
This removes av1_make_masked_inter_predictor_hbd and should have no impact
on the bit stream.
=> Single av1_make_masked_inter_predictor function for 8 and 10 bit streams

Source/Lib/Common/Codec/EbEncDecProcess.c, Source/Lib/Common/Codec/EbPictureDecisionProcess.c, Source/Lib/Common/Codec/aom_dsp_rtcd.c
Fix typo in OFF code
Re-enable ATB for screen content
=> Fix typo from 793785c commit

Source/Lib/Common/ASM_AVX2/EbNoiseExtractAVX2.c, Source/Lib/Common/ASM_AVX2/EbNoiseExtractAVX2.h, Source/Lib/Common/Codec/EbPictureAnalysisProcess.c, test/NoiseExtractTest.cc
AVX2 code assume that width is divisible by 64.
Added support for width divisible by 16 and 32
=> Fix errors in UT for NoiseExtractTest

test/GlobalMotionUtilTest.cc, test/api_test/SvtAv1EncParamsTest.cc, test/api_test/params.h
1. add unit tests for RANSAC functions:
- ransac_affine
- ransac_rotzoom
- ransac_translation
- ransac_affine_double_prec
- ransac_rotzoom_double_prec
- ransac_translation_double_prec
2. add api parameter tests
=> Add unit tests for global motion utility

Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c
move tile info setting before releasing for good coding style.
=> umv0 resource coordinate refine

Source/Lib/Common/Codec/EbModeDecisionProcess.c
This issue #852 is caused by some variables uninitialized.
=> fix assert failed when setting adaptive_quantization = 1 with debugging build

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbPictureDecisionProcess.c
=> fix cra for altref

Source/Lib/Common/Codec/EbPictureDecisionProcess.c, Source/Lib/Common/Codec/EbPredictionStructure.c
- Removed tmvp constraint for minigop8 under minigop16 config
- Expand the RPS tables to allow for the implementation of other
prediction structures
#207
=> RPS clean up and improvements

.github/workflows/style-check.yml, .travis.yml, Source/Lib/Common/Codec/EbPictureDecisionProcess.c
Runs in 6 seconds instead of 26 it seems. Idk how trustable those numbers are.
Frees up travis a bit to not have so many stages
@EwoutH and @kylophone, please check
=> Actions: Move style check job over to gh actions

Source/App/EncApp/EbAppConfig.c, Source/Lib/Encoder/Codec/EbEncHandle.c, test/CdefTest.cc, test/GlobalMotionUtilTest.cc, test/PaletteModeUtilTest.cc, test/PictureOperatorTest.cc, test/ResidualTest.cc, test/SadTest.cc, test/SpatialFullDistortionTest.cc, test/TxfmCommon.h
Remove warnings in ./test/  popping up in MacOS.
=> Remove warnings in MacOS

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbEncDecProcess.h, Source/Lib/Common/Codec/EbModeDecisionConfigurationProcess.h, Source/Lib/Common/Codec/EbPictureControlSet.c, Source/Lib/Common/Codec/EbPictureControlSet.h, Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c, Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c, Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.h
- Cleanup functions and sturcutres related to some detectors like grass , aura , skin , blockiness etc...
#668
No impact
=> Cleanup some unused functions and detectors 

.github/workflows/svt-av1.yml
Add a build matrix to test compilation on various compilers.
Additionally set an explicit name for the build machine, so that it is clear on which OS version it runs.
=> Github Actions CI: Add build matrix

Source/Lib/Encoder/Codec/EbInterPrediction.c
use optimized code for eb_av1_convolve_2d_sr, eb_av1_convolve_x_sr and eb_av1_convolve_y_sr
=> use optimized version for convolve intraBC

Source/App/EncApp/EbAppInputy4m.c
Fixed error message condition for y4m format
No impact
=> y4m error message fix

Source/Lib/Encoder/Globals/EbEncHandle.c
Fixed crash for -rc 1 due to wrong super block size
issue #940
=> fix rate control crash

Source/Lib/Common/Codec/EbPictureBufferDesc.c, Source/Lib/Encoder/Codec/EbCodingUnit.c, Source/Lib/Encoder/Codec/EbDlfProcess.c, Source/Lib/Encoder/Codec/EbEncDecSegments.h, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c, Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.c, Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.h, Source/Lib/Encoder/Codec/EbPictureControlSet.c, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbPictureDecisionQueue.c, Source/Lib/Encoder/Codec/EbPictureDecisionQueue.h, Source/Lib/Encoder/Codec/EbPictureDecisionReorderQueue.c, Source/Lib/Encoder/Codec/EbPictureDecisionReorderQueue.h, Source/Lib/Encoder/Codec/EbPictureManagerQueue.c, Source/Lib/Encoder/Codec/EbPictureManagerQueue.h, Source/Lib/Encoder/Codec/EbPictureManagerReorderQueue.c, Source/Lib/Encoder/Codec/EbPictureManagerReorderQueue.h, Source/Lib/Encoder/Codec/EbRateControlProcess.c, Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c, Source/Lib/Encoder/Codec/EbSequenceControlSet.c, Source/Lib/Encoder/Codec/EbSequenceControlSet.h, Source/Lib/Encoder/Codec/EbSystemResourceManager.c, Source/Lib/Encoder/Codec/EbTransQuantBuffers.c, Source/Lib/Encoder/Codec/noise_model.c, test/FilmGrainTest.cc, test/NoiseExtractTest.cc
=> Minor clean up for resource allocation refactoring

.github/workflows/svt-av1.yml
This pull request addresses one of the items in #873 - Implement quick binary check for bitstream changes between PR and master
=> Add binary identical test for Github Actions

Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Fix the crash in debug mode due to md skip
Closes #885  
**Authors**
@anaghdin
Type of change
Bug Fix
Negligible impact for performance
=> Fix the crash in debug mode

Source/Lib/Encoder/ASM_AVX2/highbd_variance_avx2.c, Source/Lib/Encoder/Codec/EbIntraPrediction.c, Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbPsnr.c, Source/Lib/Encoder/Codec/EbRateDistortionCost.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.h, Source/Lib/Encoder/Codec/av1me.c, Source/Lib/Encoder/Codec/av1me.h, Source/Lib/Encoder/Codec/palette.c
This pull requests add the support of the palette tool for 10 bit.
The palette colors are computed in 10 bit from the stream images.
=> Add the palette tool for 10 bit intra frames [No performance PRs after this PR, only cleanups and bugfixes]

.github/workflows/msvc.yml, Source/Lib/Common/ASM_SSE2/CMakeLists.txt, Source/Lib/Encoder/ASM_SSE2/CMakeLists.txt, Source/Lib/Encoder/ASM_SSSE3/CMakeLists.txt
Still haven't added any tests or anything else yet
https://github.com/OpenVisualCloud/SVT-AV1/issues/873
=> Actions/windows: Add MSVC job

test/SadTest.cc
1. fixed sad test data is not initialized when test in "BUF_SMALL" pattern.
failure cases:
~~~
[  FAILED  ] EXTSAD/Extsad_CalculationTest.Extsad_32x32Test/2, where GetParam() = (0, 2)
[  FAILED  ] EXTSAD/Extsad_CalculationTest.Extsad_32x32Test/10, where GetParam() = (2, 2)
[  FAILED  ] CALSAD/sad_CalculationTest.sad_32x32Test/2, where GetParam() = (0, 2)
[  FAILED  ] CALSAD/sad_CalculationTest.sad_32x32Test/10, where GetParam() = (2, 2)
~~~
2. clean-up build warnings in SadTest.cc
=> fix sad unit test failure cases

Config/Sample.cfg, Source/Lib/Encoder/Globals/EbEncHandle.c, test/api_test/SvtAv1EncApiTest.cc, test/api_test/params.h
=> Fix all tests from SvtAv1ApiTests

.github/workflows/style-check.yml, .github/workflows/svt-av1.yml, .travis.yml
**Actions:**
1. Add always to style check on every step so developers will not need to commit multiple times to fix through each error one at a time. This will instead go to the next step even if any of the other steps fail so they can get a complete list of what they need to fix.  
2. Update checkout to v2 on the style check.  
3. Add -10 to clang repo so it can successfully find the clang-10 package.
4. Disable fail-fast on svt-av1 so if a single matrix build fails it will still continue to build the others allowing developers to see if there is just an issue with a specific compiler build or if they are all failing.
**Travis:**
1. Add clang-10 repo so it can successfully find the clang-10 package.
2. Move travis packages to matrix. This makes viewing which packages are actually …
=> Update, Modify, Fix actions/travis

CHANGELOG.md, Source/API/EbSvtAv1.h, Source/Lib/Decoder/CMakeLists.txt, Source/Lib/Encoder/CMakeLists.txt, snap/snapcraft.yaml
- Update the changelog
- Update rev to 0.8.1
=> v0.8.1 tag

ffmpeg_plugin/README.md
Reduces required storage and reduces download times.
CI already uses clone depth 1.
=> FFmpeg plugin: Update readme to use clone depth 1

Source/API/EbSvtAv1Enc.h, Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppContext.c, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbModeDecisionProcess.h, Source/Lib/Encoder/Codec/EbProductCodingLoop.c, Source/Lib/Encoder/Globals/EbEncHandle.c
Add support for a 4th MD stage, in between the previous MD stage 1 and 2.  By default, the 3rd stage is bypassed.
@hguermaz 
Enhancement
The changes are lossless.  No speed or memory overhead.
=> 4th MD Stage

Source/Lib/Encoder/Codec/EbSequenceControlSet.c, Source/Lib/Encoder/Codec/EbSequenceControlSet.h
Reverts OpenVisualCloud/SVT-AV1#1016
causes a crash in -enc-mode 1 with a 1080p resolution
=> Revert "SequenceControlSet Copy"

Source/Lib/Encoder/Codec/EbPictureManagerProcess.c
Revert unintentional change made by #963
Causes a crash with -lp 1
=> Revert unintentional change made by #963

Source/App/DecApp/EbDecAppMain.c, Source/Lib/Common/Codec/EbBlockStructures.h, Source/Lib/Common/Codec/EbDeblockingCommon.c, Source/Lib/Common/Codec/EbDeblockingCommon.h, Source/Lib/Decoder/Codec/EbDecBlock.h, Source/Lib/Decoder/Codec/EbDecHandle.h, Source/Lib/Decoder/Codec/EbDecLF.c, Source/Lib/Decoder/Codec/EbDecLF.h, Source/Lib/Decoder/Codec/EbDecMemInit.c, Source/Lib/Decoder/Codec/EbDecParseBlock.c, Source/Lib/Decoder/Codec/EbDecParseFrame.c, Source/Lib/Decoder/Codec/EbDecParseInterBlock.c, Source/Lib/Decoder/Codec/EbDecParseObu.c, Source/Lib/Decoder/Codec/EbDecPicMgr.c, Source/Lib/Decoder/Codec/EbDecProcess.c, Source/Lib/Decoder/Codec/EbDecProcess.h, Source/Lib/Decoder/Codec/EbDecProcessBlock.c, Source/Lib/Decoder/Codec/EbDecProcessBlock.h, Source/Lib/Decoder/Codec/EbDecProcessFrame.c, Source/Lib/Encoder/ASM_AVX2/cdef_block_avx2.c, Source/Lib/Encoder/Codec/EbDeblockingFilter.c
Optimised Decoder LF flow, recon flow.
Optimised CDEF intrinsic
=> Optimised Decoder LF flow, recon flow and CDEF intrinsic

Source/Lib/Encoder/ASM_AVX512/EbComputeSAD_Intrinsic_AVX512.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.h
add missing AVX512 code for FullPel search ( get_eight_horizontal_search_point_results_8x8_16x16_pu_avx512_intrin)
=> FullPel AVX512

Source/Lib/Common/Codec/EbDeblockingCommon.c, Source/Lib/Common/Codec/EbDeblockingCommon.h, test/DeblockTest.cc
1. add more test cases for deblocking:
- aom_lpf_{horizontal, vertical}_{4, 6, 8}_sse2
- aom_highbd_lpf_{horizontal, vertical}_{4, 8}_sse2
2. add missing implementation of c reference: aom_lpf_vertical_6_c
=> Add more test cases for deblocking test

Config/Sample.cfg, Docs/svt-av1_encoder_user_guide.md, Source/API/EbSvtAv1Enc.h, Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppContext.c, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbPredictionStructure.c, Source/Lib/Encoder/Codec/EbPredictionStructure.h, Source/Lib/Encoder/Globals/EbEncHandle.c, ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch, ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch, gstreamer-plugin/gstsvtav1enc.c, test/api_test/SvtAv1EncParamsTest.cc, test/api_test/params.h, test/e2e_test/SvtAv1E2ETest.cc
Format and add more details to help menu
Update encoder user guide 
No impact
#779
#945
=> Improve help menu:

Source/Lib/Common/Codec/EbBlockStructures.h, Source/Lib/Common/Codec/EbCabacContextModel.h, Source/Lib/Common/Codec/EbInterPrediction.c, Source/Lib/Common/Codec/EbInterPrediction.h, Source/Lib/Common/Codec/EbIntraPrediction.h, Source/Lib/Decoder/Codec/EbDecBlock.h, Source/Lib/Decoder/Codec/EbDecCdef.c, Source/Lib/Decoder/Codec/EbDecCdef.h, Source/Lib/Decoder/Codec/EbDecInterPrediction.c, Source/Lib/Decoder/Codec/EbDecInterPrediction.h, Source/Lib/Decoder/Codec/EbDecIntraPrediction.c, Source/Lib/Decoder/Codec/EbDecInverseQuantize.c, Source/Lib/Decoder/Codec/EbDecMemInit.c, Source/Lib/Decoder/Codec/EbDecParseBlock.c, Source/Lib/Decoder/Codec/EbDecParseHelper.c, Source/Lib/Decoder/Codec/EbDecParseHelper.h, Source/Lib/Decoder/Codec/EbDecParseInterBlock.c, Source/Lib/Decoder/Codec/EbDecParseInterBlock.h, Source/Lib/Decoder/Codec/EbDecParseObu.c, Source/Lib/Decoder/Codec/EbDecProcess.c, Source/Lib/Decoder/Codec/EbDecProcessBlock.c, Source/Lib/Decoder/Codec/EbDecProcessFrame.c, Source/Lib/Decoder/Codec/EbObuParse.h, Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c, Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.h, Source/Lib/Encoder/Codec/EbCodingUnit.h, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbEntropyCoding.h
Separation of the encoder library into encoder and common. Removal of dependency on EntropyCoding in the decoder
=> Enc common separation 7

Config/Sample.cfg, Source/App/EncApp/EbAppConfig.c
fixes https://github.com/OpenVisualCloud/SVT-AV1/issues/1048
=> enable ErrorFile for configuration file 

Source/Lib/Common/Codec/EbCommonUtils.h, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbUtility.c, Source/Lib/Decoder/Codec/EbDecParseBlock.c, Source/Lib/Encoder/Codec/EbCodingLoop.c, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbFullLoop.c, Source/Lib/Encoder/Codec/EbMdRateEstimation.c, Source/Lib/Encoder/Codec/EbMdRateEstimation.h, Source/Lib/Encoder/Codec/EbModeDecisionProcess.c, Source/Lib/Encoder/Codec/EbModeDecisionProcess.h, Source/Lib/Encoder/Codec/EbPictureControlSet.c, Source/Lib/Encoder/Codec/EbPictureControlSet.h, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbProductCodingLoop.c, Source/Lib/Encoder/Codec/EbRateDistortionCost.c, Source/Lib/Encoder/Codec/EbTransformUnit.h
Tx Size Search for Depth_2.
Tx Size Search for Block Copy.
@hguermaz 
Enhancement.
| -- | --
| -9.75% | -0.343%|
=> Tx Size Search for Depth_2

Docs/svt-av1_decoder_user_guide.md, Docs/svt-av1_encoder_user_guide.md, LICENSE_AOM.md, README.md, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c, Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c, Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c, Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbPictureManagerProcess.c, Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c, Source/Lib/Encoder/Codec/EbSequenceControlSet.h, Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c
* Added description from the encoder design document to most kernels using the conventional style 
* Initial scs commit cleanups and comments
* Added libaom license file and a reference to it in the Readme
* Updated users guide of the encoder and decoder
* Updated Readme file to not be encoder exclusive
* No impact
=> Added more details to most kernels

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbModeDecisionProcess.h, Source/Lib/Encoder/Codec/EbProductCodingLoop.c
_________________________________________________________________________________
- code refactor 
- algorithm simplification 
_________________________________________________________________________________
@okhlif 
_________________________________________________________________________________
Clean up
Enhancement.
_________________________________________________________________________________
Data generated on the full objective-1-fast data set in context in enc-mode 0.
Speed Deviation | BD-Rate Deviation
-- | --
~-3% | -0.07%
=> nic cleanup

Source/App/EncApp/EbAppProcessCmd.c, Source/Lib/Encoder/Codec/EbEncodeContext.h, Source/Lib/Encoder/Codec/EbPacketizationProcess.c, Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.c, Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.h, test/e2e_test/SvtAv1E2EFramework.cc
=> packetization_kernel: pack entire temproal unit for a output buffer

Source/Lib/Encoder/Codec/EbProductCodingLoop.c
Added back input_origin_index update for the hybrid mode.
=> 10BIT bug fix

Source/Lib/Encoder/Globals/EbEncHandle.c
=> Adopt sb 128

test/NoiseExtractTest.cc
1. add memory zero to fix NoiseExtractTest failure after optimized eb_picture_buffer_desc_dctor ([PR1094](https://github.com/OpenVisualCloud/SVT-AV1/pull/1094))
=> Modify NoiseExtractTest

Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c, Source/Lib/Decoder/Codec/EbDecLF.c
Bug fixes in inv_transform sse3 functions related to identity transform case
Bug fix in decoder LF MT path
=> Bug fix in common inv_transform sse3 functions and decoder LF-MT

Source/Lib/Common/Codec/EbBitstreamUnit.c, Source/Lib/Common/Codec/EbBitstreamUnit.h, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbEntropyCoding.h, Source/Lib/Encoder/Codec/EbEntropyCodingObject.h, Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c, Source/Lib/Encoder/Codec/EbPacketizationProcess.c
this is a pr only improve code readability. 
It's no impact to speed or quality.
=> Bitstream: refact input params and hide implement details to make code more readable.

Source/Lib/Encoder/Codec/EbPacketizationProcess.c
we will miss last frame if it is a show existing frame
test command line:
-i blue_sky_360p_60f.yuv -o rec.yuv -intra-period 200 -enc-mode 8 -n 25 -q 40 -lp 1 -lad 0 -b 1.ivf -w 640 -h 360
=> packetization_kernel: fix missed last frame

test/wiener_convolve_test.cc
1. fixed memory alignment issue in memory allocation in wiener convolve tests
=> Fix wiener convolve test crash

Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c, Source/Lib/Encoder/Codec/EbPictureControlSet.c, Source/Lib/Encoder/Codec/EbPictureControlSet.h, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbPictureManagerProcess.c, Source/Lib/Encoder/Codec/EbRateControlProcess.c, Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c, Source/Lib/Encoder/Codec/EbSequenceControlSet.c, Source/Lib/Encoder/Codec/EbSequenceControlSet.h, Source/Lib/Encoder/Codec/EbSourceBasedOperationsProcess.c, Source/Lib/Encoder/Globals/EbEncHandle.c
Cleaned up pcs , ppcs , scs
No impact
=> Structures cleanup

Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c, Source/Lib/Encoder/Codec/EbEncInterPrediction.c
=> Fix the r2r caused by wrong mv in warp case

Source/Lib/Encoder/Codec/EbProductCodingLoop.c
=> Fix the r2r caused by the wrong neighbor array

Docs/svt-av1_encoder_user_guide.md, Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppContext.c, Source/App/EncApp/EbAppMain.c
Enhance help menu and command line options
Update encoder user guide to match the help menu 
#779
#945
No impact
=> Improve CLI 

.github/workflows/msvc.yml
1. add unit tests and e2e tests support in GitHub CI windows workflow.
=> Add GitHub CI configuration for Windows

Source/App/EncApp/EbAppConfig.c
Windows debug build shows: 
Run-Time Check Failure #2 - Stack around the variable 'message' was corrupted.
=> Fix windows debug build and fix typo

Source/Lib/Encoder/Codec/EbRestProcess.c
Bug Fix: initialize is_16bit_pipeline flag under enhanced_unscaled_picture_ptr
=> Segfault fix

Source/App/EncApp/EbAppConfig.c
=> fix INTRA_ANGLE_DELTA_NEW_TOKEN mapping

Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c
Put the post_object out of the while-loop.
In some cases, the pcs is released in PAK kernel before we quit the
while-loop
Fixes #1158 
=> Fix the r2r in entropy kernel

Source/App/EncApp/EbAppConfig.c, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbPictureBufferDesc.c, Source/Lib/Common/Codec/EbPictureBufferDesc.h, Source/Lib/Encoder/Codec/EbDeblockingFilter.c, Source/Lib/Encoder/Codec/EbDlfProcess.c, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbPictureControlSet.c, Source/Lib/Encoder/Codec/EbPictureControlSet.h, Source/Lib/Encoder/Codec/EbRestProcess.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.h, Source/Lib/Encoder/Globals/EbEncHandle.c
Cherry-picked and rebased from the `cs2` branch. 
Co-authored-by: Jing Li <jing.b.li@intel.com>
Co-authored-by: chkngit <42250551+chkngit@users.noreply.github.com>
=> fix encoding for non multiple-of-8 pictures

Source/Lib/Common/Codec/EbBitstreamUnit.c, Source/Lib/Common/Codec/EbInterPrediction.c, Source/Lib/Common/Codec/EbIntraPrediction.c
Most of these were suggested by Cppcheck
=> Various fixes for cleaner code

Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c
=> Fix R2R caused by missing chroma data at boundary(#1079)

Source/Lib/Common/Codec/EbThreads.c
Clean up and fix the pthread creation and error handling code a bit.
=> Fix pthread creation error handling

.github/workflows/macos.yml, CMakeLists.txt, Source/Lib/Common/ASM_SSE2/CMakeLists.txt, Source/Lib/Common/ASM_SSE2/x64inc.asm, Source/Lib/Common/ASM_SSSE3/CMakeLists.txt, Source/Lib/Common/CMakeLists.txt, Source/Lib/Decoder/CMakeLists.txt, Source/Lib/Encoder/ASM_SSE2/CMakeLists.txt, Source/Lib/Encoder/ASM_SSSE3/CMakeLists.txt, Source/Lib/Encoder/CMakeLists.txt
Based off code from x265's CMakeLists
Required some "Hackish" code due to the unique structure.
Closes #219
=> CMake: Add code for Xcode generation

.github/workflows/ci.yml, gstreamer-plugin/CMakeLists.txt, gstreamer-plugin/README.md, gstreamer-plugin/gstsvtav1enc.c, gstreamer-plugin/meson.build
=> [GStreamer]Update SVT-AV1 interfaces

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Encoder/Codec/EbProductCodingLoop.c
=> Add boundary check for predictive_me_search

Docs/svt-av1_encoder_user_guide.md, Source/App/EncApp/EbAppConfig.c
=> Support stdout for output

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbUtility.c, Source/Lib/Common/Codec/EbUtility.h, Source/Lib/Common/Codec/common_dsp_rtcd.c, Source/Lib/Common/Codec/common_dsp_rtcd.h, Source/Lib/Encoder/Codec/EbCodingLoop.c, Source/Lib/Encoder/Codec/EbDeblockingFilter.c, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbEncInterPrediction.c, Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c, Source/Lib/Encoder/Codec/EbModeDecision.c, Source/Lib/Encoder/Codec/EbNeighborArrays.c, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbProductCodingLoop.c, Source/Lib/Encoder/Codec/EbRestProcess.c, Source/Lib/Encoder/Codec/EbSegmentation.c
move back log2f/LOG2F to EbDefinitions.h/EbUtility.h due to rate degradation caused by moving it to common_dsp_rtcd.c until further investigation
=> revert log2f changes due to rate loss

Source/Lib/Encoder/Codec/k_means_template.h
=> Fix clang-cl build error

test/e2e_test/E2eTestVectors.h
1. Replaces hard coding of CLI token with getting from SvtAv1EncApp helper
=> Fixed CLI string in E2E tests

Source/Lib/Encoder/Globals/EbEncHandle.c
#1245 issue fixed, tiny fixing by setting enable_manual_pred_struct to EB_FALSE
=> Fix: EbSvtAv1EncConfiguration.enable_manual_pred_struct is not set to EB_FALSE by default 

Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c, Source/Lib/Encoder/Codec/EbTemporalFiltering.c
=> Fix R2R in non-8 aligned resolution streams

Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h
=> Fix frames_to_be_encoded for non-file input

Source/Lib/Encoder/Codec/EbProductCodingLoop.c
=> Add protection for out of boundary

.travis.yml
Removed the ffmpeg and gstreamer patch and binary identical jobs
Removed references to deleted jobs
=> Travis-ci: Cleanup old jobs and yaml file

Source/Lib/Encoder/Globals/EbEncHandle.c
=> Resolve the hang of 31B with lp=1 which is caused by lack of PA surfaces

Source/Lib/Encoder/Codec/EbProductCodingLoop.c
=> Fix the R2R in M2 caused by uninitialized parameters

.github/workflows/sanitizers.yml, Source/Lib/Common/Codec/EbThreads.c
=> CI: Add sanitizer runs

Build/windows/build.bat
Whichever one comes last will be the one that is built, Should help with people who want to choose their build type.
=> build.bat: Add static and shared options

Source/Lib/Encoder/Globals/EbEncHandle.c
RC only works with sb 64x64
Closes issue #1309 
No impact
=> Fix RC crash

Source/Lib/Encoder/ASM_AVX2/EbTemporalFiltering_AVX2.c, Source/Lib/Encoder/Codec/EbTemporalFiltering.c, Source/Lib/Encoder/Codec/EbTemporalFiltering.h, Source/Lib/Encoder/Codec/aom_dsp_rtcd.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.h, test/TemporalFilterTestPlanewise.cc
Speed-up compared to C implementation ~3.5x
=> Implementation of av1_apply_temporal_filter_planewise_hbd_avx2

Config/Sample.cfg, Docs/svt-av1_encoder_user_guide.md, Source/API/EbSvtAv1Enc.h, Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppContext.c, Source/Lib/Encoder/Globals/EbEncHandle.c, gstreamer-plugin/gstsvtav1enc.c
Add the ability to pin/unpin to/from cores for any number of cores(used to be restricted to 1 core)
Tune buffer settings to get a better tradeoff point for user/real time going from lp 1 to lp 8
=> Multi thread buffer tuning

Source/Lib/Encoder/ASM_AVX2/highbd_variance_avx2.c, Source/Lib/Encoder/Codec/EbTemporalFiltering.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.h, test/HbdVarianceTest.cc
For 1080p 10-bit video in "preset 8" ~2.5% speedup
=> Implementation of variance_highbd_avx2 kernel

Source/Lib/Common/ASM_AVX2/EbPackUnPack_Intrinsic_AVX2.c, Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c, Source/Lib/Common/ASM_AVX2/cfl_avx2.c, Source/Lib/Common/ASM_AVX2/convolve_avx2.h, Source/Lib/Common/ASM_AVX2/highbd_convolve_2d_avx2.c, Source/Lib/Common/ASM_AVX2/highbd_convolve_avx2.c, Source/Lib/Common/ASM_SSE4_1/EbBlend_a64_mask_sse4.c, Source/Lib/Common/ASM_SSE4_1/highbd_warp_plane_sse4.c, Source/Lib/Common/C_DEFAULT/EbIntraPrediction_c.c, Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c, Source/Lib/Common/Codec/EbPictureOperators.c, Source/Lib/Common/Codec/EbPictureOperators.h, Source/Lib/Common/Codec/EbUtility.c, Source/Lib/Common/Codec/common_dsp_rtcd.c, Source/Lib/Common/Codec/common_dsp_rtcd.h
Resolves more cppcheck issues
None
@1480c1
=> Cppcheck-point 2

.github/workflows/macos.yml
makes the unit tests match the regular macOS checks
Might fix the issues @xuguangxin found in his PR
none
@1480c1
=> macOS: Run brew upgrade before unit test building

Source/Lib/Common/Codec/EbMalloc.h, Source/Lib/Encoder/ASM_AVX2/EbCdef_AVX2.c, Source/Lib/Encoder/ASM_AVX512/EbCdef_AVX512.c, Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c, Source/Lib/Encoder/Codec/EbCdefProcess.c, Source/Lib/Encoder/Codec/EbDeblockingFilter.c, Source/Lib/Encoder/Codec/EbDlfProcess.c, Source/Lib/Encoder/Codec/EbEncCdef.c, Source/Lib/Encoder/Codec/EbEncIntraPrediction.c, Source/Lib/Encoder/Codec/EbEntropyCodingProcess.c, Source/Lib/Encoder/Codec/EbGlobalMotionEstimation.c, Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.h, test/CdefTest.cc
=> Cppcheck-point 4

Source/Lib/Common/ASM_AVX2/av1_inv_txfm_avx2.c, Source/Lib/Common/ASM_AVX2/convolve_avx2.h, Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c, Source/Lib/Common/ASM_AVX2/jnt_convolve_2d_avx2.c, Source/Lib/Common/ASM_AVX2/jnt_convolve_avx2.c, Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.c, Source/Lib/Common/Codec/EbIntraPrediction.c, Source/Lib/Common/Codec/EbInvTransforms.c, Source/Lib/Common/Codec/EbMalloc.c, Source/Lib/Encoder/Codec/EbAdaptiveMotionVectorPrediction.c, Source/Lib/Encoder/Codec/EbCdefProcess.c, Source/Lib/Encoder/Codec/EbDeblockingFilter.c, Source/Lib/Encoder/Codec/EbEncDecSegments.c
Resolves even more cppcheck issues.
I can either roll this into #1335, or keep it separate depending on if it would be easier to review that way.
None
@1480c1
=> Cppcheck-point 3

Source/Lib/Encoder/Codec/EbModeDecision.c
Move "if" to fix valgrind errors from Travis CI:
at 0x5277CD8: unipred_3x3_candidates_injection (EbModeDecision.c:884)
by 0x5285CFA: inject_inter_candidates (EbModeDecision.c:4381)
by 0x528A15D: generate_md_stage_0_cand (EbModeDecision.c:5432)
by 0x531425A: md_encode_block (EbProductCodingLoop.c:6344)
by 0x5318243: mode_decision_sb (EbProductCodingLoop.c:7340)
by 0x5224152: enc_dec_kernel (EbEncDecProcess.c:3410)
by 0x107B86DA: start_thread (pthread_create.c:463)
by 0x10E8F88E: clone (clone.S:95)
at 0x5278524: unipred_3x3_candidates_injection (EbModeDecision.c:1025)
by 0x5285CFA: inject_inter_candidates (EbModeDecision.c:4381)
by 0x528A15D: generate_md_stage_0_cand …
=> Fix for valgrind errors from Travis CI

Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c, Source/Lib/Common/Codec/EbIntraPrediction.c, Source/Lib/Encoder/ASM_AVX2/EbCdef_AVX2.c, Source/Lib/Encoder/ASM_AVX2/EbComputeSAD_Intrinsic_AVX2.c, Source/Lib/Encoder/ASM_AVX2/obmc_variance_avx2.c, Source/Lib/Encoder/ASM_AVX2/palette_avx2.c, Source/Lib/Encoder/ASM_SSE4_1/EbComputeSAD_Intrinsic_SSE4_1.c, Source/Lib/Encoder/ASM_SSSE3/variance_impl_ssse3.c, Source/Lib/Encoder/Codec/EbCodingLoop.c, Source/Lib/Encoder/Codec/EbEncCdef.c, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbEncDecSegments.c, Source/Lib/Encoder/Codec/EbEncInterPrediction.c, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbFullLoop.c, Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c, Source/Lib/Encoder/Codec/EbMdRateEstimation.c, Source/Lib/Encoder/Codec/EbModeDecisionProcess.h, Source/Lib/Encoder/Codec/EbPacketizationProcess.c, Source/Lib/Encoder/Codec/EbPictureAnalysisProcess.c, Source/Lib/Encoder/Codec/EbPredictionStructure.c, Source/Lib/Encoder/Globals/EbEncHandle.c
Fixes some more cppcheck issues
@1480c1
=> cppcheck6: variableScope etc

Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c, Source/Lib/Encoder/ASM_AVX2/EbCombinedAveragingSAD_Intrinsic_AVX2.c, Source/Lib/Encoder/ASM_AVX2/palette_avx2.c, Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c, Source/Lib/Encoder/Codec/EbEncCdef.c, Source/Lib/Encoder/Codec/EbEncInterPrediction.c, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbFullLoop.c, Source/Lib/Encoder/Codec/EbModeDecision.c, Source/Lib/Encoder/Codec/EbRateDistortionCost.c, Source/Lib/Encoder/Globals/EbEncHandle.c
smaller PR with just  shadowVariable, knownConditionTrueFalse, & duplicateAssignExpression
@1480c1
=> cppcheck7: shadowVariable, knownConditionTrueFalse, & duplicateAssignExpression

Source/App/EncApp/EbAppConfig.c
Fix --enable-pic-based-rate-est and --enable-intra-edge-skp parameters. 
Eric Lam
Colton Cheung
=> Fix enable-pic-based-rate-est and enable-intra-edge-skp params

Source/API/EbSvtAv1Enc.h
Cosmetics: wihtout -> without
Limin Wang
=> Cosmetics: wihtout -> without

.github/workflows/macos.yml
this should help prevent issues with preinstalled packages stuff such as bazel and bazelisk and we do not care about such preinstalled packages breaking
@1480c1
=> macOS: Set upgrade and install to force

Source/App/EncApp/EbAppConfig.h, Source/Lib/Common/ASM_AVX2/EbMemory_AVX2.h, Source/Lib/Common/ASM_SSE2/EbPictureOperators_Intrinsic_SSE2.c, Source/Lib/Common/ASM_SSSE3/EbHighbdIntraPrediction_Intrinsic_SSSE3.c, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbMalloc.c, Source/Lib/Common/Codec/EbMalloc.h, Source/Lib/Common/Codec/EbUtility.c, Source/Lib/Decoder/Codec/EbDecMemInit.c, Source/Lib/Decoder/Codec/EbDecMemInit.h, Source/Lib/Decoder/Codec/EbDecParseObu.c, Source/Lib/Encoder/Codec/EbProductCodingLoop.c, third_party/fastfeat/fast_9.c
Address some memory related issues from cppcheck
@xuguangxin can you please review the memory related functions, especially in Source/Lib/Common/Codec/EbMalloc.c and Source/Lib/Common/Codec/EbMalloc.h
memcpy stuff /cc @ttrigui 
@1480c1
=> cppcheck: Memory related issues

Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppMain.c, Source/Lib/Encoder/Codec/EbPredictionStructure.c, Source/Lib/Encoder/Codec/EbPredictionStructure.h, Source/Lib/Encoder/Globals/EbEncHandle.c
SvtAv1EncApp : enable x264 style 2 pass encoder and two passes encode.
Now you can use following command line to encode 2 pass bitstream
SvtAv1EncApp --pass 1   -i <input> -b <output>
SvtAv1EncApp --pass 2  -i <input> -b <output>
SvtAv1EncApp --passes 2   -i <input> -b <output>
ffmpeg -i input.y4m -c:v libsvt_av1 -pass 1 pass1.ivf -y
ffmpeg -i input.y4m -c:v libsvt_av1 -pass 2 pass2.ivf -y
No
jing.a.sun@intel.com
guangxin.xu@intel.com
=> SvtAv1EncApp : combined 2 passes encode

test/quantize_func_test.cc
Fixing error from #1362 
Eric Lam
=> fix remaining license change mistake

Source/Lib/Common/Codec/EbDefinitions.h
Temporary fix for the r2r when not using lp option in the cmd line. 
closes #1442
=> turn OFF TX_EARLY_EXIT

Source/Lib/Decoder/Codec/EbDecObmc.c, Source/Lib/Decoder/Codec/EbDecPicMgr.c
Fixes decoding issues
Fixes #1337
@1480c1
=> Decoder: Fix issues with the decoder not producing the correct output

.github/workflows/ci.yml, Source/App/EncApp/EbAppConfig.c, Source/Lib/Common/ASM_AVX2/EbPictureOperators_Intrinsic_AVX2.c, Source/Lib/Common/Codec/EbInvTransforms.c, Source/Lib/Common/Codec/EbMalloc.h, Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c, Source/Lib/Encoder/Codec/EbModeDecision.c, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbProductCodingLoop.c, Source/Lib/Encoder/Codec/EbTransforms.c
Seems these weren't being picked up by Github Actions' cppcheck
Closes #1351
Fixes #1435
@1480c1
=> Wshadow: Add -Wshadow to CI and fix shadow variable issues

.github/workflows/ci.yml, Source/Lib/Common/ASM_AVX2/convolve_avx2.h, Source/Lib/Common/ASM_SSE2/synonyms.h, Source/Lib/Encoder/ASM_AVX2/highbd_fwd_txfm_avx2.c, Source/Lib/Encoder/ASM_AVX2/pickrst_avx2.c, Source/Lib/Encoder/Codec/palette.c
Since it seems some people are still using really old compilers.
Has potential speed penalty due to different code
@1480c1
=> Add support for gcc 4.8.5

Docs/svt-av1_encoder_user_guide.md, Source/API/EbSvtAv1Enc.h, Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppContext.c, Source/App/EncApp/EbAppMain.c, Source/Lib/Encoder/Globals/EbEncHandle.c
Remove deprecated tokens , clean the app and update the encoder user guide
=> Remove deprecated tokens , clean the app and update the encoder user guide

Source/Lib/Common/Codec/EbThreads.c
=> minor change for EbThreads.c

Config/Sample.cfg, Docs/svt-av1_encoder_user_guide.md, Source/API/EbSvtAv1Enc.h, Source/App/EncApp/EbAppConfig.c, Source/App/EncApp/EbAppConfig.h, Source/App/EncApp/EbAppContext.c, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Globals/EbEncHandle.c, gstreamer-plugin/gstsvtav1enc.c
Clean up run-time flags that are not applicable any more
update users guide and sample.cfg at the same time
=> Run-time flags cleanup

CONTRIBUTING.md, README.md, Source/API/EbDebugMacros.h
Add a the contributing agreement link to be executed for contributions to be accepted
@hassount
=> Add a the Contributing agreement links to be executed for contributions

Build/linux/build.sh
inspired by @ccccheung, test if sudo is needed before asking for it, also fix using toolchains, along with general improvements
@1480c1
=> Buildsh: Only use sudo if needed and some other cleanups

.github/workflows/macos.yml
To help fix macOS+brew issues
@1480c1
=> macOS: reset brew if brew fails|| brew update-reset

.github/workflows/patches.yml
=> github: use the same brew commands for the ffmpeg job

Source/Lib/Encoder/ASM_AVX2/palette_avx2.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.c, Source/Lib/Encoder/Codec/aom_dsp_rtcd.h, Source/Lib/Encoder/Codec/k_means_template.h, Source/Lib/Encoder/Codec/palette.c, test/PaletteModeUtilTest.cc
Fixes some conflicts with libaom
@1480c1
=> fix some conflicts with libaom

Build/linux/build.sh
Reverts AOMediaCodec/SVT-AV1#1593
=> Revert "build.sh: Fix broken build script"

Source/API/EbDebugMacros.h, Source/Lib/Encoder/Codec/EbEncDecProcess.c, Source/Lib/Encoder/Codec/EbModeDecisionConfigurationProcess.c, Source/Lib/Encoder/Codec/EbModeDecisionProcess.c, Source/Lib/Encoder/Codec/EbModeDecisionProcess.h, Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c, Source/Lib/Encoder/Codec/EbPictureDecisionProcess.c, Source/Lib/Encoder/Codec/EbProductCodingLoop.c, Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c, Source/Lib/Encoder/Codec/firstpass.c
Preset tuning for better tradeoffs
@PhoenixWorth 
@Arhuan 
M7 
PSNR Y | PSNR  U | PSNR  V | Speed Dev | memory   reduction
2.01% | 1.60% | 1.98% | 28% | 0%
=> Preset tuning

Docs/svt-av1-decoder-design.md, Source/Lib/Decoder/Codec/EbDecCdef.c, Source/Lib/Decoder/Codec/EbDecHandle.h, Source/Lib/Decoder/Codec/EbDecLF.c, Source/Lib/Decoder/Codec/EbDecMemInit.c, Source/Lib/Decoder/Codec/EbDecNbr.c, Source/Lib/Decoder/Codec/EbDecParseBlock.c, Source/Lib/Decoder/Codec/EbDecParseFrame.c, Source/Lib/Decoder/Codec/EbDecParseFrame.h, Source/Lib/Decoder/Codec/EbDecParseInterBlock.c, Source/Lib/Decoder/Codec/EbDecParseObu.c, Source/Lib/Decoder/Codec/EbDecProcess.c, Source/Lib/Decoder/Codec/EbDecProcessBlock.c, Source/Lib/Decoder/Codec/EbDecProcessFrame.c, Source/Lib/Decoder/Codec/EbDecRestoration.c, Source/Lib/Decoder/Codec/EbDecUtils.c, third_party/googletest/include/gtest/internal/gtest-port.h
Replaces some terms that might have negative connotations with alternatives
Closes #1581 
@1480c1
=> Replace certain terms with alternatives

Docs/svt-av1-decoder-design.md, Source/Lib/Common/Codec/EbDefinitions.h, Source/Lib/Common/Codec/EbInterPrediction.c, Source/Lib/Decoder/Codec/EbDecParseFrame.c, Source/Lib/Encoder/Codec/EbSequenceControlSet.c, test/Doxyfile
additional missed changes in the prior pr
currently, the remaining uses of `master` are in the context of git branches and a single email
related to #1581 
@1480c1
=> Addition wording changes that were missed

Source/Lib/Encoder/Globals/EbEncHandle.c
Fix the 1 pass VBR setting for tpl and LAD
@anaghdin
=> Fix the 1 pass VBR tpl/lad setting

.gitlab-ci.yml
Adds Windows and macOS jobs to Gitlab CI
https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/1
Marvin Scholz
=> Gitlab CI additions

.gitlab-ci.yml
Follow up to #1623 
Marvin Scholz
=> CI: Rename jobs for more consistency and readability

Source/App/EncApp/CMakeLists.txt, test/e2e_test/CMakeLists.txt
TARGET_EXISTS is not present on some older cmake
/cc @paulsgh 
@hassount 
@1480c1
=> CMake: replace generator expression with if(target)

.gitlab-ci.yml, test/stylecheck.sh
Use our alpine image and also add some functional fixes along with automatic branch parsing of upstream
@ePirat 
@1480c1
=> Stylecheck

.github/workflows/ci.yml, Source/Lib/Encoder/ASM_AVX512/highbd_fwd_txfm_AVX512.c, Source/Lib/Encoder/ASM_AVX512/pickrst_avx512.c
=> github: add avx512 compilation test

.gitlab-ci.yml
Forgot to open a pr for this one
@1480c1
=> gitlab: add linux enc test

Source/API/EbSvtAv1.h, Source/API/EbSvtAv1Metadata.h, Source/App/EncApp/EbAppProcessCmd.c, Source/Lib/Encoder/Codec/EbEntropyCoding.c, Source/Lib/Encoder/Codec/EbEntropyCoding.h, Source/Lib/Encoder/Codec/EbPacketizationProcess.c, Source/Lib/Encoder/Codec/EbPacketizationReorderQueue.h, Source/Lib/Encoder/Codec/EbResourceCoordinationProcess.c, Source/Lib/Encoder/Globals/EbEncHandle.c, Source/Lib/Encoder/Globals/EbMetadataHandle.c, test/e2e_test/SvtAv1E2EFramework.cc
This is a first effort to add metadata OBU encoding support.
I have previously contributed a similar API for libaom (commit 1) so users can feel familiar with the usage to attach a metadata stream to a to-be-encoded frame.
Please review this approach as I am not totally familiarized with the packetization process and the last changes in packetization_kernel were to get the metadata OBU in the correct position so it relates to the frame it corresponds inside the stream, but maybe you can provide feedback. Also, had to increase the value in packetization_reorder_entry_ctor from 16 to 160 to be able to write the metadata as 16 wasn't enough. This number is arbitrary.
Testing this commit with ffmpeg generates a stream with metadata OBUs in same order and format of what we get from libaom.
The …
=> Add metadata OBU encoding support

Source/Lib/Common/Codec/EbThreads.c, Source/Lib/Common/Codec/EbThreads.h, Source/Lib/Encoder/Codec/firstpass.c
Static Analysis fixes
@ttrigui
=> Static Analysis fixes
